import * as React from "react";
import { Heading, Stack, Text } from "./Foundation";

type Tone = "neutral" | "info" | "success" | "warning" | "danger";
export const Badge: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLSpanElement> & { tone?: Tone } & React.RefAttributes<HTMLSpanElement>> = React.forwardRef<HTMLSpanElement, React.HTMLAttributes<HTMLSpanElement> & { tone?: Tone }>(function Badge({ tone = "neutral", className, ...props }, ref) { return <span ref={ref} className={["z-badge", `z-tone-${tone}`, className].filter(Boolean).join(" ")} {...props} />; });

export interface CalloutProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "title"> { tone?: Tone; title?: React.ReactNode; icon?: React.ReactNode; }
export const Callout: React.ForwardRefExoticComponent<CalloutProps & React.RefAttributes<HTMLDivElement>> = React.forwardRef<HTMLDivElement, CalloutProps>(function Callout({ tone = "info", title, icon, children, className, ...props }, ref) { return <div ref={ref} role={tone === "danger" ? "alert" : "note"} className={["z-callout", `z-tone-${tone}`, className].filter(Boolean).join(" ")} {...props}>{icon ? <span aria-hidden="true">{icon}</span> : null}<div>{title ? <strong>{title}</strong> : null}<div>{children}</div></div></div>; });

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> { value?: number; max?: number; label: string; showValue?: boolean; }
export const Progress: React.ForwardRefExoticComponent<ProgressProps & React.RefAttributes<HTMLDivElement>> = React.forwardRef<HTMLDivElement, ProgressProps>(function Progress({ value, max = 100, label, showValue, className, ...props }, ref) { const percent = value === undefined ? undefined : Math.min(100, Math.max(0, value / max * 100)); return <div className="z-progress-wrap"><div className="z-progress-label"><span>{label}</span>{showValue && percent !== undefined ? <span>{Math.round(percent)}%</span> : null}</div><div ref={ref} role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={max} aria-valuenow={value} className={["z-progress", value === undefined ? "z-progress--indeterminate" : "", className].filter(Boolean).join(" ")} {...props}><span className="z-progress__bar" style={percent === undefined ? undefined : { width: `${percent}%` }} /></div></div>; });

export interface SkeletonProps extends React.HTMLAttributes<HTMLSpanElement> { width?: string | number; height?: string | number; shape?: "text" | "rectangle" | "circle"; }
export const Skeleton: React.ForwardRefExoticComponent<SkeletonProps & React.RefAttributes<HTMLSpanElement>> = React.forwardRef<HTMLSpanElement, SkeletonProps>(function Skeleton({ width, height, shape = "text", style, className, ...props }, ref) { return <span ref={ref} aria-hidden="true" className={["z-skeleton", `z-skeleton--${shape}`, className].filter(Boolean).join(" ")} style={{ width, height, ...style }} {...props} />; });

export interface EmptyStateProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "title"> { title: React.ReactNode; description?: React.ReactNode; icon?: React.ReactNode; action?: React.ReactNode; }
export const EmptyState: React.ForwardRefExoticComponent<EmptyStateProps & React.RefAttributes<HTMLDivElement>> = React.forwardRef<HTMLDivElement, EmptyStateProps>(function EmptyState({ title, description, icon, action, className, ...props }, ref) { return <Stack ref={ref} align="center" className={["z-empty-state", className].filter(Boolean).join(" ")} {...props}>{icon ? <span className="z-empty-state__icon" aria-hidden="true">{icon}</span> : null}<Heading level={3}>{title}</Heading>{description ? <Text muted>{description}</Text> : null}{action}</Stack>; });

export interface TableColumn<Row> { id: string; header: React.ReactNode; cell: (row: Row) => React.ReactNode; align?: "start" | "center" | "end"; }
export interface TableProps<Row> extends Omit<React.TableHTMLAttributes<HTMLTableElement>, "children"> { caption: React.ReactNode; columns: readonly TableColumn<Row>[]; rows: readonly Row[]; rowKey: (row: Row) => React.Key; empty?: React.ReactNode; }
export function Table<Row>({ caption, columns, rows, rowKey, empty = "No data", className, ...props }: TableProps<Row>): React.ReactElement { return <div className="z-table-scroll" tabIndex={0} role="region" aria-label={typeof caption === "string" ? caption : undefined}><table className={["z-table", className].filter(Boolean).join(" ")} {...props}><caption className="z-visually-hidden">{caption}</caption><thead><tr>{columns.map((column) => <th key={column.id} scope="col" className={`z-align-${column.align ?? "start"}`}>{column.header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={rowKey(row)}>{columns.map((column) => <td key={column.id} className={`z-align-${column.align ?? "start"}`}>{column.cell(row)}</td>)}</tr>) : <tr><td colSpan={columns.length} className="z-table__empty">{empty}</td></tr>}</tbody></table></div>; }
