import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { Dialog } from "./Overlays";
import { Input } from "./Input";

export interface TabItem<Value extends string = string> { value: Value; label: React.ReactNode; content: React.ReactNode; disabled?: boolean; }
export interface TabsProps<Value extends string = string> { items: readonly TabItem<Value>[]; value?: Value; defaultValue?: Value; onChange?: (value: Value) => void; orientation?: "horizontal" | "vertical"; activationMode?: "automatic" | "manual"; className?: string; }
export function Tabs<Value extends string = string>({ items, value, defaultValue, onChange, orientation = "horizontal", activationMode = "automatic", className }: TabsProps<Value>): React.ReactElement {
  return <TabsPrimitive.Root className={["z-tabs", className].filter(Boolean).join(" ")} value={value} defaultValue={defaultValue ?? items[0]?.value} onValueChange={(next) => onChange?.(next as Value)} orientation={orientation} activationMode={activationMode}><TabsPrimitive.List className="z-tabs__list" aria-orientation={orientation}>{items.map((item) => <TabsPrimitive.Trigger key={item.value} value={item.value} disabled={item.disabled} className="z-tabs__trigger">{item.label}</TabsPrimitive.Trigger>)}</TabsPrimitive.List>{items.map((item) => <TabsPrimitive.Content key={item.value} value={item.value} className="z-tabs__content">{item.content}</TabsPrimitive.Content>)}</TabsPrimitive.Root>;
}

export const Toolbar: React.ForwardRefExoticComponent<React.HTMLAttributes<HTMLDivElement> & { orientation?: "horizontal" | "vertical"; label: string } & React.RefAttributes<HTMLDivElement>> = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement> & { orientation?: "horizontal" | "vertical"; label: string }>(function Toolbar({ orientation = "horizontal", label, className, onKeyDown, ...props }, ref) {
  return <div {...props} ref={ref} role="toolbar" aria-label={label} aria-orientation={orientation} className={["z-toolbar", `z-toolbar--${orientation}`, className].filter(Boolean).join(" ")} onKeyDown={(event) => { onKeyDown?.(event); if (event.defaultPrevented) return; const previous = orientation === "horizontal" ? "ArrowLeft" : "ArrowUp"; const next = orientation === "horizontal" ? "ArrowRight" : "ArrowDown"; if (![previous, next, "Home", "End"].includes(event.key)) return; const controls = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),[href],[tabindex]:not([tabindex="-1"])')); const index = controls.indexOf(document.activeElement as HTMLElement); const target = event.key === "Home" ? controls[0] : event.key === "End" ? controls.at(-1) : controls[(index + (event.key === next ? 1 : -1) + controls.length) % controls.length]; if (target) { event.preventDefault(); target.focus(); } }} />;
});

export interface CommandItem { id: string; label: string; keywords?: readonly string[]; group?: string; shortcut?: string; disabled?: boolean; onSelect: () => void; }
export interface CommandMenuProps { open: boolean; onOpenChange: (open: boolean) => void; items: readonly CommandItem[]; title?: string; placeholder?: string; emptyText?: string; }
export function CommandMenu({ open, onOpenChange, items, title = "Command menu", placeholder = "Type a command…", emptyText = "No commands found" }: CommandMenuProps): React.ReactElement {
  const [query, setQuery] = React.useState("");
  const [active, setActive] = React.useState(0);
  const filtered = React.useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return items.filter((item) => !needle || `${item.label} ${(item.keywords ?? []).join(" ")}`.toLocaleLowerCase().includes(needle)); }, [items, query]);
  React.useEffect(() => setActive(0), [query]);
  const choose = (item: CommandItem | undefined) => { if (!item || item.disabled) return; item.onSelect(); onOpenChange(false); };
  return <Dialog title={title} open={open} onOpenChange={onOpenChange} className="z-command-menu"><div onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((current) => Math.min(filtered.length - 1, current + 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((current) => Math.max(0, current - 1)); } if (event.key === "Home") { event.preventDefault(); setActive(0); } if (event.key === "End") { event.preventDefault(); setActive(Math.max(0, filtered.length - 1)); } if (event.key === "Enter") { event.preventDefault(); choose(filtered[active]); } }}><Input autoFocus aria-label={placeholder} placeholder={placeholder} value={query} onChange={(event) => setQuery(event.target.value)} aria-controls="z-command-results" aria-activedescendant={filtered[active] ? `z-command-${filtered[active].id}` : undefined} /><div id="z-command-results" role="listbox" aria-label={`${title} results`} className="z-command-results">{filtered.length ? filtered.map((item, index) => <button key={item.id} id={`z-command-${item.id}`} type="button" role="option" aria-selected={index === active} disabled={item.disabled} className="z-command-item" onPointerMove={() => setActive(index)} onClick={() => choose(item)}><span>{item.label}</span>{item.shortcut ? <span className="z-menu-shortcut">{item.shortcut}</span> : null}</button>) : <div className="z-empty-inline">{emptyText}</div>}</div></div></Dialog>;
}

export interface TreeNode { id: string; label: React.ReactNode; children?: readonly TreeNode[]; disabled?: boolean; }
export interface TreeViewProps { nodes: readonly TreeNode[]; selectedId?: string; defaultExpandedIds?: readonly string[]; expandedIds?: readonly string[]; onExpandedChange?: (ids: string[]) => void; onSelect?: (id: string) => void; label: string; className?: string; }
interface FlatNode { node: TreeNode; level: number; parentId?: string; }
export function TreeView({ nodes, selectedId, defaultExpandedIds = [], expandedIds, onExpandedChange, onSelect, label, className }: TreeViewProps): React.ReactElement {
  const [internalExpanded, setInternalExpanded] = React.useState(() => new Set(defaultExpandedIds));
  const expanded = React.useMemo(() => new Set(expandedIds ?? internalExpanded), [expandedIds, internalExpanded]);
  const flat = React.useMemo(() => { const result: FlatNode[] = []; const visit = (items: readonly TreeNode[], level: number, parentId?: string) => items.forEach((node) => { result.push({ node, level, parentId }); if (node.children?.length && expanded.has(node.id)) visit(node.children, level + 1, node.id); }); visit(nodes, 1); return result; }, [nodes, expanded]);
  const [focusedId, setFocusedId] = React.useState(() => flat.find((item) => !item.node.disabled)?.node.id);
  const refs = React.useRef(new Map<string, HTMLButtonElement>());
  const updateExpanded = (next: Set<string>) => { if (expandedIds === undefined) setInternalExpanded(next); onExpandedChange?.([...next]); };
  const toggle = (id: string, force?: boolean) => { const next = new Set(expanded); const shouldExpand = force ?? !next.has(id); if (shouldExpand) next.add(id); else next.delete(id); updateExpanded(next); };
  const focusAt = (index: number) => { const target = flat[index]; if (!target) return; setFocusedId(target.node.id); queueMicrotask(() => refs.current.get(target.node.id)?.focus()); };
  return <div role="tree" aria-label={label} className={["z-tree", className].filter(Boolean).join(" ")}>{flat.map((entry, index) => { const hasChildren = Boolean(entry.node.children?.length); const isExpanded = hasChildren && expanded.has(entry.node.id); return <button key={entry.node.id} ref={(element) => { if (element) refs.current.set(entry.node.id, element); else refs.current.delete(entry.node.id); }} type="button" role="treeitem" aria-level={entry.level} aria-expanded={hasChildren ? isExpanded : undefined} aria-selected={selectedId === entry.node.id} disabled={entry.node.disabled} tabIndex={focusedId === entry.node.id ? 0 : -1} className="z-tree-item" style={{ "--z-tree-level": entry.level } as React.CSSProperties} onFocus={() => setFocusedId(entry.node.id)} onClick={() => { if (hasChildren) toggle(entry.node.id); onSelect?.(entry.node.id); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); focusAt(Math.min(flat.length - 1, index + 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); focusAt(Math.max(0, index - 1)); } else if (event.key === "Home") { event.preventDefault(); focusAt(0); } else if (event.key === "End") { event.preventDefault(); focusAt(flat.length - 1); } else if (event.key === "ArrowRight" && hasChildren) { event.preventDefault(); if (!isExpanded) toggle(entry.node.id, true); else focusAt(index + 1); } else if (event.key === "ArrowLeft") { event.preventDefault(); if (isExpanded) toggle(entry.node.id, false); else if (entry.parentId) { const parentIndex = flat.findIndex((item) => item.node.id === entry.parentId); focusAt(parentIndex); } } else if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect?.(entry.node.id); } }}><span className="z-tree-item__chevron" aria-hidden="true">{hasChildren ? (isExpanded ? "▾" : "▸") : ""}</span><span>{entry.node.label}</span></button>; })}</div>;
}

export interface SplitPaneProps extends React.HTMLAttributes<HTMLDivElement> { first: React.ReactNode; second: React.ReactNode; size?: number; defaultSize?: number; onSizeChange?: (percent: number) => void; min?: number; max?: number; orientation?: "horizontal" | "vertical"; firstLabel?: string; secondLabel?: string; }
export function SplitPane({ first, second, size, defaultSize = 50, onSizeChange, min = 15, max = 85, orientation = "horizontal", className, firstLabel = "First panel", secondLabel = "Second panel", ...props }: SplitPaneProps): React.ReactElement {
  const [internal, setInternal] = React.useState(defaultSize); const current = size ?? internal; const root = React.useRef<HTMLDivElement>(null);
  const set = (next: number) => { const clamped = Math.min(max, Math.max(min, next)); if (size === undefined) setInternal(clamped); onSizeChange?.(clamped); };
  const move = (event: PointerEvent) => { const rect = root.current?.getBoundingClientRect(); if (!rect) return; set(orientation === "horizontal" ? (event.clientX - rect.left) / rect.width * 100 : (event.clientY - rect.top) / rect.height * 100); };
  return <div {...props} ref={root} className={["z-split-pane", `z-split-pane--${orientation}`, className].filter(Boolean).join(" ")}><div className="z-split-pane__panel" aria-label={firstLabel} style={{ flexBasis: `${current}%` }}>{first}</div><div role="separator" aria-orientation={orientation === "horizontal" ? "vertical" : "horizontal"} aria-valuemin={min} aria-valuemax={max} aria-valuenow={Math.round(current)} tabIndex={0} className="z-split-pane__handle" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); window.addEventListener("pointermove", move); window.addEventListener("pointerup", () => window.removeEventListener("pointermove", move), { once: true }); }} onKeyDown={(event) => { const delta = event.shiftKey ? 10 : 1; if (["ArrowLeft", "ArrowUp"].includes(event.key)) { event.preventDefault(); set(current - delta); } if (["ArrowRight", "ArrowDown"].includes(event.key)) { event.preventDefault(); set(current + delta); } if (event.key === "Home") { event.preventDefault(); set(min); } if (event.key === "End") { event.preventDefault(); set(max); } }} /><div className="z-split-pane__panel" aria-label={secondLabel} style={{ flexBasis: `${100 - current}%` }}>{second}</div></div>;
}
