import * as React from "react";
import type { Story } from "@ladle/react";
import { Badge, Button, Callout, Checkbox, Code, CommandMenu, Dialog, EmptyState, Field, FieldError, Grid, Heading, IconButton, Input, Inline, Kbd, Label, Description, NumberInput, Popover, Progress, RadioGroup, SearchField, Select, Skeleton, SplitPane, Stack, Table, Tabs, Text, Textarea, Toggle, Tooltip, TreeView } from "./index";
import { ControlRow } from "./recipes";

const themes = ["light", "dark", "high-contrast"] as const;
function Matrix({ children }: { children: React.ReactNode }): React.ReactElement { return <Grid columns={3}>{themes.map((theme) => <Stack key={theme} data-z-theme={theme} data-z-density={theme === "light" ? "comfortable" : "compact"} style={{ padding: 16, background: "var(--z-color-canvas)", border: "1px solid var(--z-color-border)", direction: theme === "high-contrast" ? "rtl" : "ltr" }}><Heading level={3}>{theme}</Heading>{children}</Stack>)}</Grid>; }

export const Foundations: Story = () => <Matrix><Heading>Foundation</Heading><Text>Dense, calm application UI with <Code>--z-*</Code> tokens.</Text><Inline><Badge>stable</Badge><Kbd>⌘ K</Kbd><Skeleton width={80} /></Inline><Progress label="Indexing" value={64} showValue /><Callout title="No decorative accent">Color communicates state.</Callout></Matrix>;

export const Forms: Story = () => { const [enabled, setEnabled] = React.useState(true); const [number, setNumber] = React.useState(""); const [theme, setTheme] = React.useState("dark"); return <Matrix><Field><Label>Repository name with a very long label</Label><Description>Native props, refs and descriptions remain connected.</Description><Input placeholder="open-vibe" /></Field><Field invalid><Label>Remote</Label><Input defaultValue="not a URL" /><FieldError>Enter a valid URL</FieldError></Field><Textarea aria-label="Notes" placeholder="Long-form notes…" /><Checkbox label="Include ignored files" /><RadioGroup legend="Strategy" defaultValue="merge" options={[{ value: "merge", label: "Merge" }, { value: "rebase", label: "Rebase", description: "Replay local changes" }]} /><ControlRow label="Background indexing" description="Runs while the project is open"><Toggle aria-label="Background indexing" checked={enabled} onValueChange={setEnabled} /></ControlRow><NumberInput aria-label="Retry count" value={number} min={0} max={9} onChange={setNumber} /><Select aria-label="Theme" value={theme} onChange={setTheme} options={[{ value: "dark", label: "Dark", group: "Built in" }, { value: "light", label: "Light", group: "Built in" }, { value: "system", label: "System", group: "Automatic", disabled: true }]} /><Inline><Button>Default</Button><Button variant="primary" loading>Saving</Button><Button disabled>Disabled</Button><IconButton aria-label="More actions">•••</IconButton></Inline></Matrix>; };

export const Overlays: Story = () => <Stack><Heading>Overlays</Heading><Inline><Dialog trigger={<Button>Open dialog</Button>} title="Rename branch" description="Focus is trapped until the dialog closes."><Field><Label>Name</Label><Input defaultValue="feature/tokens" /></Field></Dialog><Popover trigger={<Button>Open popover</Button>} ariaLabel="Branch details"><Text>Portalled and collision-aware.</Text></Popover><Tooltip content="Keyboard users receive this description"><Button>Hover or focus</Button></Tooltip></Inline></Stack>;

export const Navigation: Story = () => <Stack><Tabs items={[{ value: "files", label: "Files", content: <TreeView label="Project files" defaultExpandedIds={["src"]} nodes={[{ id: "src", label: "src", children: [{ id: "index", label: "index.ts" }, { id: "css", label: "styles.css" }] }, { id: "readme", label: "README.md" }]} /> }, { value: "changes", label: "Changes", content: "No changes" }]} /><SplitPane first={<div style={{ padding: 12 }}>Inspector</div>} second={<div style={{ padding: 12 }}>Preview</div>} defaultSize={35} style={{ height: 180, border: "1px solid var(--z-color-border)" }} /></Stack>;

export const SettingsInspector: Story = () => { const [autosave, setAutosave] = React.useState(true); const [fontSize, setFontSize] = React.useState("14"); return <div data-testid="settings-composition" style={{ maxWidth: 660 }}><Stack gap="2"><Heading>Editor inspector</Heading><Text muted>Workspace-specific behavior. Changes apply immediately.</Text><ControlRow label="Autosave" description="Write changes after 750 ms of inactivity"><Toggle aria-label="Autosave" checked={autosave} onValueChange={setAutosave} /></ControlRow><ControlRow label="Font size" description="Between 10 and 28 pixels"><NumberInput aria-label="Font size" value={fontSize} min={10} max={28} precision={0} onChange={setFontSize} /></ControlRow><ControlRow label="Cursor animation" description="Reduced motion overrides this setting"><Select aria-label="Cursor animation" value="smooth" options={[{ value: "off", label: "Off" }, { value: "smooth", label: "Smooth" }]} /></ControlRow></Stack></div>; };

export const CommandPaletteComposition: Story = () => { const [open, setOpen] = React.useState(true); return <><Button onClick={() => setOpen(true)}>Open command palette</Button><CommandMenu open={open} onOpenChange={setOpen} items={[{ id: "file", label: "Open file…", group: "Files", shortcut: "⌘P", onSelect: () => undefined }, { id: "symbol", label: "Go to symbol…", group: "Navigation", shortcut: "⌘⇧O", onSelect: () => undefined }, { id: "restart", label: "Restart language server", keywords: ["lsp"], onSelect: () => undefined }]} /></>; };

interface Row { id: number; branch: string; status: string; checks: number; }
const rows: Row[] = [{ id: 1, branch: "codex/zazaru-tokens", status: "Ready", checks: 18 }, { id: 2, branch: "fix/tree-focus", status: "Review", checks: 16 }];
export const DataManagementComposition: Story = () => { const [query, setQuery] = React.useState(""); const filtered = rows.filter((row) => row.branch.includes(query)); return <Stack><Inline style={{ justifyContent: "space-between" }}><div><Heading>Change queues</Heading><Text muted>Local branches waiting for integration.</Text></div><Button variant="primary">Create queue</Button></Inline><SearchField label="Filter branches" value={query} onChange={(event) => setQuery(event.target.value)} onClear={() => setQuery("")} /><Table caption="Change queues" rows={filtered} rowKey={(row) => row.id} columns={[{ id: "branch", header: "Branch", cell: (row) => <Code>{row.branch}</Code> }, { id: "status", header: "Status", cell: (row) => <Badge>{row.status}</Badge> }, { id: "checks", header: "Checks", align: "end", cell: (row) => row.checks }]} empty={<EmptyState title="No matching queues" description="Try a shorter filter." />} /></Stack>; };
