import type { Translations } from "./ru";

export const am: Partial<Translations> = {
  app: "መተግበሪያ",
  general: "አጠቃላይ",
  hotkeys: "አቋራጮች",
  server: "አገልጋይ",
  providers: "አቅራቢዎች",
  models: "ሞዴሎች",
  language: "ቋንቋ",
  languageDesc: "የOpenVibe ማሳያ ቋንቋ ይቀይሩ",
  autoAccept: "ፍቃዶችን በራስ ሰር መቀበል",
  autoAcceptDesc: "የፍቃድ ጥያቄዎች በራስ ሰር ይጸድቃሉ",
  terminalShell: "የተርሚናል ሼል",
  terminalShellDesc: "ለተሰራው ተርሚናል ሼል",
  showThinking: "የማሰብ ማጠቃለያ አሳይ",
  showThinkingDesc: "የሞዴሉን የማሰብ ሂደት አሳይ",
  theme: "ገጽታ",
  themeDesc: "የመተግበሪያውን ገጽታ ይምረጡ",
  colorScheme: "የቀለም እቅድ",
  colorSchemeDesc: "ብርሃን፣ ጨለማ ወይም ስርዓት",
  dark: "ጨለማ",
  light: "ብርሃን",
  system: "ስርዓት",
  font: "ቅርጸ ቁምፊ",
  fontDesc: "ዋና የበይነገጽ ቅርጸ ቁምፊ",
  systemFont: "ስርዓት",
  codeFont: "የኮድ ቅርጸ ቁምፊ",
  codeFontDesc: "ለአርታኢ እና ተርሚናል ሞኖስፔስ ቅርጸ ቁምፊ",
  soundNotifications: "የድምጽ ማሳወቂያዎች",
  soundEnabled: "ድምጽ አንቃ",
  soundEnabledDesc: "የድምጽ ማሳወቂያዎችን አጫውት",
  soundOnComplete: "ተግባር ተጠናቀቀ",
  soundOnCompleteDesc: "በተሳካ ሁኔታ ሲጠናቀቅ ድምጽ",
  soundOnStop: "ተግባር አቁም",
  soundOnStopDesc: "በግዳጅ ሲቆም ድምጽ",
  connectedProviders: "የተገናኙ አቅራቢዎች",
  disconnect: "አቋርጥ",
  connect: "አገናኝ",
  customProvider: "የበለጠ አቅራቢ",
  searchModels: "ሞዴሎችን ፈልግ...",
  loadingModels: "ሞዴሎችን በመጫን ላይ...",
  noModels: "የሞዴሎችን ዝርዝር ለማየት ቢያንስ አንድ አቅራቢ ያገናኙ።",
  editProvider: "አቅራቢ አርትዕ",
  customProviderTitle: "የበለጠ አቅራቢ",
  name: "ስም",
  hideKey: "ቁልፍ ደብቅ",
  showKey: "ቁልፍ አሳይ",
  save: "አስቀምጥ",
  newSession: "አዲስ ክፍለ ጊዜ",
  prevSession: "ያለፈ ክፍለ ጊዜ",
  nextSession: "ቀጣይ ክፍለ ጊዜ",
  openTerminal: "ተርሚናል ክፈት",
  searchPlaceholder: "ትእዛዛትን፣ ፋይሎችን ፈልግ...",
  searchIn: "በ {folder} ውስጥ ፈልግ",
  menu: "ሜኑ",
  hideSessions: "ክፍለ ጊዜዎችን ደብቅ",
  showSessions: "ክፍለ ጊዜዎችን አሳይ",
  newSessionTitle: "አዲስ ክፍለ ጊዜ",
  prevSessionTitle: "ያለፈ ክፍለ ጊዜ",
  nextSessionTitle: "ቀጣይ ክፍለ ጊዜ",
  toggleTerminal: "ተርሚናል ቀይር",
  toggleSessions: "ክፍለ ጊዜዎችን ቀይር",
  hideFileTree: "የፋይል ዛፍ ደብቅ",
  showFileTree: "የፋይል ዛፍ አሳይ",
  toggleFileTree: "የፋይል ዛፍ ቀይር",
  close: "ዝጋ",
  minimizeLabel: "አሳንስ",
  maximizeLabel: "አስፋ",
  closeLabel: "ዝጋ",
  welcomeSubtitle: "ምንም ፕሮጀክት አልተከፈተም። ክፍለ ጊዜ ለመጀመር አቃፊ ይምረጡ።",
  openProject: "ፕሮጀክት ክፈት",
  fatalErrorTitle: "vibe መጀመር አልተሳካም",
  fatalErrorHint: "VIBE_API_KEY ከ vibe አጠገብ ባለው .env፣ በ ~/.vibe/config፣ ወይም እንደ አካባቢ ተለዋዋጭ ያዘጋጁ።",
  loadingText: "Openvibe በመጫን ላይ…",
  noSessions: "እስካሁን ምንም ክፍለ ጊዜ የለም",
  untitled: "ርዕስ የሌለው",
  deleteSession: "ክፍለ ጊዜ ሰርዝ",
  selectModel: "ሞዴል ይምረጡ:",
  revertToMessage: "ወደዚህ መልእክት ተመለስ",
  copy: "ቅዳ",
  completed: "ተጠናቋል",
  diff: "ልዩነት",
  regenerate: "እንደገና አመንጭ",
  reading: "በማንበብ ላይ",
  read: "ተነቧል",
  failedWrite: "መጻፍ አልተሳካም",
  writing: "በመጻፍ ላይ",
  written: "ተፈጥሯል",
  failedEdit: "ማስተካከል አልተሳካም",
  editing: "በማስተካከል ላይ",
  edited: "ተስተካክሏል",
  listing: "በዝርዝር ላይ",
  listed: "ተዘርዝሯል",
  searchingCodebase: "በኮድ መሰረት ውስጥ በመፈለግ ላይ",
  searchedCodebase: "Search in codebase",
  running: "በማሄድ ላይ",
  ran: "ተሄዷል",
  tool: "መሳሪያ",
  newFile: "አዲስ ፋይል",
  newFolder: "አዲስ አቃፊ",
  rename: "ስም ቀይር",
  cut: "ቁረጥ",
  paste: "ለጥፍ",
  delete: "ሰርዝ",
  deleteConfirm: "{name}ን ሰርዝ?",
  createFailed: "መፍጠር አልተሳካም: {error}",
  renameFailed: "ስም መቀየር አልተሳካም: {error}",
  newFileTooltip: "አዲስ ፋይል",
  newFolderTooltip: "አዲስ አቃፊ",
  refreshTooltip: "አድስ",
  collapseAllTooltip: "ሁሉንም አጥፋ",
  loading: "በመጫን ላይ…",
  closeProject: "ፕሮጀክት ዝጋ",
  openProjectMenuItem: "ፕሮጀክት ክፈት",
  revealExplorer: "በፋይል ኤክስፕሎረር ውስጥ አሳይ",
  removeFromList: "ከዝርዝር አስወግድ",
  openFolder: "አቃፊ ክፈት",
  settings: "ቅንብሮች",
  stop: "አቁም",
  runCommand: "ትዕዛዝ አሂድ",
  sendMessage: "መልእክት ላክ",
  dropFilesAttach: "ለማያያዝ ፋይሎችን ጣል",
  remove: "አስወግድ",
  attachFiles: "ፋይሎችን አያይዝ",
  cancel: "ሰርዝ",
  processing: "በማስኬድ ላይ...",
  vibeAnything: "የሆነ ነገር ጻፍ...",
  selectModelFallback: "ሞዴል ምረጥ",
  searchModelPlaceholder: "ሞዴሎችን ፈልግ...",
  addProvider: "አቅራቢ ጨምር",
  configureModels: "ሞዴሎችን አዋቅር",
  noModelsFound: "ምንም ሞዴል አልተገኘም",
  noModelsEnabled: "ምንም ሞዴል አልነቃም",
  searching: "በመፈለግ ላይ…",
  noMatches: "ምንም አልተገኘም",
  terminal: "ተርሚናል",
  search: "ፍለጋ",
  terminalTab: "ተርሚናል {num}",
  closeTab: "ትር ዝጋ",
  newTerminal: "አዲስ ተርሚናል",
  shellExited: "[ሼል በኮድ {code} ወጥቷል]",
  cannotOpenFile: "ፋይል መክፈት አይቻልም",
  retry: "እንደገና ሞክር",
  openFileFromTree: "ከፋይል ዛፍ ፋይል ክፈት",
  unsavedChanges: "ያልተቀመጡ ለውጦች",
  closeFile: "{filename} ዝጋ",
  filePath: "የፋይል ዱካ",
  selectFileToEdit: "ለማስተካከል ፋይል ምረጥ",
  copyCode: "ቅዳ",
  openSettingsHotkey: "ቅንብሮችን ክፈት",
  clearChatHotkey: "ቻት አጽዳ",
  manuallyStopped: "ስራው በተጠቃሚ ተቆሟል",

  // MCP
  edit: "አርትዕ",
  mcpServers: "MCP አገልጋዮች",
  mcpServersCount: "MCP አገልጋዮች ({count})",
  mcpRefreshStatuses: "ሁኔታዎችን አድስ",
  mcpNoServersConfigured: "ምንም MCP አገልጋይ አልተዋቀረም",
  mcpOpenSettings: "የ MCP ቅንብሮችን ክፈት",
  mcpAddServer: "አገልጋይ አክል",
  mcpVisualEditor: "አዘጋጅ",
  mcpRawConfig: "Raw ውቅር",
  mcpExport: "ላክ",
  mcpImport: "አስመጣ",
  mcpSaveTomlConfig: "TOML ውቅር አስቀምጥ",
  mcpEnableServer: "አገልጋይ አነቃቅ",
  mcpDisableServer: "አገልጋይ አቦዝን",
  mcpStartServer: "አገልጋይ ጀምር",
  mcpStopServer: "አገልጋይ አቁም",
  mcpAddServerTitle: "MCP አገልጋይ አክል",
  mcpEditServerTitle: "MCP አገልጋይ አርትዕ",
  mcpServerName: "የአገልጋይ ስም",
  mcpCommandPath: "ትዕዛዝ (የሚፈጸም ፋይል መንገድ)",
  mcpCommandPlaceholder: "npx፣ uvx ወይም /መንገድ/ወደ/ፋይል",
  mcpArguments: "ነገሮች (በክፍተት የተለዩ)",
  mcpEnvVariables: "የአካባቢ ተለዋዋጮች",
  mcpEnvKeyPlaceholder: "ቁልፍ",
  mcpEnvValuePlaceholder: "እሴት",
  mcpAddEnvVar: "+ የአካባቢ ተለዋዋጭ አክል",
  mcpEnableOnStartup: "በጅማሬ ላይ አነቃቅ",
  mcpSaveServer: "አገልጋይ አስቀምጥ",
  mcpDeleteConfirm: "በእርግጥ MCP አገልጋይ '{name}' ማሰረዝ ይፈልጋሉ?",
  mcpServerNameRequired: "የአገልጋይ ስም ያስፈልጋል።",
  mcpServerCommandRequired: "የአገልጋይ ትዕዛዝ ያስፈልጋል።",
  mcpServerExists: "በዚህ ስም ያለ አገልጋይ ಈಗಾಗಲೇ አለ።",
  mcpSaveFailed: "ማስቀመጥ አልተሳካም: {error}",
  mcpInvalidJsonFormat: "ለ MCP ውቅር ህጋዊ ያልሆነ JSON ቅርጸት",
  mcpFailedParseJson: "የመጣውን JSON መተንተን አልተሳካም",
  mcpInvalidConfigFormat: "ህጋዊ ያልሆነ የውቅር ቅርጸት: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 ፋይል ተቀይሯል",
  commitFileChanged_few: "{count} ፋይሎች ተቀይረዋል",
  commitFileChanged: "{count} ፋይሎች ተቀይረዋል",
  commitInsertion_one: "1 መስመር ተጨምሯል(+)",
  commitInsertion_few: "{count} መስመሮች ተጨምረዋል(+)",
  commitInsertion: "{count} መስመሮች ተጨምረዋል(+)",
  commitDeletion_one: "1 መስመር ተሰርዟል(-)",
  commitDeletion_few: "{count} መስመሮች ተሰርዘዋል(-)",
  commitDeletion: "{count} መስመሮች ተሰርዘዋል(-)",
  openCommit: "ኮሚት ክፈት",
  copyCommitHash: "የኮሚት ሃሽ ቅዳ",
  openOnGitHub: "በ GitHub ላይ ክፈት",
  noFilesChanged: "ምንም ፋይል አልተቀየረም",
  inlineGenerating: "ኮድ እየተፈጠረ ነው...",
  inlineEditCode: "Inline Vibe ኮዱን እንዲያርትዕ ይጠይቁ...",
  inlineRefineCode: "Inline Vibe እንደገና እንዲያሻሽል ይጠይቁ...",
  inlineSend: "ላክ (Ctrl+Enter)",
  inlineAccept: "ለውጦችን ተቀበል",
  inlineReject: "አትቀበል",
  inlinePrevDiff: "ቀዳሚ ልዩነት",
  inlineNextDiff: "ቀጣይ ልዩነት",
  videoPlay: "አጫውት (Space)",
  videoPause: "ቁም (Space)",
  videoMute: "ድምፅ አጥፋ (M)",
  videoUnmute: "ድምፅ አብራ (M)",
  videoVolume: "ድምፅ",
  videoPlaybackSpeed: "የማጫወቻ ፍጥነት",
  videoFullscreen: "ሙሉ ማስክ (F)",
  failedReadFile: "ፋይሉን ማንበብ አልተቻለም",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "ቅዳ",
  regenerateMessage: "እንደገና ፍጠር",

  // Source control
  sourceControl: "ምንጭ ቁጥጥር",
  viewAsFlatList: "እንደ ጠፍጣፋ ዝርዝር ይመልከቱ",
  viewsAndMoreActions: "እይታዎች እና ተጨማሪ ድርጊቶች...",
  stageAllChanges: "ደረጃ ሁሉም ለውጦች",
  checkoutCreateBranch: "ይመልከቱ/ቅርንጫፍ ፍጠር...",
  refreshStatus: "የማደስ ሁኔታ",
  repositories: "ማከማቻዎች",
  commitMessagePlaceholder: "መልእክት (በ«{ቅርንጫፍ}» ላይ ለመፈፀም Ctrl+Enter)",
  commitBtn: "ቁርጠኝነት",
  filterChangesPlaceholder: "የማጣሪያ ለውጦች (ለምሳሌ *.ts፣ src/)",
  clearFilter: "አጽዳ ማጣሪያ",
  noChangesDetected: "በማከማቻው ውስጥ ምንም ለውጦች አልተገኙም።",
  stagedChanges: "ደረጃ የተደረጉ ለውጦች",
  unstageAll: "ሁሉንም ያራግፉ",
  unstageChanges: "የመድረክ ለውጦች",
  discardChanges: "ለውጦችን አስወግድ",
  stageChanges: "የመድረክ ለውጦች",
  graph: "ግራፍ",
  noCommitsInGraph: "በግራፍ ታሪክ ውስጥ ምንም ቁርጠኝነት የለም።",
  newBranchName: "አዲስ የቅርንጫፍ ስም...",
  createBranchBtn: "ፍጠር",
  currentBranch: "(የአሁኑ)",

  // Auto-added translated keys
  renderFileTree: "የሚያምር የፋይል ዛፍ",
  renderFileTreeDesc: "ከጥሬ ጽሑፍ ይልቅ የአቃፊ አወቃቀሮችን እንደ ውብ UI አካል ይስሩ",
  apiKeyPlaceholder: "የኤፒአይ ቁልፍ",
  customIcon: "ብጁ አዶ (ዩአርኤል ወይም ሰቀላ)",
  modelsUrl: "የሞዴሎች ዝርዝር URL (አማራጭ)",
  headers: "ራስጌዎች",
  parameters: "መለኪያዎች",
  headerKey: "የራስጌ ስም",
  headerValue: "የራስጌ እሴት",
  paramKey: "የመለኪያ ስም",
  paramValue: "የመለኪያ እሴት",
  uploadIcon: "የመስቀል አዶ",
  closeTerminal: "ተርሚናል ዝጋ",
  hideButton: "ደብቅ",
  showButton: "አሳይ",
  restoreButtons: "አዝራሮችን እነበረበት መልስ",
  filesChanged: "{count} ፋይሎች ተለውጠዋል",
  filesChanged_one: "{count} ፋይል ተቀይሯል።",
  filesChanged_few: "{count} ፋይሎች ተለውጠዋል",
  changes: "ለውጦች",
  exploring: "ማሰስ",
  explored: "ያስሱ",
  editProject: "አርትዕ",
  editProjectTitle: "ፕሮጀክት አርትዕ",
  projectIcon: "አዶ",
  backgroundColor: "የበስተጀርባ ቀለም",
  closeFromList: "ገጠመ",
  searchInCode: "በኮድ ውስጥ ይፈልጉ",
  searchInCodePlaceholder: "ፈልግ",
  replacePlaceholder: "ተካ",
  refreshSearch: "ፍለጋ አድስ",
  clearSearchResults: "የፍለጋ ውጤቶችን አጽዳ",
  viewAsTree: "እንደ ዛፍ ተመልከት",
  showReplace: "ምትክ አሳይ",
  hideReplace: "ምትክን ደብቅ",
  matchCase: "ተዛማጅ መያዣ",
  matchWholeWord: "ሙሉውን ቃል አዛምድ",
  useRegex: "መደበኛ አገላለጽ ተጠቀም",
  preserveCase: "መያዣውን አስቀምጥ",
  replaceAll: "ሁሉንም ይተኩ",
  filesToIncludeExclude: "የሚካተቱ/የሚካተቱ ፋይሎች",
  filesToInclude: "ለማካተት ፋይሎች",
  filesToExclude: "ለማግለል ፋይሎች",
  includePlaceholder: "ለምሳሌ. *.ts፣ src/**",
  excludePlaceholder: "ለምሳሌ. መስቀለኛ_ሞዱሎች፣ *.test.ts",
  noResultsFound: "ምንም ውጤቶች አልተገኙም።",
  searchInCodeResults_one: "በ{fileCount} ፋይል ውስጥ {count} ውጤት",
  searchInCodeResults_few: "{count} ውጤቶች በ{fileCount} ፋይሎች ውስጥ",
  searchInCodeResults: "{count} ውጤቶች በ{fileCount} ፋይሎች ውስጥ",
  typeToSearch: "ፋይሎችን በይዘት ለማግኘት የፍለጋ ጥያቄ ይተይቡ።",
  loadingMatches: "በመጫን ላይ...",
  moreMatches_one: "… እና {count} ተጨማሪ ግጥሚያ",
  moreMatches_few: "… እና {count} ተጨማሪ ግጥሚያዎች",
  moreMatches: "… እና {count} ተጨማሪ ግጥሚያዎች",
  newProjectHotkey: "አዲስ ፕሮጀክት",
  closeProjectHotkey: "ፕሮጀክት ዝጋ",
  closeFileHotkey: "ፋይል ዝጋ",
  navigation: "አሰሳ",
  chat: "ተወያይ",
  workspace: "የስራ ቦታ",
  project: "ፕሮጀክት",
  editor: "አርታዒ",
  noHotkeys: "ምንም ትኩስ ቁልፎች አልተጫኑም።",
  design: "ንድፍ",
  animations: "እነማዎች",
  animStyleFade: "ደብዛዛ",
  animStyleSlide: "ስላይድ",
  animStyleScale: "ልኬት",
  animStyleFadeSlide: "ደብዝዝ + ስላይድ",
  animStyleNone: "እነማዎች የሉም",
  animProjectHover: "የፕሮጀክት ማንዣበብ",
  animProjectHoverDesc: "በፕሮጀክት ንጣፍ ላይ ሲያንዣብቡ እነማ",
  animProjectSwitch: "የፕሮጀክት መቀየሪያ",
  animProjectSwitchDesc: "አዲስ ፕሮጀክት ሲከፍቱ ሽግግር",
  animSidebarSlide: "የጎን አሞሌ",
  animSidebarSlideDesc: "የጎን ፓነልን መክፈት / መዝጋት",
  animContextMenu: "የአውድ ምናሌ",
  animContextMenuDesc: "የአውድ ምናሌ ገጽታ",
  animButtons: "አዝራሮች",
  animButtonsDesc: "በይነተገናኝ አካላት በማንዣበብ ላይ",
  animPanelAppear: "ፓነሎች እና ሞዴሎች",
  animPanelAppearDesc: "ቅንብሮች፣ ብቅ-ባዮች እና ሞዳል ገጽታ",
  animMultiplier: "አኒሜሽን ልስላሴ",
  animMultiplierDesc: "የአኒሜሽን ልስላሴ ማባዛት። 0 = ቆሟል፣ 0.5 = ፈጣን፣ 1 = መደበኛ፣ 2 = ለስላሳ፣ 5 = እጅግ በጣም ለስላሳ",
  windowEffects: "የመስኮት ውጤቶች",
  blurOverlay: "የበስተጀርባ ብዥታ",
  blurOverlayDesc: "በሞዳል መስኮቶች (ቅንብሮች፣ የአውድ ምናሌዎች) በስተጀርባ ያለውን ይዘት ያደበዝዝ።",
  blurNone: "ምንም",
  blurSubtle: "ስውር",
  blurStrong: "ጠንካራ",
  borderRadius: "የድንበር ራዲየስ",
  borderRadiusDesc: "የማዕዘን ማጠጋጋት ለUI አባሎች",
  uiZoom: "UI አጉላ",
  zoomStep: "ደረጃ አጉላ",
  zoomStepDesc: "እያንዳንዱ Ctrl+Plus/Ctrl+Minus ፕሬስ ምን ያህል የማጉላት ደረጃን ይለውጣል",
  zoomDefault: "ነባሪ ማጉላት",
  zoomDefaultDesc: "Ctrl+0 ን ሲጫኑ አጉላ",
  appName: "Vibe ዴስክቶፕን ይክፈቱ",
  appVersion: "v1.3.9",
  shell: "ዛጎል",
  langRussian: "ራሺያኛ",
  langEnglish: "እንግሊዝኛ",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "ዩክሬንያን",
  langBelarusian: "ቤላሩሲያን",
  langSpanish: "ስፓንኛ",
  langItalian: "ጣሊያንኛ",
  langPortuguese: "ፖርቹጋልኛ",
  langJapanese: "ጃፓንኛ",
  langSerbian: "ሰሪቢያን",
  langFrench: "ፈረንሳይኛ",
  langGerman: "ጀርመንኛ",
  langHindi: "ሂንዲ",
  langArabic: "አረብኛ",
  langIndonesian: "ኢንዶኔዥያን",
  langKorean: "ኮሪያኛ",
  langTurkish: "ቱሪክሽ",
  langVietnamese: "ቪትናሜሴ",
  langPolish: "ፖሊሽ",
  langDutch: "ደች",
  langRomanian: "ሮማንያን",
  langGreek: "ግሪክኛ",
  langSwedish: "ስዊድንኛ",
  langKazakh: "ካዛክሀ",
  langAzerbaijani: "አዘርባጃኒ",
  langThai: "ታይ",
  langBengali: "ቤንጋሊ",
  langPunjabi: "ፑንጃቢ",
  langBulgarian: "ቡልጋርያኛ",
  langCzech: "ቼክ",
  langFilipino: "ፊሊፒኖ",
  langPersian: "ፐርሽያን",
  langMalay: "ማላይ",
  langBurmese: "በርሚስ",
  langAmharic: "አማርኛ",
  langMarathi: "ማራቲ",
  codeTab: "ኮድ",
  editorFontSize: "የቅርጸ ቁምፊ መጠን",
  editorFontSizeDesc: "አርታዒ እና ተርሚናል ቅርጸ ቁምፊ መጠን",
  editorLineHeight: "የመስመር ቁመት",
  editorLineHeightDesc: "የአርታዒ መስመር ቁመት ማባዣ",
  editorLigatures: "ቅርጸ-ቁምፊ ሊጋቸሮች",
  editorLigaturesDesc: "የኮድ ማያያዣዎችን አንቃ (ለምሳሌ====)",
  editorCursorStyle: "የጠቋሚ ዘይቤ",
  editorCursorStyleDesc: "የአርታዒው ጠቋሚ ቅርጽ",
  editorCursorBlink: "የጠቋሚ ብልጭታ",
  editorCursorBlinkDesc: "የጠቋሚው አኒሜሽን ዘይቤ",
  cursorLine: "መስመር",
  cursorBlock: "አግድ",
  cursorUnderline: "ይሰመርበት",
  cursorLineThin: "መስመር ቀጭን",
  cursorBlockOutline: "Outline አግድ",
  cursorUnderlineThin: "ቀጭን አስምር",
  blinkBlink: "ብልጭ ድርግም የሚል",
  blinkSmooth: "ለስላሳ",
  blinkPhase: "ደረጃ",
  blinkExpand: "ዘርጋ",
  blinkSolid: "ድፍን",
  manageThemes: "ገጽታዎችን አስተዳድር",
  manageThemesDesc: "የቀለም ገጽታዎችዎን ያስመጡ ወይም ወደ ውጭ ይላኩ።",
  importTheme: "አስመጣ",
  exportTheme: "ወደ ውጪ ላክ",
  borderStyle: "የድንበር ዘይቤ",
  borderStyleDesc: "የፓነል ክፈፎችን ያብሩ ወይም ያጥፉ",
  borderStyleBordered: "ተወስኗል",
  borderStyleBorderless: "ድንበር የለሽ",
  hideSourceControl: "የምንጭ ቁጥጥርን ደብቅ",
  showSourceControl: "ምንጭ ቁጥጥር አሳይ",

  // Newly added UI strings
  startVibingBtn: "ማዋቀር ጨርስ",
  onboardingStepAnimationTitle: "እነማ ማዋቀር",
  onboardingStepSettingsTitle: "የስራ ቦታ ቅንብሮች",
  onboardingStepThemeTitle: "ገጽታ ይምረጡ",
  onboardingStepSettingsDesc: "ምርጫዎችዎን አሁን ያቀናብሩ ወይም በኋላ ይቀይሩዋቸው።",
  animationSpeedDesc: "የበይነገጽ ሽግግሮች እና ለስላሳ የውጤት ልኬት",
  animationSpeed: "የአኒሜሽን ፍጥነት",
  welcomeGreeting: "ሰላም፣ {name}",
  rerunOnboardingDesc: "የመጀመሪያውን የእንኳን ደህና መጣችሁ ማያ ገጽ እና ፈጣን የመሳፈሪያ አዋቂን እንደገና ያስነሱ",
  rerunOnboarding: "የማዋቀር አዋቂን አሂድ",
  onboardingStepAnimationDesc: "ለበይነገጽ አካላት የሽግግር ቅጦችን ይምረጡ እና ቅልጥፍናቸውን ያስተካክሉ።",
  onboardingStepThemeDesc: "ከመቀጠልዎ በፊት ገጽታን አስቀድመው ይመልከቱ።",
  welcomeThanks: "ለስራ ሂደትዎ OpenVibeን እናዋቅር።",
  backBtn: "ተመለስ",
  useRegionalProxyDesc: "የመስመር ኤፒአይ የክልል ገደቦችን ለማለፍ በአውሮፓ ውስጥ ባለው ፈጣን ተኪ አገልጋይ በኩል ይጠይቃል",
  letsVibeBtn: "Let's vibe",
  continueBtn: "ቀጥል",
  useRegionalProxy: "የክልል ፕሮክሲ (አውሮፓ) ተጠቀም",
  // Added by tools/complete_i18n.py
  copyFormatted: "ጽሑፍ ቅዳ",
  copyRaw: "እንደ ጥሬ ቅዳ",
  todoTitle: "ተግባራት",
  todoCount: "{completed} የ{count}",
  todoProgress: "የተጠናቀቁ ተግባራት፡ {completed} ከ{count}",
  todoPin: "የተግባር ዝርዝርን ሰካ",
  todoUnpin: "የተግባር ዝርዝርን ይንቀሉ",
  todoCreated: "የተግባር እቅድ ተፈጠረ",
  todoCompleted: "የተጠናቀቀ ተግባር",
  todoBlocked: "ተግባር ላይ ታግዷል",
  activityGroupTodo: "የተግባር እቅድ ማውጣት",
  errorNoticeNetworkTitle: "አገልግሎቱን ማግኘት አልተቻለም",
  errorNoticeQuotaTitle: "የአቅራቢው ገደብ ላይ ደርሷል",
  errorNoticeBlockedTitle: "የአቅራቢ መዳረሻ የተገደበ ነው።",
  errorNoticeProviderTitle: "አቅራቢው ስህተት መለሰ",
  agentRunWorkingFor: "በመስራት ላይ {time}",
  agentRunWorkedFor: "ለ{time} ሰርቷል",
  agentRunSeconds_one: "{count} ሰከንድ",
  agentRunSeconds_few: "{count} ሰከንዶች",
  agentRunSeconds: "{count} ሰከንዶች",
  agentRunMinutesShort: "{count}ሜ",
  agentRunSecondsShort: "{count}ሴ",
  activityProjectStructure: "የፕሮጀክቱን መዋቅር ማሰስ",
  activityInspectFolder: "{name}ን ማሰስ",
  activityReadFile: "በመገምገም ላይ {name}",
  activityReadCode: "ኮዱን በመገምገም ላይ",
  activitySearchQuery: "«{query}»ን በመፈለግ ላይ",
  activitySearchCode: "ተገቢውን ትግበራ በመፈለግ ላይ",
  activityUpdateFile: "{name} በማዘመን ላይ",
  activityUpdateCode: "ኮዱን በማዘመን ላይ",
  activityRunCommand: "ፕሮጀክቱን በመፈተሽ ላይ",
  activityInvestigateTask: "ተግባሩን መመርመር",
  activityUseTool: "{name}ን በማሄድ ላይ",
  gitStatus: "የመመርመር ሁኔታ",
  gitStatusDone: "የተፈተሸ ሁኔታ",
  gitBranches: "ቅርንጫፎችን መመርመር",
  gitBranchesDone: "የተፈተሸ ቅርንጫፎች",
  gitLog: "መገምገም ግዴታዎች",
  gitLogDone: "የተገመገሙ ተግባራት",
  gitDiff: "ለውጦችን በመገምገም ላይ",
  gitDiffDone: "የተገመገሙ ለውጦች",
  gitShow: "የጊት ነገርን መፈተሽ",
  gitShowDone: "የተፈተሸ የጊት ነገር",
  gitBlame: "የመስመር ደራሲነትን በመተንተን ላይ",
  gitBlameDone: "የተተነተነ የመስመር ደራሲነት",
  gitRefs: "Git refs በመፈተሽ ላይ",
  gitRefsDone: "የተፈተሸ Git refs",
  gitInspect: "የጊት ታሪክን በመፈተሽ ላይ",
  gitInspectDone: "የተፈተሸ የጊት ታሪክ",
  activityGroupSearch: "ፍለጋ",
  activityGroupRead: "ፋይሎችን ማንበብ",
  activityGroupEdit: "የተስተካከሉ ፋይሎች",
  activityGroupCommand: "ያዛል",
  activityGroupBrowse: "አቃፊዎችን ማሰስ",
  activityGroupAgent: "ምርመራ",
  activityGroupExternal: "ውጫዊ መሳሪያዎች",
  activityGroupTools: "ድርጊቶች",
  activityFetchUrl: "ድረ-ገጽ {url} በማምጣት ላይ",
  activityFetchUrlGeneral: "ድረ-ገጽ በማምጣት ላይ",
  activityGitBranches: "የጊት ቅርንጫፎችን በመመልከት ላይ",
  activityGitCommand: "Git ክወና፡ {ትእዛዝ}",
  activityGitDiff: "የጂት ልዩነትን በመፈተሽ ላይ",
  activityGitLog: "የጊት ቃል መዝገብን በመመልከት ላይ",
  activityGitStatus: "የGit ሁኔታን በመፈተሽ ላይ",
  activityGroupAgentN: "ምርመራ - {count} ተግባራት",
  activityGroupAgentN_few: "Исследование - {መቁጠር} задачи",
  activityGroupAgentN_one: "ምርመራ - ተግባር {count}",
  activityGroupBrowseN: "{count} አቃፊዎችን በማሰስ ላይ",
  activityGroupBrowseN_few: "Просмотр (መቁጠር) ፓፖክ",
  activityGroupBrowseN_one: "{count} አቃፊን በማሰስ ላይ",
  activityGroupCommandN: "የ{count} ትዕዛዞችን በማስኬድ ላይ",
  activityGroupCommandN_few: "Выполнение {መቁጠር} команд",
  activityGroupCommandN_one: "የ{count} ትዕዛዝን በማስኬድ ላይ",
  activityGroupEditN: "{count} ፋይሎችን በማርትዕ ላይ",
  activityGroupEditN_few: "Редактирование {መቁጠር} файлов",
  activityGroupEditN_one: "{count} ፋይልን በማስተካከል ላይ",
  activityGroupExternalN: "ውጫዊ መሳሪያዎች — ጥሪዎች {count}",
  activityGroupExternalN_few: "Внешние инструменты — {count} выzoва",
  activityGroupExternalN_one: "ውጫዊ መሣሪያ - ጥሪ (ቁጥር)",
  activityGroupGit: "Git ክወናዎች",
  activityGroupGitN: "Git — {count} ክወናዎች",
  activityGroupGitN_few: "Git — {count} ብዙ",
  activityGroupGitN_one: "Git — {count} ክወና",
  activityGroupReadN: "{count} ፋይሎችን በማንበብ ላይ",
  activityGroupReadN_few: "Чтение {መቁጠር} файлов",
  activityGroupReadN_one: "{count} ፋይልን በማንበብ ላይ",
  activityGroupSearchN: "ፈልግ — {count} መጠይቆች",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "ፈልግ — {count} መጠይቅ",
  activityGroupTodoN: "እቅድ ማውጣት - ተግባራትን {count}",
  activityGroupTodoN_few: "Планирование — {መቁጠር} задачи",
  activityGroupTodoN_one: "እቅድ ማውጣት - ተግባር {count}",

  // Agent flow (linear run redesign)
  flowThinking: "እያሰበ ነው…",
  flowThought: "የማሰብ ሂደት",
  flowAnalysis: "ትንተና",
  flowCountRead: "{count} ንባቦች",
  flowCountSearch: "{count} ፍለጋዎች",
  flowCountBrowse: "{count} የአቃፊ እይታዎች",
  flowCountWeb: "{count} የድር ፍለጋዎች",
  flowCountGit: "{count} የgit ክንውኖች",
  activityGroupToolsN: "እርምጃዎች {count}",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "እርምጃ {count}",
  activityGroupWeb: "የድር ፍለጋ",
  activityGroupWebN: "የድር ፍለጋ — {count} መጠይቆች",
  activityGroupWebN_few: "Веб-поиск - {መቁጠር} запроса",
  activityGroupWebN_one: "የድር ፍለጋ — {count} መጠይቅ",
  activityRepeatedCalls: "ጥሪዎች {count}",
  activityWebSearch: '"{query}" ድር በመፈለግ ላይ',
  activityWebSearchGeneral: "መረጃ ለማግኘት ድርን መፈለግ",
  addModel: "ሞዴል አክል",
  customModelsLabel: "ሞዴሎች",
  experimentalExtremeRadius: "የሙከራ ከፍተኛ ራዲየስ (እስከ 100 ፒክስል)",
  experimentalExtremeRadiusDesc: "የዩአይ ድንበር ራዲየስ እስከ 100 ፒክስል ማቀናበር ይፈቅዳል። የሙከራ ባንዲራ!",
  fetchedUrl: "የተገኘ URL",
  fetchingUrl: "URL በማምጣት ላይ",
  generateCommitMessage: "በ AI የቁርጥ ቀን መልእክት ይፍጠሩ",
  hideToolCalls: "የመሳሪያ ጥሪዎችን ደብቅ",
  modelDisplayName: "የማሳያ ስም",
  modelIdPlaceholder: "ሞዴል-መታወቂያ",
  promptMarkdown: "ፈጣን ግቤት ውስጥ ምልክት ማድረጊያ",
  promptMarkdownDesc: "ጥያቄዎችን በሚተይቡበት ጊዜ የማርክ ዳውን ቅርጸት በቀጥታ ስጥ",
  promptMarkdownGhost: "የአገባብ ምልክቶችን አሳይ (**)",
  promptMarkdownGhostDesc: "የደበዘዙ አገባብ ቁምፊዎችን (**, `, #) በተዘጋጀው ጽሑፍ ውስጥ አሳይ",
  reasoningEffortHigh: "ከፍተኛ",
  reasoningEffortLow: "ዝቅተኛ",
  reasoningEffortMedium: "መካከለኛ",
  reasoningEffortNone: "ምንም",
  searchedWeb: "የድር ፍለጋ",
  searchingWeb: "ድር መፈለግ",
  showToolCalls: "የመሳሪያ ጥሪዎችን አሳይ",
  tabStyle: "የትር ዘይቤ",
  tabStyleDefault: "ነባሪ",
  tabStyleDesc: "ካሬ ወይም የተጠጋጉ እንክብሎች ለአርታዒ ትሮች",
  tabStylePills: "እንክብሎች",
};
