import type { Translations } from "./ru";

export const cs: Partial<Translations> = {
  app: "Aplikace",
  general: "Obecné",
  hotkeys: "Klávesové zkratky",
  server: "Server",
  providers: "Poskytovatelé",
  models: "Modely",
  language: "Jazyk",
  languageDesc: "Změnit jazyk zobrazení OpenVibe",
  autoAccept: "Automaticky přijímat oprávnění",
  autoAcceptDesc: "Žádosti o oprávnění budou automaticky schváleny",
  terminalShell: "Terminálový shell",
  terminalShellDesc: "Shell pro vestavěný terminál",
  showThinking: "Zobrazit souhrny myšlení",
  showThinkingDesc: "Zobrazit proces myšlení modelu",
  theme: "Téma",
  themeDesc: "Vyberte téma aplikace",
  colorScheme: "Barevné schéma",
  colorSchemeDesc: "Světlý, tmavý nebo systémový",
  dark: "Tmavý",
  light: "Světlý",
  system: "Systémový",
  font: "Písmo",
  fontDesc: "Hlavní písmo rozhraní",
  systemFont: "Systémové",
  codeFont: "Písmo kódu",
  codeFontDesc: "Neproporcionální písmo pro editor a terminál",
  soundNotifications: "Zvuková upozornění",
  soundEnabled: "Povolit zvuky",
  soundEnabledDesc: "Přehrávat zvuková upozornění",
  soundOnComplete: "Dokončení úkolu",
  soundOnCompleteDesc: "Zvuk při úspěšném dokončení",
  soundOnStop: "Zastavení úkolu",
  soundOnStopDesc: "Zvuk při vynuceném zastavení",
  connectedProviders: "Připojení poskytovatelé",
  disconnect: "Odpojit",
  connect: "Připojit",
  customProvider: "Vlastní poskytovatel",
  searchModels: "Hledat modely...",
  loadingModels: "Načítání modelů...",
  noModels: "Chcete-li zobrazit seznam modelů, připojte alespoň jednoho poskytovatele.",
  editProvider: "Upravit poskytovatele",
  customProviderTitle: "Vlastní poskytovatel",
  name: "Název",
  hideKey: "Skrýt klíč",
  showKey: "Zobrazit klíč",
  save: "Uložit",
  newSession: "Nová relace",
  prevSession: "Předchozí relace",
  nextSession: "Další relace",
  openTerminal: "Otevřít terminál",
  searchPlaceholder: "Hledat příkazy, soubory...",
  searchIn: "Hledat v {folder}",
  menu: "Menu",
  hideSessions: "Skrýt relace",
  showSessions: "Zobrazit relace",
  newSessionTitle: "Nová relace",
  prevSessionTitle: "Předchozí relace",
  nextSessionTitle: "Další relace",
  toggleTerminal: "Přepnout terminál",
  toggleSessions: "Přepnout relace",
  hideFileTree: "Skrýt strom souborů",
  showFileTree: "Zobrazit strom souborů",
  toggleFileTree: "Přepnout strom souborů",
  close: "Zavřít",
  minimizeLabel: "Minimalizovat",
  maximizeLabel: "Maximalizovat",
  closeLabel: "Zavřít",
  welcomeSubtitle: "Není otevřen žádný projekt. Vyberte složku a spusťte relaci.",
  openProject: "Otevřít projekt",
  fatalErrorTitle: "Vibe nelze spustit",
  fatalErrorHint: "Nastavte VIBE_API_KEY v .env vedle vibe, v ~/.vibe/config nebo jako proměnnou prostředí.",
  loadingText: "Openvibe se načítá…",
  noSessions: "Zatím žádné relace",
  untitled: "Bez názvu",
  deleteSession: "Smazat relaci",
  selectModel: "Vyberte model:",
  revertToMessage: "Vrátit se k této zprávě",
  copy: "Kopírovat",
  completed: "Dokončeno",
  diff: "Rozdíly",
  regenerate: "Přegenerovat",
  reading: "Čtení",
  read: "Přečteno",
  failedWrite: "Chyba zápisu",
  writing: "Zápis",
  written: "Vytvořeno",
  failedEdit: "Chyba úpravy",
  editing: "Úprava",
  edited: "Upraveno",
  listing: "Výpis",
  listed: "Vypsáno",
  searchingCodebase: "Hledání v kódové bázi",
  searchedCodebase: "Search in codebase",
  running: "Spouštění",
  ran: "Spuštěno",
  tool: "Nástroj",
  newFile: "Nový soubor",
  newFolder: "Nová složka",
  rename: "Přejmenovat",
  cut: "Vyjmout",
  paste: "Vložit",
  delete: "Smazat",
  deleteConfirm: "Smazat {name}?",
  createFailed: "Chyba vytvoření: {error}",
  renameFailed: "Chyba přejmenování: {error}",
  newFileTooltip: "Nový soubor",
  newFolderTooltip: "Nová složka",
  refreshTooltip: "Obnovit",
  collapseAllTooltip: "Sbalit vše",
  loading: "načítání…",
  closeProject: "Zavřít projekt",
  openProjectMenuItem: "Otevřít projekt",
  revealExplorer: "Zobrazit v průzkumníku",
  removeFromList: "Odebrat ze seznamu",
  openFolder: "Otevřít složku",
  settings: "Nastavení",
  stop: "Zastavit",
  runCommand: "Spustit příkaz",
  sendMessage: "Odeslat zprávu",
  dropFilesAttach: "Přetáhněte soubory pro přiložení",
  remove: "Odebrat",
  attachFiles: "Přiložit soubory",
  shell: "Shell",
  cancel: "Zrušit",
  processing: "Zpracování...",
  vibeAnything: "Napište cokoliv...",
  selectModelFallback: "Vyberte model",
  searchModelPlaceholder: "Hledat modely...",
  addProvider: "Přidat poskytovatele",
  configureModels: "Konfigurovat modely",
  noModelsFound: "Nenalezeny žádné modely",
  noModelsEnabled: "Žádné povolené modely",
  searching: "hledání…",
  noMatches: "žádné shody",
  terminal: "Terminál",
  search: "Hledání",
  terminalTab: "Terminál {num}",
  closeTab: "Zavřít kartu",
  newTerminal: "Nový terminál",
  shellExited: "[shell skončil s kódem {code}]",
  cannotOpenFile: "Soubor nelze otevřít",
  retry: "Zkusit znovu",
  openFileFromTree: "Otevřete soubor ze stromu souborů",
  unsavedChanges: "Neuložené změny",
  closeFile: "Zavřít {filename}",
  filePath: "Cesta k souboru",
  selectFileToEdit: "Vyberte soubor k úpravě",
  copyCode: "Kopírovat",
  openSettingsHotkey: "Otevřít nastavení",
  clearChatHotkey: "Vymazat chat",
  appName: "OpenVibe Desktop",
  appVersion: "v1.3.9",
  manuallyStopped: "Zastaveno uživatelem",

  // MCP
  edit: "Upravit",
  mcpServers: "Servery MCP",
  mcpServersCount: "Servery MCP ({count})",
  mcpRefreshStatuses: "Obnovit stav",
  mcpNoServersConfigured: "Žádné servery MCP nebyly nakonfigurovány",
  mcpOpenSettings: "Otevřít nastavení MCP",
  mcpAddServer: "Přidat server",
  mcpVisualEditor: "Editor",
  mcpRawConfig: "Raw konfigurace",
  mcpExport: "Exportovat",
  mcpImport: "Importovat",
  mcpSaveTomlConfig: "Uložit konfig TOML",
  mcpEnableServer: "Povolit server",
  mcpDisableServer: "Zakázat server",
  mcpStartServer: "Spustit server",
  mcpStopServer: "Zastavit server",
  mcpAddServerTitle: "Přidat server MCP",
  mcpEditServerTitle: "Upravit server MCP",
  mcpServerName: "Název serveru",
  mcpCommandPath: "Příkaz (cesta k spustitelnému souboru)",
  mcpCommandPlaceholder: "npx, uvx nebo /cesta/k/souboru",
  mcpArguments: "Argumenty (oddělené mezerou)",
  mcpEnvVariables: "Proměnné prostředí",
  mcpEnvKeyPlaceholder: "KLÍČ",
  mcpEnvValuePlaceholder: "HODNOTA",
  mcpAddEnvVar: "+ Přidat proměnnou prostředí",
  mcpEnableOnStartup: "Povolit při spuštění",
  mcpSaveServer: "Uložit server",
  mcpDeleteConfirm: "Opravdu chcete smazat MCP server '{name}'?",
  mcpServerNameRequired: "Název serveru je povinný.",
  mcpServerCommandRequired: "Příkaz serveru je povinný.",
  mcpServerExists: "Server s tímto názvem již existuje.",
  mcpSaveFailed: "Uložení selhalo: {error}",
  mcpInvalidJsonFormat: "Neplatný formát JSON pro konfiguraci MCP",
  mcpFailedParseJson: "Nepodařilo se zpracovat importovaný JSON",
  mcpInvalidConfigFormat: "Neplatný formát konfigurace: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 soubor změněn",
  commitFileChanged_few: "{count} soubory změněny",
  commitFileChanged: "{count} souborů změněno",
  commitInsertion_one: "1 vložení(+)",
  commitInsertion_few: "{count} vložení(+)",
  commitInsertion: "{count} vložení(+)",
  commitDeletion_one: "1 smazání(-)",
  commitDeletion_few: "{count} smazání(-)",
  commitDeletion: "{count} smazání(-)",
  openCommit: "Otevřít commit",
  copyCommitHash: "Kopírovat hash commitu",
  openOnGitHub: "Otevřít na GitHub",
  noFilesChanged: "Žádné soubory nezměněny",
  inlineGenerating: "Generování kódu...",
  inlineEditCode: "Požádejte Inline Vibe o úpravu kódu...",
  inlineRefineCode: "Požádejte Inline Vibe o další úpravu...",
  inlineSend: "Odeslat (Ctrl+Enter)",
  inlineAccept: "Přijmout změny",
  inlineReject: "Odmítnout",
  inlinePrevDiff: "Předchozí rozdíl",
  inlineNextDiff: "Další rozdíl",
  videoPlay: "Přehrát (Space)",
  videoPause: "Pozastavit (Space)",
  videoMute: "Ztlumit (M)",
  videoUnmute: "Zapnout zvuk (M)",
  videoVolume: "Hlasitost",
  videoPlaybackSpeed: "Rychlost přehrávání",
  videoFullscreen: "Celá obrazovka (F)",
  failedReadFile: "Nepodařilo se přečíst soubor",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "Kopírovat",
  regenerateMessage: "Znovu vygenerovat",

  // Source control
  sourceControl: "Ovládání zdroje",
  viewAsFlatList: "Zobrazit jako plochý seznam",
  viewsAndMoreActions: "Zobrazení a další akce...",
  stageAllChanges: "Uspořádejte všechny změny",
  checkoutCreateBranch: "Pokladna / Vytvořit pobočku...",
  refreshStatus: "Stav obnovení",
  repositories: "Úložiště",
  commitMessagePlaceholder: "Zpráva (Ctrl+Enter pro potvrzení na '{branch}')",
  commitBtn: "Spáchat",
  filterChangesPlaceholder: "Změny filtrů (např. *.ts, src/)",
  clearFilter: "Vymazat filtr",
  noChangesDetected: "V úložišti nebyly zjištěny žádné změny.",
  stagedChanges: "Postupné změny",
  unstageAll: "Unstage All",
  unstageChanges: "Unstage změny",
  discardChanges: "Zahodit změny",
  stageChanges: "Změny fáze",
  graph: "Graf",
  noCommitsInGraph: "Žádné potvrzení v historii grafu.",
  newBranchName: "Nový název pobočky...",
  createBranchBtn: "Vytvořit",
  currentBranch: "(proud)",

  // Auto-added translated keys
  renderFileTree: "Krásný souborový strom",
  renderFileTreeDesc:
    "Vykreslete struktury složek jako krásnou komponentu uživatelského rozhraní namísto surového textu",
  apiKeyPlaceholder: "Klíč API",
  customIcon: "Vlastní ikona (URL nebo nahrání)",
  modelsUrl: "Adresa URL seznamu modelů (volitelné)",
  headers: "Záhlaví",
  parameters: "Parametry",
  headerKey: "Název záhlaví",
  headerValue: "Hodnota záhlaví",
  paramKey: "Název parametru",
  paramValue: "Hodnota parametru",
  uploadIcon: "Ikona nahrávání",
  closeTerminal: "Zavřete terminál",
  hideButton: "Skrýt",
  showButton: "Show",
  restoreButtons: "Tlačítka pro obnovení",
  filesChanged: "Počet změněných souborů: {count}",
  filesChanged_one: "{count} soubor změněn",
  filesChanged_few: "Počet změněných souborů: {count}",
  changes: "Změny",
  exploring: "Zkoumání",
  explored: "Prozkoumat",
  editProject: "Upravit",
  editProjectTitle: "Upravit projekt",
  projectIcon: "Ikona",
  backgroundColor: "Barva pozadí",
  closeFromList: "Blízko",
  searchInCode: "Hledejte v kódu",
  searchInCodePlaceholder: "Vyhledávání",
  replacePlaceholder: "Nahradit",
  refreshSearch: "Obnovit vyhledávání",
  clearSearchResults: "Vymazat výsledky vyhledávání",
  viewAsTree: "Zobrazit jako strom",
  showReplace: "Zobrazit Nahradit",
  hideReplace: "Skrýt Nahradit",
  matchCase: "Match Case",
  matchWholeWord: "Porovnejte celé slovo",
  useRegex: "Použijte regulární výraz",
  preserveCase: "Zachovat případ",
  replaceAll: "Nahradit vše",
  filesToIncludeExclude: "Soubory k zahrnutí/vyloučení",
  filesToInclude: "soubory k zahrnutí",
  filesToExclude: "soubory k vyloučení",
  includePlaceholder: "např. *.ts, src/**",
  excludePlaceholder: "např. node_modules, *.test.ts",
  noResultsFound: "Nebyly nalezeny žádné výsledky.",
  searchInCodeResults_one: "{count} výsledek v {fileCount} souboru",
  searchInCodeResults_few: "{count} výsledků v {fileCount} souborech",
  searchInCodeResults: "{count} výsledků v {fileCount} souborech",
  typeToSearch: "Zadejte vyhledávací dotaz a vyhledejte soubory podle obsahu.",
  loadingMatches: "Načítání...",
  moreMatches_one: "… a {count} další shoda",
  moreMatches_few: "… a {count} dalších shod",
  moreMatches: "… a {count} dalších shod",
  newProjectHotkey: "Nový projekt",
  closeProjectHotkey: "Zavřít projekt",
  closeFileHotkey: "Zavřít soubor",
  navigation: "Navigace",
  chat: "Povídání",
  workspace: "Pracovní prostor",
  project: "Projekt",
  editor: "Editor",
  noHotkeys: "Nejsou načteny žádné klávesové zkratky",
  design: "Design",
  animations: "Animace",
  animStyleFade: "Vyblednout",
  animStyleSlide: "Skluzavka",
  animStyleScale: "Měřítko",
  animStyleFadeSlide: "Fade + Slide",
  animStyleNone: "Žádné animace",
  animProjectHover: "Umístění projektu",
  animProjectHoverDesc: "Animace při najetí myší na dlaždici projektu",
  animProjectSwitch: "Přepínač projektu",
  animProjectSwitchDesc: "Přechod při otevření nového projektu",
  animSidebarSlide: "Postranní panel",
  animSidebarSlideDesc: "Otevírání/zavírání bočního panelu",
  animContextMenu: "Kontextové menu",
  animContextMenuDesc: "Vzhled kontextového menu",
  animButtons: "Tlačítka",
  animButtonsDesc: "Interaktivní prvky na přechodu",
  animPanelAppear: "Panely a modály",
  animPanelAppearDesc: "Nastavení, vyskakovací okna a modální vzhled",
  animMultiplier: "Plynulost animace",
  animMultiplierDesc:
    "Multiplikátor plynulosti animace. 0 = zastaveno, 0,5 = svižné, 1 = normální, 2 = hladké, 5 = ultra hladké",
  windowEffects: "Efekty okna",
  blurOverlay: "Rozostření pozadí",
  blurOverlayDesc: "Rozmazání obsahu za modálními okny (nastavení, kontextové nabídky)",
  blurNone: "Žádný",
  blurSubtle: "Jemný",
  blurStrong: "Silný",
  borderRadius: "Poloměr hranice",
  borderRadiusDesc: "Zaoblení rohů pro prvky uživatelského rozhraní",
  uiZoom: "UI Zoom",
  zoomStep: "Krok přiblížení",
  zoomStepDesc: "Jak moc každé stisknutí Ctrl+Plus/Ctrl+Minus změní úroveň přiblížení",
  zoomDefault: "Výchozí přiblížení",
  zoomDefaultDesc: "Úroveň přiblížení při stisknutí Ctrl+0",
  langRussian: "ruština",
  langEnglish: "angličtina",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "ukrajinština",
  langBelarusian: "běloruský",
  langSpanish: "španělština",
  langItalian: "italština",
  langPortuguese: "portugalština",
  langJapanese: "japonský",
  langSerbian: "srbština",
  langFrench: "francouzština",
  langGerman: "Němec",
  langHindi: "hindština",
  langArabic: "arabština",
  langIndonesian: "indonéština",
  langKorean: "korejština",
  langTurkish: "turečtina",
  langVietnamese: "vietnamština",
  langPolish: "polština",
  langDutch: "holandský",
  langRomanian: "rumunština",
  langGreek: "řecký",
  langSwedish: "švédský",
  langKazakh: "kazašský",
  langAzerbaijani: "ázerbájdžánský",
  langThai: "thajština",
  langBengali: "bengálský",
  langPunjabi: "pandžábština",
  langBulgarian: "bulharský",
  langCzech: "čeština",
  langFilipino: "filipínský",
  langPersian: "Peršan",
  langMalay: "malajština",
  langBurmese: "barmský",
  langAmharic: "amharština",
  langMarathi: "maráthština",
  codeTab: "Kód",
  editorFontSize: "Velikost písma",
  editorFontSizeDesc: "Velikost písma editoru a terminálu",
  editorLineHeight: "Výška řádku",
  editorLineHeightDesc: "Násobitel výšky řádku editoru",
  editorLigatures: "Ligatury písma",
  editorLigaturesDesc: "Povolit kódovací ligatury (např. =>, ===)",
  editorCursorStyle: "Styl kurzoru",
  editorCursorStyleDesc: "Tvar kurzoru editoru",
  editorCursorBlink: "Kurzor bliká",
  editorCursorBlinkDesc: "Styl animace kurzoru",
  cursorLine: "Čára",
  cursorBlock: "Blok",
  cursorUnderline: "Zdůraznit",
  cursorLineThin: "Tenká čára",
  cursorBlockOutline: "Obrys bloku",
  cursorUnderlineThin: "Podtržení Tenké",
  blinkBlink: "Blikat",
  blinkSmooth: "Hladký",
  blinkPhase: "Fáze",
  blinkExpand: "Rozšířit",
  blinkSolid: "Solidní",
  manageThemes: "Správa motivů",
  manageThemesDesc: "Importujte nebo exportujte svá barevná témata",
  importTheme: "Importovat",
  exportTheme: "Vývozní",
  borderStyle: "Styl ohraničení",
  borderStyleDesc: "Zapnout nebo vypnout okraje panelu",
  borderStyleBordered: "Ohraničený",
  borderStyleBorderless: "Bez hranic",
  hideSourceControl: "Skrýt ovládání zdroje",
  showSourceControl: "Zobrazit ovládání zdroje",

  // Newly added UI strings
  rerunOnboardingDesc: "Znovu spusťte úvodní uvítací obrazovku a průvodce rychlým vstupem",
  useRegionalProxy: "Použít regionální proxy (Evropa)",
  startVibingBtn: "Dokončete nastavení",
  backBtn: "Zadní",
  welcomeThanks: "Pojďme nastavit OpenVibe pro váš pracovní postup.",
  letsVibeBtn: "Let's vibe",
  continueBtn: "Pokračovat",
  onboardingStepAnimationTitle: "Nastavení animace",
  onboardingStepSettingsDesc: "Nastavte své preference nyní nebo je změňte později.",
  useRegionalProxyDesc: "Směrujte požadavky API přes rychlý proxy server v Evropě, abyste obešli regionální omezení",
  animationSpeedDesc: "Přechody rozhraní a plynulé škálování efektů",
  onboardingStepSettingsTitle: "Nastavení pracovního prostoru",
  rerunOnboarding: "Spusťte Průvodce nastavením",
  welcomeGreeting: "Dobrý den, {name}",
  onboardingStepThemeTitle: "Vyberte téma",
  animationSpeed: "Rychlost animace",
  onboardingStepAnimationDesc: "Vyberte styly přechodů pro prvky rozhraní a upravte jejich hladkost.",
  onboardingStepThemeDesc: "Než budete pokračovat, zobrazte náhled motivu.",
  // Added by tools/complete_i18n.py
  copyFormatted: "Zkopírujte text",
  copyRaw: "Kopírovat jako Raw",
  todoTitle: "Úkoly",
  todoCount: "{completed} z {count}",
  todoProgress: "Dokončené úkoly: {completed} z {count}",
  todoPin: "Připnout seznam úkolů",
  todoUnpin: "Odepnout seznam úkolů",
  todoCreated: "Vytvořený plán úkolů",
  todoCompleted: "Dokončený úkol",
  todoBlocked: "Blokováno na úkolu",
  activityGroupTodo: "plánování úkolů",
  errorNoticeNetworkTitle: "Nelze se spojit se službou",
  errorNoticeQuotaTitle: "Byl dosažen limit poskytovatele",
  errorNoticeBlockedTitle: "Přístup poskytovatele je omezen",
  errorNoticeProviderTitle: "Poskytovatel vrátil chybu",
  agentRunWorkingFor: "Pracuje {time}",
  agentRunWorkedFor: "Pracováno pro {time}",
  agentRunSeconds_one: "{count} sekundy",
  agentRunSeconds_few: "{count} sekund",
  agentRunSeconds: "{count} sekund",
  agentRunMinutesShort: "{count}m",
  agentRunSecondsShort: "{count}s",
  activityProjectStructure: "Prozkoumání struktury projektu",
  activityInspectFolder: "Prozkoumání {name}",
  activityReadFile: "Recenze {name}",
  activityReadCode: "Kontrola kódu",
  activitySearchQuery: "Vyhledávání „{query}“",
  activitySearchCode: "Hledání příslušné implementace",
  activityUpdateFile: "Aktualizace {name}",
  activityUpdateCode: "Aktualizace kódu",
  activityRunCommand: "Kontrola projektu",
  activityInvestigateTask: "Zkoumání úkolu",
  activityUseTool: "Spuštěno {name}",
  gitStatus: "Kontrola stavu",
  gitStatusDone: "Kontrolovaný stav",
  gitBranches: "Kontrola poboček",
  gitBranchesDone: "Kontrolované pobočky",
  gitLog: "Kontrola závazků",
  gitLogDone: "Zkontrolované závazky",
  gitDiff: "Kontrola změn",
  gitDiffDone: "Zkontrolované změny",
  gitShow: "Kontrola objektu Git",
  gitShowDone: "Zkontrolovaný objekt Git",
  gitBlame: "Analýza liniového autorství",
  gitBlameDone: "Analyzované liniové autorství",
  gitRefs: "Kontrola odkazů Git",
  gitRefsDone: "Zkontrolované odkazy Git",
  gitInspect: "Kontrola historie Git",
  gitInspectDone: "Zkontrolována historie Git",
  activityGroupSearch: "vyhledávání",
  activityGroupRead: "čtení souborů",
  activityGroupEdit: "upravené soubory",
  activityGroupCommand: "příkazy",
  activityGroupBrowse: "procházení složek",
  activityGroupAgent: "vyšetřování",
  activityGroupExternal: "externí nástroje",
  activityGroupTools: "akce",
  activityFetchUrl: "Načítání webové stránky {url}",
  activityFetchUrlGeneral: "Načítání webové stránky",
  activityGitBranches: "Zobrazení větví Git",
  activityGitCommand: "Operace Git: {command}",
  activityGitDiff: "Kontrola rozdílu Git",
  activityGitLog: "Zobrazení protokolu odevzdání Git",
  activityGitStatus: "Kontrola stavu Git",
  activityGroupAgentN: "Vyšetřování — {count} úkolů",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "Vyšetřování — {count} úkol",
  activityGroupBrowseN: "Procházení {count} složek",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "Procházení {count} složky",
  activityGroupCommandN: "Spuštění {count} příkazů",
  activityGroupCommandN_few: "Выполнение {count} команд",
  activityGroupCommandN_one: "Spuštění příkazu {count}",
  activityGroupEditN: "Úprava {count} souborů",
  activityGroupEditN_few: "Редактирование {count} файлов",
  activityGroupEditN_one: "Úprava {count} souboru",
  activityGroupExternalN: "Externí nástroje — {count} volání",
  activityGroupExternalN_few: "Внешние инструменты — {count} вызова",
  activityGroupExternalN_one: "Externí nástroj — {count} volání",
  activityGroupGit: "Operace Git",
  activityGroupGitN: "Git — {count} operací",
  activityGroupGitN_few: "Git — {count} операции",
  activityGroupGitN_one: "Git — operace {count}",
  activityGroupReadN: "Čtení {count} souborů",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "Čtení {count} souboru",
  activityGroupSearchN: "Vyhledávání – {count} dotazů",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "Hledat – {count} dotaz",
  activityGroupTodoN: "Plánování — {count} úkolů",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "Plánování — {count} úkol",

  // Agent flow (linear run redesign)
  flowThinking: "Přemýšlí…",
  flowThought: "Proces myšlení",
  flowAnalysis: "Analýza",
  flowCountRead_one: "{count} čtení",
  flowCountRead_few: "{count} čtení",
  flowCountRead: "{count} čtení",
  flowCountSearch_one: "{count} hledání",
  flowCountSearch_few: "{count} hledání",
  flowCountSearch: "{count} hledání",
  flowCountBrowse_one: "{count} zobrazení složky",
  flowCountBrowse_few: "{count} zobrazení složek",
  flowCountBrowse: "{count} zobrazení složek",
  flowCountWeb_one: "{count} webové hledání",
  flowCountWeb_few: "{count} webová hledání",
  flowCountWeb: "{count} webových hledání",
  flowCountGit_one: "{count} git operace",
  flowCountGit_few: "{count} git operace",
  flowCountGit: "{count} git operací",
  activityGroupToolsN: "{count} akcí",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "{count} akce",
  activityGroupWeb: "vyhledávání na webu",
  activityGroupWebN: "Vyhledávání na webu – {count} dotazů",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "Vyhledávání na webu — {count} dotaz",
  activityRepeatedCalls: "{count} hovorů",
  activityWebSearch: "Hledání „{query}“ na webu",
  activityWebSearchGeneral: "Hledání informací na webu",
  addModel: "Přidat model",
  customModelsLabel: "Modelky",
  experimentalExtremeRadius: "Experimentální extrémní rádius (až 100 pixelů)",
  experimentalExtremeRadiusDesc:
    "Umožňuje nastavit poloměr okraje uživatelského rozhraní až 100 pixelů. Experimentální vlajka!",
  fetchedUrl: "Načtená adresa URL",
  fetchingUrl: "Načítání adresy URL",
  generateCommitMessage: "Vygenerujte zprávu o potvrzení pomocí AI",
  hideToolCalls: "Skrýt volání nástrojů",
  modelDisplayName: "Zobrazovaný název",
  modelIdPlaceholder: "ID modelu",
  promptMarkdown: "Markdown v Prompt Input",
  promptMarkdownDesc: "Renderujte formátování Markdown živě při psaní výzev",
  promptMarkdownGhost: "Zobrazit značky syntaxe (**)",
  promptMarkdownGhostDesc: "Zobrazovat ve formátovaném textu matné znaky syntaxe (**, `, #).",
  reasoningEffortHigh: "Vysoký",
  reasoningEffortLow: "Nízký",
  reasoningEffortMedium: "Střední",
  reasoningEffortNone: "Žádný",
  searchedWeb: "vyhledávání na webu",
  searchingWeb: "Vyhledávání na webu",
  showToolCalls: "Zobrazit volání nástroje",
  tabStyle: "Styl karty",
  tabStyleDefault: "Výchozí",
  tabStyleDesc: "Čtvercové nebo zaoblené pilulky pro karty editoru",
  tabStylePills: "Pilulky",
};
