import type { Translations } from "./ru";

export const en: Partial<Translations> = {
  app: "Application",
  general: "General",
  hotkeys: "Hotkeys",
  server: "Server",
  providers: "Providers",
  models: "Models",
  language: "Language",
  languageDesc: "Change the display language of OpenVibe",
  autoAccept: "Auto-accept permissions",
  autoAcceptDesc: "Permission requests will be approved automatically",
  terminalShellDesc: "Shell for the built-in terminal",
  showThinking: "Show thinking summaries",
  showThinkingDesc: "Display the model's thinking process",
  renderFileTree: "Beautiful file tree",
  renderFileTreeDesc: "Render folder structures as a beautiful UI component instead of raw text",
  useRegionalProxy: "Use regional proxy (Europe)",
  useRegionalProxyDesc: "Route API requests through a fast proxy server in Europe to bypass regional restrictions",
  theme: "Theme",
  themeDesc: "Choose the application theme",
  colorScheme: "Color scheme",
  colorSchemeDesc: "Light, dark or system",
  dark: "Dark",
  light: "Light",
  system: "System",
  font: "Font",
  fontDesc: "Main interface font",
  systemFont: "System",
  codeFont: "Code font",
  codeFontDesc: "Monospace font for editor and terminal",
  soundNotifications: "Sound notifications",
  soundEnabled: "Enable sounds",
  soundEnabledDesc: "Play sound notifications",
  soundOnComplete: "Task complete",
  soundOnCompleteDesc: "Sound on successful completion",
  soundOnStop: "Task stop",
  soundOnStopDesc: "Sound on force stop",
  connectedProviders: "Connected providers",
  disconnect: "Disconnect",
  connect: "Connect",
  customProvider: "Custom provider",
  searchModels: "Search models...",
  loadingModels: "Loading models...",
  noModels: "Connect at least one provider to see the list of models.",
  editProvider: "Edit provider",
  customProviderTitle: "Custom provider",
  providerSettingsTabs: "Provider settings",
  providerGeneralTab: "General",
  providerAdvancedTab: "Advanced",
  name: "Name",
  hideKey: "Hide key",
  apiKeyPlaceholder: "API Key",
  showKey: "Show key",
  save: "Save",
  customIcon: "Custom icon (URL or upload)",
  modelsUrl: "Models list URL (optional)",
  headers: "Headers",
  parameters: "Parameters",
  headerKey: "Header name",
  headerValue: "Header value",
  paramKey: "Parameter name",
  paramValue: "Parameter value",
  uploadIcon: "Upload icon",
  customModelsLabel: "Models",
  modelIdPlaceholder: "model-id",
  modelDisplayName: "Display name",
  addModel: "Add model",
  newSession: "New session",
  prevSession: "Previous session",
  nextSession: "Next session",
  openTerminal: "Open terminal",
  searchPlaceholder: "Search commands, files...",
  searchIn: "Search in {folder}",
  menu: "Menu",
  hideSessions: "Hide sessions",
  showSessions: "Show sessions",
  newSessionTitle: "New session",
  prevSessionTitle: "Previous session",
  nextSessionTitle: "Next session",
  toggleTerminal: "Toggle Terminal",
  closeTerminal: "Close terminal",
  toggleSessions: "Toggle sessions",
  hideFileTree: "Hide file tree",
  showFileTree: "Show file tree",
  toggleFileTree: "Toggle file tree",
  hideButton: "Hide",
  showButton: "Show",
  restoreButtons: "Restore buttons",
  close: "Close",
  minimizeLabel: "Minimize",
  maximizeLabel: "Maximize",
  closeLabel: "Close",
  welcomeSubtitle: "No project open. Pick a folder to start a session in it.",
  openProject: "Open Project",
  fatalErrorTitle: "Couldn't start vibe",
  fatalErrorHint: "Set VIBE_API_KEY in a .env next to vibe, in ~/.vibe/config, or as an environment variable.",
  loadingText: "Openvibe is loading…",
  noSessions: "No chats",
  untitled: "Untitled",
  deleteSession: "Delete session",
  selectModel: "Select a model:",
  revertToMessage: "Revert to this message",
  copy: "Copy",
  copyFormatted: "Copy text",
  copyRaw: "Copy as Raw",
  completed: "Completed",
  todoTitle: "Tasks",
  todoCount: "{completed} of {count}",
  todoProgress: "Tasks completed: {completed} of {count}",
  todoStep: "Step {stepNumber} / {stepCount}",
  todoFilesChanged: "Changed {count} files",
  todoFilesChanged_one: "Changed {count} file",
  todoPin: "Pin task list",
  todoUnpin: "Unpin task list",
  todoCreated: "Created task plan",
  todoCompleted: "Completed task",
  todoBlocked: "Blocked on task",
  activityGroupTodo: "task planning",
  diff: "Diff",
  filesChanged: "{count} files changed",
  filesChanged_one: "{count} file changed",
  filesChanged_few: "{count} files changed",
  messagesReverted: "{count} messages reverted",
  messagesReverted_one: "{count} message reverted",
  changedFilesTitle: "Changed files",
  restore: "Restore",
  subagentReadOnly: "Input is not supported here.",
  goBack: "Go back",
  loadingDiff: "Loading diff:",
  showMore: "Show more...",
  emptyDirectory: "Empty directory.",
  regenerate: "Regenerate",
  changes: "Changes",

  reading: "Reading",
  read: "Read",
  failedWrite: "Failed to write",
  writing: "Writing",
  written: "Written",
  failedEdit: "Failed to edit",
  editing: "Editing",
  edited: "Edited",
  listing: "Listing",
  listed: "Listed",
  searchingCodebase: "Searching in codebase",
  searchedCodebase: "Search in codebase",
  running: "Running",
  ran: "Ran",
  exploring: "Exploring",
  explored: "Explore",
  tool: "Tool",
  newFile: "New File",
  newFolder: "New Folder",
  rename: "Rename",
  cut: "Cut",
  paste: "Paste",
  delete: "Delete",
  deleteConfirm: "Delete {name}?",
  createFailed: "Failed to create: {error}",
  renameFailed: "Failed to rename: {error}",
  newFileTooltip: "New file",
  newFolderTooltip: "New folder",
  refreshTooltip: "Refresh",
  collapseAllTooltip: "Collapse all",
  loading: "loading…",
  closeProject: "Close project",
  openProjectMenuItem: "Open project",
  revealExplorer: "Reveal in file explorer",
  removeFromList: "Remove from list",
  openFolder: "Open folder",
  settings: "Settings",
  editProject: "Edit",
  editProjectTitle: "Edit project",
  projectIcon: "Icon",
  backgroundColor: "Background color",
  closeFromList: "Close",
  stop: "Stop",
  runCommand: "Run command",
  sendMessage: "Send message",
  dropFilesAttach: "Drop files to attach",
  remove: "Remove",
  attachFiles: "Attach files",
  cancel: "Cancel",
  processing: "Processing...",
  vibeAnything: "Vibe anything...",
  promptSuggestionStart: "Where do we start?",
  promptSuggestionWorkspace: "Where should we take this project?",
  promptSuggestionCode: "Is there a piece of code asking for a closer look?",
  promptSuggestionEntry: "Want to trace where this app begins?",
  promptSuggestionBlocker: "What is slowing you down right now?",
  promptSuggestionStructure: "Map this repository out?",
  promptSuggestionNext: "Find the bottleneck or pick the next move?",

  selectModelFallback: "Select Model",
  searchModelPlaceholder: "Search models...",
  addProvider: "Add provider",
  configureModels: "Configure models",
  reasoningEffortNone: "None",
  reasoningEffortLow: "Low",
  reasoningEffortMedium: "Medium",
  reasoningEffortHigh: "High",
  reasoningEffortMinimal: "Minimal",
  reasoningEffortXhigh: "Extra high",
  reasoningEffortMax: "Maximum",
  reasoningEffortUltra: "Ultra",
  composerOptions: "Composer options",
  composerModel: "Model",
  composerEffort: "Effort",
  composerPermissionAsk: "Ask for approval",
  composerPermissionAskDesc: "Always ask to edit external files and use the internet",
  composerPermissionConfirm: "Approve for me",
  composerPermissionConfirmDesc: "Only ask for actions detected as potentially unsafe",
  composerPermissionFull: "Full access",
  composerPermissionFullDesc: "Unrestricted access to the internet and any file on your computer",
  composerPermissionAuto: "Automatic",
  composerPermissionMenu: "Permission mode",
  composerPermissionAutoDesc: "Automatically allow agent actions",
  composerPermissionTitle: "How should agent actions be approved?",
  composerPermissionFullConfirmTitle: "Turn on Full Access?",
  composerPermissionFullConfirmDesc: "The agent will have unrestricted access to:",
  composerPermissionFullFiles: "Files and folders",
  composerPermissionFullFilesDesc: "Read, edit, and delete files on your computer",
  composerPermissionFullTerminal: "Terminal commands",
  composerPermissionFullTerminalDesc: "Run commands with system access",
  composerPermissionFullInternet: "Internet and connected apps",
  composerPermissionFullInternetDesc: "Access websites and connected services",
  composerPermissionFullRisk: "Full access allows the agent to take potentially unsafe actions.",
  composerPermissionFullConfirm: "Confirm",
  composerPermissionSettings: "Permission settings",
  noModelsFound: "No models found",
  noModelsEnabled: "No models enabled",
  searching: "searching…",
  noMatches: "no matches",
  terminal: "Terminal",
  terminalTab: "Terminal {num}",
  closeTab: "Close tab",
  newTerminal: "New terminal",
  shellExited: "[shell exited with code {code}]",
  cannotOpenFile: "Cannot open file",
  retry: "Retry",
  errorNoticeNetworkTitle: "Couldn't reach the service",
  errorNoticeQuotaTitle: "Provider limit reached",
  errorNoticeBlockedTitle: "Provider access is restricted",
  errorNoticeProviderTitle: "The provider returned an error",

  // Code search
  searchInCode: "Search in Code",
  searchInCodePlaceholder: "Search",
  replacePlaceholder: "Replace",
  refreshSearch: "Refresh search",
  clearSearchResults: "Clear search results",
  viewAsTree: "View as Tree",
  showReplace: "Show Replace",
  hideReplace: "Hide Replace",
  matchCase: "Match Case",
  matchWholeWord: "Match Whole Word",
  useRegex: "Use Regular Expression",
  preserveCase: "Preserve Case",
  replaceAll: "Replace All",
  filesToIncludeExclude: "Files to Include/Exclude",
  filesToInclude: "files to include",
  filesToExclude: "files to exclude",
  includePlaceholder: "e.g. *.ts, src/**",
  excludePlaceholder: "e.g. node_modules, *.test.ts",
  noResultsFound: "No results found.",
  searchInCodeResults_one: "{count} result in {fileCount} file",
  searchInCodeResults_few: "{count} results in {fileCount} files",
  searchInCodeResults: "{count} results in {fileCount} files",
  typeToSearch: "Type a search query to find files by content.",
  loadingMatches: "Loading...",
  moreMatches_one: "… and {count} more match",
  moreMatches_few: "… and {count} more matches",
  moreMatches: "… and {count} more matches",

  openFileFromTree: "Open a file from the file tree",
  unsavedChanges: "Unsaved changes",
  closeFile: "Close {filename}",
  filePath: "File path",
  selectFileToEdit: "Select a file to edit",
  copyCode: "Copy",
  openSettingsHotkey: "Open Settings",
  clearChatHotkey: "Clear Chat",
  newProjectHotkey: "New Project",
  closeProjectHotkey: "Close Project",
  closeFileHotkey: "Close File",
  navigation: "Navigation",
  search: "Search",
  chat: "Chat",
  workspace: "Workspace",
  project: "Project",
  editor: "Editor",
  noHotkeys: "No hotkeys loaded",
  manuallyStopped: "Manually stopped",

  // Design / Animation settings
  design: "Appearance",
  animations: "Animations",
  animStyleFade: "Fade",
  animStyleSlide: "Slide",
  animStyleScale: "Scale",
  animStyleFadeSlide: "Fade + Slide",
  animStyleNone: "No animations",
  animProjectHover: "Project hover",
  animProjectHoverDesc: "Animation when hovering over a project tile",
  animProjectSwitch: "Project switch",
  animProjectSwitchDesc: "Transition when opening a new project",
  animSidebarSlide: "Sidebar",
  animSidebarSlideDesc: "Opening/closing the side panel",
  animContextMenu: "Context menu",
  animContextMenuDesc: "Context menu appearance",
  animButtons: "Buttons",
  animButtonsDesc: "Interactive elements on hover",
  animPanelAppear: "Panels & modals",
  animPanelAppearDesc: "Settings, popups and modal appearance",
  animMultiplier: "Animation smoothness",
  animMultiplierDesc:
    "Animation smoothness multiplier. 0 = stopped, 0.5 = snappy, 1 = normal, 2 = smooth, 5 = ultra smooth",

  // Window effects
  windowEffects: "Window Effects",
  blurOverlay: "Background blur",
  blurOverlayDesc: "Blur the content behind modal windows (settings, context menus)",
  blurNone: "None",
  blurSubtle: "Subtle",
  blurStrong: "Strong",

  // Radius settings
  borderRadius: "Border radius",
  borderRadiusDesc: "Corner rounding for UI elements",
  experimentalExtremeRadius: "Experimental extreme radius (up to 100px)",
  experimentalExtremeRadiusDesc: "Allows setting the UI border radius up to 100px. Experimental flag!",

  // Zoom settings
  uiZoom: "UI Zoom",
  zoomStep: "Zoom step",
  zoomStepDesc: "How much each Ctrl+Plus/Ctrl+Minus press changes the zoom level",
  zoomDefault: "Default zoom",
  zoomDefaultDesc: "Zoom level when pressing Ctrl+0",

  // MCP
  edit: "Edit",
  mcpServers: "MCP Servers",

  mcpServersCount: "MCP Servers ({count})",
  mcpRefreshStatuses: "Refresh statuses",
  mcpNoServersConfigured: "No MCP servers configured",
  mcpOpenSettings: "Open MCP Settings",
  mcpAddServer: "Add Server",
  mcpVisualEditor: "Editor",
  mcpRawConfig: "Raw Config",
  mcpExport: "Export",
  mcpImport: "Import",
  mcpSaveTomlConfig: "Save TOML Config",
  mcpEnableServer: "Enable Server",
  mcpDisableServer: "Disable Server",
  mcpStartServer: "Start Server",
  mcpStopServer: "Stop Server",
  mcpAddServerTitle: "Add MCP Server",
  mcpEditServerTitle: "Edit MCP Server",
  mcpServerName: "Server Name",
  mcpCommandPath: "Command (Executable path)",
  mcpCommandPlaceholder: "npx or uvx or /path/to/binary",
  mcpArguments: "Arguments (space-separated)",
  mcpEnvVariables: "Environment Variables",
  mcpEnvKeyPlaceholder: "KEY",
  mcpEnvValuePlaceholder: "VALUE",
  mcpAddEnvVar: "+ Add Env Variable",
  mcpEnableOnStartup: "Enable on Startup",
  mcpSaveServer: "Save Server",
  mcpDeleteConfirm: "Are you sure you want to delete MCP server '{name}'?",
  mcpServerNameRequired: "Server name is required.",
  mcpServerCommandRequired: "Server binary command is required.",
  mcpServerExists: "A server with this name already exists.",
  mcpSaveFailed: "Failed to save: {error}",
  mcpInvalidJsonFormat: "Invalid JSON format for MCP config",
  mcpFailedParseJson: "Failed to parse imported JSON",
  mcpInvalidConfigFormat: "Invalid config format: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "{count} file changed",
  commitFileChanged_few: "{count} files changed",
  commitFileChanged: "{count} files changed",
  commitInsertion_one: "{count} insertion(+)",
  commitInsertion_few: "{count} insertions(+)",
  commitInsertion: "{count} insertions(+)",
  commitDeletion_one: "{count} deletion(-)",
  commitDeletion_few: "{count} deletions(-)",
  commitDeletion: "{count} deletions(-)",
  openCommit: "Open Commit",
  copyCommitHash: "Copy Commit Hash",
  openOnGitHub: "Open on GitHub",
  noFilesChanged: "No files changed",

  // InlineVibe
  inlineGenerating: "Generating code...",
  inlineEditCode: "Ask Inline Vibe to edit code...",
  inlineRefineCode: "Ask Inline Vibe to refine/edit again...",
  inlineSend: "Send (Ctrl+Enter)",
  inlineAccept: "Accept Changes",
  inlineReject: "Reject",
  inlinePrevDiff: "Previous Diff",
  inlineNextDiff: "Next Diff",

  // Agent run
  agentRunWorkingFor: "Working {time}",
  agentRunWorkedFor: "Worked for {time}",
  showToolCalls: "Show tool calls",
  hideToolCalls: "Hide tool calls",
  agentRunSeconds_one: "{count} second",
  agentRunSeconds_few: "{count} seconds",
  agentRunSeconds: "{count} seconds",
  agentRunMinutesShort: "{count}m",
  agentRunSecondsShort: "{count}s",
  activityRepeatedCalls: "{count} calls",
  activityProjectStructure: "Exploring the project structure",
  activityInspectFolder: "Exploring {name}",
  activityReadFile: "Reviewing {name}",
  activityReadCode: "Reviewing the code",
  activitySearchQuery: "Searching for “{query}”",
  activitySearchCode: "Searching for the relevant implementation",
  activityUpdateFile: "Updating {name}",
  activityUpdateCode: "Updating the code",
  activityRunCommand: "Checking the project",
  activityInvestigateTask: "Investigating the task",
  activityUseTool: "Running {name}",
  gitStatus: "Inspecting status",
  gitStatusDone: "Inspected status",
  gitBranches: "Inspecting branches",
  gitBranchesDone: "Inspected branches",
  gitLog: "Reviewing commits",
  gitLogDone: "Reviewed commits",
  gitDiff: "Reviewing changes",
  gitDiffDone: "Reviewed changes",
  gitShow: "Inspecting Git object",
  gitShowDone: "Inspected Git object",
  gitBlame: "Analyzing line authorship",
  gitBlameDone: "Analyzed line authorship",
  gitRefs: "Inspecting Git refs",
  gitRefsDone: "Inspected Git refs",
  gitInspect: "Inspecting Git history",
  gitInspectDone: "Inspected Git history",
  searchingWeb: "Searching web",
  searchedWeb: "Web search",
  fetchingUrl: "Fetching URL",
  fetchedUrl: "Fetched URL",
  activityWebSearch: 'Searching web for "{query}"',
  activityWebSearchGeneral: "Searching web for information",
  activityFetchUrl: "Fetching webpage {url}",
  activityFetchUrlGeneral: "Fetching webpage",
  activityGitStatus: "Checking Git status",
  activityGitDiff: "Inspecting Git diff",
  activityGitLog: "Viewing Git commit log",
  activityGitBranches: "Viewing Git branches",
  activityGitCommand: "Git operation: {command}",
  activityGroupWeb: "web search",
  activityGroupSearch: "search",
  activityGroupRead: "reading files",
  activityGroupEdit: "edited files",
  activityGroupCommand: "running commands",
  activityGroupBrowse: "browsing folders",
  activityGroupAgent: "investigation",
  activityGroupGit: "Git operations",
  activityGroupExternal: "external tools",
  activityGroupTools: "actions",
  activitySummaryRead: "read files",
  activitySummaryEdit: "edited files",
  activitySummaryCommand: "ran commands",
  activitySummaryGit: "checked Git",
  activitySummaryWeb: "searched the web",
  activitySummaryAgent: "investigated the task",
  activitySummaryExternal: "used external tools",
  activitySummaryTools: "used tools",
  activitySummaryAnd: "and",

  // Group labels with count (accordion headers)
  activityGroupSearchN_one: "Search — {count} query",
  activityGroupSearchN: "Search — {count} queries",
  activityGroupReadN_one: "Reading {count} file",
  activityGroupReadN: "Reading {count} files",
  activityGroupEditN_one: "Editing {count} file",
  activityGroupEditN: "Editing {count} files",
  activityGroupCommandN_one: "Running {count} command",
  activityGroupCommandN: "Running {count} commands",
  activityGroupBrowseN_one: "Browsing {count} folder",
  activityGroupBrowseN: "Browsing {count} folders",
  activityGroupAgentN_one: "Investigation — {count} task",
  activityGroupAgentN: "Investigation — {count} tasks",
  activityGroupGitN_one: "Git — {count} operation",
  activityGroupGitN: "Git — {count} operations",
  activityGroupWebN_one: "Web search — {count} query",
  activityGroupWebN: "Web search — {count} queries",
  activityGroupExternalN_one: "External tool — {count} call",
  activityGroupExternalN: "External tools — {count} calls",
  activityGroupToolsN_one: "{count} action",
  activityGroupToolsN: "{count} actions",
  activityGroupTodoN_one: "Planning — {count} task",
  activityGroupTodoN: "Planning — {count} tasks",

  // Agent flow (linear run redesign)
  flowThinking: "Thinking…",
  flowThought: "Thought process",
  reasoningThinking: "Thinking…",
  reasoningThought: "Thought",
  reasoningForSeconds: "for {seconds} seconds",
  reasoningForFewSeconds: "for a few seconds",
  exploreLabel: "Explore",
  flowAnalysis: "Analysis",
  flowCountRead_one: "{count} read",
  flowCountRead: "{count} reads",
  flowCountSearch_one: "{count} search",
  flowCountSearch: "{count} searches",
  flowCountBrowse_one: "{count} folder view",
  flowCountBrowse: "{count} folder views",
  flowCountWeb_one: "{count} web search",
  flowCountWeb: "{count} web searches",
  flowCountGit_one: "{count} git operation",
  flowCountGit: "{count} git operations",

  // Legacy thinking block

  // VideoViewer
  videoPlay: "Play (Space)",
  videoPause: "Pause (Space)",
  videoMute: "Mute (M)",
  videoUnmute: "Unmute (M)",
  videoVolume: "Volume",
  videoPlaybackSpeed: "Playback speed",
  videoFullscreen: "Fullscreen (F)",
  failedReadFile: "Failed to read file",

  // ConnectPopup URL placeholders
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",

  // History actions
  copyMessage: "Copy",
  regenerateMessage: "Regenerate",

  // Source control
  sourceControl: "Source Control",
  hideSourceControl: "Hide Source Control",
  showSourceControl: "Show Source Control",
  viewAsFlatList: "View as Flat List",
  viewsAndMoreActions: "Views and More Actions...",
  stageAllChanges: "Stage All Changes",
  checkoutCreateBranch: "Checkout / Create Branch...",
  refreshStatus: "Refresh Status",
  repositories: "Repositories",
  commitMessagePlaceholder: "Message (Ctrl+Enter to commit on '{branch}')",
  generateCommitMessage: "Generate commit message with AI",
  commitBtn: "Commit",
  filterChangesPlaceholder: "Filter changes (e.g. *.ts, src/)",
  clearFilter: "Clear filter",
  noChangesDetected: "No changes detected in repository.",
  stagedChanges: "Staged Changes",
  unstageAll: "Unstage All",
  unstageChanges: "Unstage Changes",
  discardChanges: "Discard Changes",
  stageChanges: "Stage Changes",
  graph: "Graph",
  noCommitsInGraph: "No commits in graph history.",
  newBranchName: "New branch name...",
  createBranchBtn: "Create",
  currentBranch: "(current)",

  // Keys missing from en.ts (present in ru.ts)
  terminalShell: "Terminal Shell",
  appName: "OpenVibe Desktop",
  appVersion: "v1.3.9",
  shell: "Shell",

  // Language names
  langRussian: "Russian",
  langEnglish: "English",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "Ukrainian",
  langBelarusian: "Belarusian",
  langSpanish: "Spanish",
  langItalian: "Italian",
  langPortuguese: "Portuguese",
  langJapanese: "Japanese",
  langSerbian: "Serbian",
  langFrench: "French",
  langGerman: "German",
  langHindi: "Hindi",
  langArabic: "Arabic",
  langIndonesian: "Indonesian",
  langKorean: "Korean",
  langTurkish: "Turkish",
  langVietnamese: "Vietnamese",
  langPolish: "Polish",
  langDutch: "Dutch",
  langRomanian: "Romanian",
  langGreek: "Greek",
  langSwedish: "Swedish",
  langKazakh: "Kazakh",
  langAzerbaijani: "Azerbaijani",
  langThai: "Thai",
  langBengali: "Bengali",
  langPunjabi: "Punjabi",
  langBulgarian: "Bulgarian",
  langCzech: "Czech",
  langFilipino: "Filipino",
  langPersian: "Persian",
  langMalay: "Malay",
  langBurmese: "Burmese",
  langAmharic: "Amharic",
  langMarathi: "Marathi",

  // Code tab
  codeTab: "Code",
  editorFontSize: "Font Size",
  editorFontSizeDesc: "Editor and terminal font size",
  editorLineHeight: "Line Height",
  editorLineHeightDesc: "Editor line height multiplier",
  editorLigatures: "Font Ligatures",
  editorLigaturesDesc: "Enable coding ligatures (e.g. =>, ===)",
  editorCursorStyle: "Cursor Style",
  editorCursorStyleDesc: "Shape of the editor cursor",
  editorCursorBlink: "Cursor Blinking",
  editorCursorBlinkDesc: "Animation style of the cursor",
  cursorLine: "Line",
  cursorBlock: "Block",
  cursorUnderline: "Underline",
  cursorLineThin: "Line Thin",
  cursorBlockOutline: "Block Outline",
  cursorUnderlineThin: "Underline Thin",
  blinkBlink: "Blink",
  blinkSmooth: "Smooth",
  blinkPhase: "Phase",
  blinkExpand: "Expand",
  blinkSolid: "Solid",

  // Design tab (previously hardcoded)
  manageThemes: "Manage Themes",
  manageThemesDesc: "Import or export your color themes",
  appearanceLightTheme: "Light theme",
  appearanceDarkTheme: "Dark theme",
  appearanceAccent: "Accent color",
  appearanceForeground: "Foreground color",
  appearancePreferences: "Interface preferences",
  importTheme: "Import",
  exportTheme: "Export",
  borderStyle: "Border Style",
  borderStyleDesc: "Toggle panel borders on or off",
  borderStyleBordered: "Bordered",
  borderStyleBorderless: "Borderless",
  tabStyle: "Tab Style",
  tabStyleDesc: "Square or rounded pills for editor tabs",
  tabStyleDefault: "Default",
  tabStylePills: "Pills",

  // Onboarding view
  welcomeGreeting: "Hello, {name}",
  welcomeThanks: "Let's set up OpenVibe for your workflow.",
  letsVibeBtn: "Let's vibe",
  onboardingStepThemeTitle: "Choose a theme",
  onboardingStepThemeDesc: "Preview a theme before you continue.",
  continueBtn: "Continue",
  backBtn: "Back",
  onboardingStepSettingsTitle: "Workspace settings",
  onboardingStepSettingsDesc: "Set your preferences now or change them later.",
  onboardingStepAnimationTitle: "Animation setup",
  onboardingStepAnimationDesc: "Choose transition styles for interface elements and adjust their smoothness.",
  startVibingBtn: "Finish setup",
  rerunOnboarding: "Run Setup Wizard",
  rerunOnboardingDesc: "Re-trigger the initial welcome screen and quick onboarding wizard",
  animationSpeed: "Animation Speed",
  animationSpeedDesc: "Interface transitions and smooth effect scaling",
  promptMarkdown: "Markdown in Prompt Input",
  promptMarkdownDesc: "Render Markdown formatting live while typing prompts",
  promptMarkdownGhost: "Show Syntax Markers (**)",
  promptMarkdownGhostDesc: "Display dimmed syntax characters (**, `, #) inside formatted text",

  // Sidebar & Navigation
  newConversation: "New chat",
  conversationHistory: "History",
  scheduledTasks: "Scheduled",
  projects: "Projects",
  addProject: "Open Folder / Project",
  filterProjects: "Display Options",
  noProjects: "No projects",
  newChatInProject: "New conversation in project",
  searchHistory: "Search history...",
  noHistoryFound: "No conversations found",
  allProjects: "All projects",
  today: "Today",
  yesterday: "Yesterday",
  last7Days: "Last 7 days",
  last30Days: "Last 30 days",
  older: "Older",
  noScheduledTasks: "No scheduled tasks",
  noScheduledTasksDesc: "Automations and background timers will appear here when scheduled.",
  createScheduledTask: "Create task",
  openProjectFolder: "Reveal in file manager",
  copyProjectPath: "Copy path",
  deleteSessionConfirm: "Delete this conversation?",
  showAll: "Show all",
  showLess: "Show less",

  // Empty workspace
  emptyWorkspaceTitle: "What should we build in {project}?",
  emptyWorkspaceExplore: "Explore the code and explain how it works",
  emptyWorkspaceBuild: "Build a new feature or tool",
  emptyWorkspaceReview: "Review the code and suggest improvements",
  emptyWorkspaceFix: "Find and fix a problem",
  localWorkspace: "Local",

  // Workspace side panel
  openPanelTitle: "Open a panel",
  openPanelDescription: "Choose a workspace view to open in this side panel.",
  filesTitle: "Files",
  searchFilesPlaceholder: "Search files",
  searchingFiles: "Searching files…",
  noMatchingFiles: "No matching files",
  searchFilesFailed: "File search failed: {error}",
  searchTitle: "Search",
  gitTitle: "Git",
  terminalTitle: "Terminal",
  browserTitle: "Browser",
  browserTabs: "Browser tabs",
  browserNewTab: "New tab",
  browserBack: "Back",
  browserForward: "Forward",
  browserReload: "Reload",
  browserAddress: "Address",
  browserAddressPlaceholder: "Enter a URL",
  browserLoading: "Loading",
  browserStarting: "Starting isolated Chromium…",
  browserEmpty: "Enter an address to open a page",
  browserTakeControl: "Take control",
  browserReturnAgent: "Return to agent",
  browserManualActive: "Manual control",
  browserActivityOpen: "Opening {target}",
  browserActivityNavigate: "Navigating to {target}",
  browserActivityClick: "Clicking “{target}”",
  browserActivityFill: "Entering text in “{target}”",
  browserActivityVerify: "Checking the result",
  browserSummaryOpened: "opened the page",
  browserSummaryActions_one: "performed {count} action",
  browserSummaryActions_few: "performed {count} actions",
  browserSummaryActions: "performed {count} actions",
  browserSummaryVerified: "checked the result",
  browserDetailUrl: "URL",
  browserDetailAction: "Action",
  browserDetailTarget: "Target",
  browserDetailDuration: "Duration",
  browserDetailResult: "Result",
  listSkillsActive: "Checking available skills",
  listSkillsDone: "Loaded the available skills",
  readSkillActive: "Connecting to skill {name}",
  readSkillDone: "Loaded instructions for skill {name}",
  readSkillResourceActive: "Reading a resource for skill {name}",
  readSkillResourceDone: "Read a resource for skill {name}",
  activityGroupSkills: "skills",
  activityGroupSkillsN_one: "{count} skill",
  activityGroupSkillsN: "{count} skills",
  activitySummarySkills: "loaded skills",
  activitySummaryBrowser: "controlled the browser",
  serversTitle: "Servers",
};
