import type { Translations } from "./ru";

export const pl: Partial<Translations> = {
  app: "Aplikacja",
  general: "Ogólne",
  hotkeys: "Skróty klawiszowe",
  server: "Serwer",
  providers: "Dostawcy",
  models: "Modele",
  language: "Język",
  languageDesc: "Zmień język wyświetlania OpenVibe",
  autoAccept: "Automatycznie akceptuj uprawnienia",
  autoAcceptDesc: "Prośby o uprawnienia będą automatycznie zatwierdzane",
  terminalShellDesc: "Powłoka dla wbudowanego terminala",
  showThinking: "Pokaż podsumowania myślenia",
  showThinkingDesc: "Wyświetl proces myślowy modelu",
  theme: "Motyw",
  themeDesc: "Wybierz motyw aplikacji",
  colorScheme: "Schemat kolorów",
  colorSchemeDesc: "Jasny, ciemny lub systemowy",
  dark: "Ciemny",
  light: "Jasny",
  system: "Systemowy",
  font: "Czcionka",
  fontDesc: "Główna czcionka interfejsu",
  systemFont: "Systemowa",
  codeFont: "Czcionka kodu",
  codeFontDesc: "Czcionka o stałej szerokości dla edytora i terminala",
  soundNotifications: "Powiadomienia dźwiękowe",
  soundEnabled: "Włącz dźwięki",
  soundEnabledDesc: "Odtwarzaj powiadomienia dźwiękowe",
  soundOnComplete: "Zakończenie zadania",
  soundOnCompleteDesc: "Dźwięk po pomyślnym zakończeniu",
  soundOnStop: "Zatrzymanie zadania",
  soundOnStopDesc: "Dźwięk po wymuszonym zatrzymaniu",
  connectedProviders: "Podłączeni dostawcy",
  disconnect: "Rozłącz",
  connect: "Połącz",
  customProvider: "Własny dostawca",
  searchModels: "Szukaj modeli...",
  loadingModels: "Ładowanie modeli...",
  noModels: "Podłącz co najmniej jednego dostawcę, aby zobaczyć listę modeli.",
  editProvider: "Edytuj dostawcę",
  customProviderTitle: "Własny dostawca",
  name: "Nazwa",
  hideKey: "Ukryj klucz",
  showKey: "Pokaż klucz",
  save: "Zapisz",
  newSession: "Nowa sesja",
  prevSession: "Poprzednia sesja",
  nextSession: "Następna sesja",
  openTerminal: "Otwórz terminal",
  searchPlaceholder: "Szukaj poleceń, plików...",
  searchIn: "Szukaj w {folder}",
  menu: "Menu",
  hideSessions: "Ukryj sesje",
  showSessions: "Pokaż sesje",
  newSessionTitle: "Nowa sesja",
  prevSessionTitle: "Poprzednia sesja",
  nextSessionTitle: "Następna sesja",
  toggleTerminal: "Przełącz terminal",
  toggleSessions: "Przełącz sesje",
  hideFileTree: "Ukryj drzewo plików",
  showFileTree: "Pokaż drzewo plików",
  toggleFileTree: "Przełącz drzewo plików",
  close: "Zamknij",
  minimizeLabel: "Minimalizuj",
  maximizeLabel: "Maksymalizuj",
  closeLabel: "Zamknij",
  welcomeSubtitle: "Brak otwartego projektu. Wybierz folder, aby rozpocząć sesję.",
  openProject: "Otwórz projekt",
  fatalErrorTitle: "Nie można uruchomić vibe",
  fatalErrorHint: "Ustaw VIBE_API_KEY w .env obok vibe, w ~/.vibe/config lub jako zmienną środowiskową.",
  loadingText: "Openvibe się ładuje…",
  noSessions: "Brak sesji",
  untitled: "Bez tytułu",
  deleteSession: "Usuń sesję",
  selectModel: "Wybierz model:",
  revertToMessage: "Wróć do tej wiadomości",
  copy: "Kopiuj",
  completed: "Zakończono",
  diff: "Różnice",
  regenerate: "Regeneruj",
  reading: "Czytanie",
  read: "Przeczytano",
  failedWrite: "Błąd zapisu",
  writing: "Pisanie",
  written: "Utworzono",
  failedEdit: "Błąd edycji",
  editing: "Edycja",
  edited: "Edytowano",
  listing: "Listowanie",
  listed: "Wylistowano",
  searchingCodebase: "Szukanie w kodzie",
  searchedCodebase: "Search in codebase",
  running: "Uruchamianie",
  ran: "Uruchomiono",
  tool: "Narzędzie",
  newFile: "Nowy plik",
  newFolder: "Nowy folder",
  rename: "Zmień nazwę",
  cut: "Wytnij",
  paste: "Wklej",
  delete: "Usuń",
  deleteConfirm: "Usunąć {name}?",
  createFailed: "Błąd tworzenia: {error}",
  renameFailed: "Błąd zmiany nazwy: {error}",
  newFileTooltip: "Nowy plik",
  newFolderTooltip: "Nowy folder",
  refreshTooltip: "Odśwież",
  collapseAllTooltip: "Zwiń wszystko",
  loading: "ładowanie…",
  closeProject: "Zamknij projekt",
  openProjectMenuItem: "Otwórz projekt",
  revealExplorer: "Pokaż w eksploratorze",
  removeFromList: "Usuń z listy",
  openFolder: "Otwórz folder",
  settings: "Ustawienia",
  stop: "Zatrzymaj",
  runCommand: "Wykonaj polecenie",
  sendMessage: "Wyślij wiadomość",
  dropFilesAttach: "Przeciągnij pliki, aby je dołączyć",
  remove: "Usuń",
  attachFiles: "Dołącz pliki",
  cancel: "Anuluj",
  processing: "Przetwarzanie...",
  vibeAnything: "Napisz coś...",
  selectModelFallback: "Wybierz model",
  searchModelPlaceholder: "Szukaj modeli...",
  addProvider: "Dodaj dostawcę",
  configureModels: "Konfiguruj modele",
  noModelsFound: "Nie znaleziono modeli",
  noModelsEnabled: "Brak włączonych modeli",
  searching: "szukanie…",
  noMatches: "brak wyników",
  terminal: "Terminal",
  search: "Szukaj",
  terminalTab: "Terminal {num}",
  closeTab: "Zamknij kartę",
  newTerminal: "Nowy terminal",
  shellExited: "[powłoka zakończona kodem {code}]",
  cannotOpenFile: "Nie można otworzyć pliku",
  retry: "Ponów",
  openFileFromTree: "Otwórz plik z drzewa plików",
  unsavedChanges: "Niezapisane zmiany",
  closeFile: "Zamknij {filename}",
  filePath: "Ścieżka pliku",
  selectFileToEdit: "Wybierz plik do edycji",
  copyCode: "Kopiuj",
  openSettingsHotkey: "Otwórz ustawienia",
  clearChatHotkey: "Wyczyść czat",
  manuallyStopped: "Zatrzymane przez użytkownika",

  // MCP
  edit: "Edytuj",
  mcpServers: "Serwery MCP",
  mcpServersCount: "Serwery MCP ({count})",
  mcpRefreshStatuses: "Odśwież statusy",
  mcpNoServersConfigured: "Brak skonfigurowanych serwerów MCP",
  mcpOpenSettings: "Otwórz ustawienia MCP",
  mcpAddServer: "Dodaj serwer",
  mcpVisualEditor: "Edytor",
  mcpRawConfig: "Surowa konfiguracja",
  mcpExport: "Eksportuj",
  mcpImport: "Importuj",
  mcpSaveTomlConfig: "Zapisz konfig TOML",
  mcpEnableServer: "Włącz serwer",
  mcpDisableServer: "Wyłącz serwer",
  mcpStartServer: "Uruchom serwer",
  mcpStopServer: "Zatrzymaj serwer",
  mcpAddServerTitle: "Dodaj serwer MCP",
  mcpEditServerTitle: "Edytuj serwer MCP",
  mcpServerName: "Nazwa serwera",
  mcpCommandPath: "Polecenie (ścieżka pliku wykonywalnego)",
  mcpCommandPlaceholder: "npx, uvx lub /sciezka/do/pliku",
  mcpArguments: "Argumenty (rozdzielone spacjami)",
  mcpEnvVariables: "Zmienne środowiskowe",
  mcpEnvKeyPlaceholder: "KLUCZ",
  mcpEnvValuePlaceholder: "WARTOŚĆ",
  mcpAddEnvVar: "+ Dodaj zmienną środowiskową",
  mcpEnableOnStartup: "Włącz przy starcie",
  mcpSaveServer: "Zapisz serwer",
  mcpDeleteConfirm: "Czy na pewno chcesz usunąć serwer MCP '{name}'?",
  mcpServerNameRequired: "Nazwa serwera jest wymagana.",
  mcpServerCommandRequired: "Polecenie serwera jest wymagane.",
  mcpServerExists: "Serwer o tej nazwie już istnieje.",
  mcpSaveFailed: "Nie udało się zapisać: {error}",
  mcpInvalidJsonFormat: "Nieprawidłowy format JSON dla konfiguracji MCP",
  mcpFailedParseJson: "Nie udało się przetworzyć zaimportowanego JSON",
  mcpInvalidConfigFormat: "Nieprawidłowy format konfiguracji: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 plik zmieniony",
  commitFileChanged_few: "{count} pliki zmienione",
  commitFileChanged: "{count} plików zmienionych",
  commitInsertion_one: "1 wstawienie(+)",
  commitInsertion_few: "{count} wstawienia(+)",
  commitInsertion: "{count} wstawień(+)",
  commitDeletion_one: "1 usunięcie(-)",
  commitDeletion_few: "{count} usunięcia(-)",
  commitDeletion: "{count} usunięć(-)",
  openCommit: "Otwórz commit",
  copyCommitHash: "Kopiuj hash commita",
  openOnGitHub: "Otwórz na GitHub",
  noFilesChanged: "Brak zmienionych plików",
  inlineGenerating: "Generowanie kodu...",
  inlineEditCode: "Poproś Inline Vibe o edycję kodu...",
  inlineRefineCode: "Poproś Inline Vibe o ponowne doprecyzowanie...",
  inlineSend: "Wyślij (Ctrl+Enter)",
  inlineAccept: "Akceptuj zmiany",
  inlineReject: "Odrzuć",
  inlinePrevDiff: "Poprzednia różnica",
  inlineNextDiff: "Następna różnica",
  videoPlay: "Odtwórz (Space)",
  videoPause: "Pauza (Space)",
  videoMute: "Wycisz (M)",
  videoUnmute: "Włącz dźwięk (M)",
  videoVolume: "Głośność",
  videoPlaybackSpeed: "Prędkość odtwarzania",
  videoFullscreen: "Pełny ekran (F)",
  failedReadFile: "Nie udało się odczytać pliku",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "Kopiuj",
  regenerateMessage: "Regeneruj",

  // Source control
  sourceControl: "Kontrola źródła",
  viewAsFlatList: "Wyświetl jako płaską listę",
  viewsAndMoreActions: "Wyświetlenia i więcej działań...",
  stageAllChanges: "Etap wszystkich zmian",
  checkoutCreateBranch: "Zamówienie/Utwórz oddział...",
  refreshStatus: "Odśwież stan",
  repositories: "Repozytoria",
  commitMessagePlaceholder: "Wiadomość (Ctrl+Enter, aby zatwierdzić w „{branch}”)",
  commitBtn: "Popełniać",
  filterChangesPlaceholder: "Zmiany filtrów (np. *.ts, src/)",
  clearFilter: "Wyczyść filtr",
  noChangesDetected: "Nie wykryto żadnych zmian w repozytorium.",
  stagedChanges: "Zmiany etapowe",
  unstageAll: "Usuń wszystko ze sceny",
  unstageChanges: "Zmiany poza sceną",
  discardChanges: "Odrzuć zmiany",
  stageChanges: "Zmiany etapowe",
  graph: "Wykres",
  noCommitsInGraph: "Brak zatwierdzeń w historii wykresów.",
  newBranchName: "Nowa nazwa oddziału...",
  createBranchBtn: "Tworzyć",
  currentBranch: "(aktualny)",

  // Auto-added translated keys
  renderFileTree: "Piękne drzewo plików",
  renderFileTreeDesc:
    "Renderuj struktury folderów jako piękny komponent interfejsu użytkownika zamiast surowego tekstu",
  apiKeyPlaceholder: "Klucz API",
  customIcon: "Ikona niestandardowa (URL lub przesyłanie)",
  modelsUrl: "Adres URL listy modeli (opcjonalnie)",
  headers: "Nagłówki",
  parameters: "Parametry",
  headerKey: "Nazwa nagłówka",
  headerValue: "Wartość nagłówka",
  paramKey: "Nazwa parametru",
  paramValue: "Wartość parametru",
  uploadIcon: "Prześlij ikonę",
  closeTerminal: "Zamknij terminal",
  hideButton: "Ukrywać",
  showButton: "Pokazywać",
  restoreButtons: "Przywróć przyciski",
  filesChanged: "Zmieniono {count} plików",
  filesChanged_one: "Zmieniono plik {count}",
  filesChanged_few: "Zmieniono {count} plików",
  changes: "Zmiany",
  exploring: "Odkrywanie",
  explored: "Badać",
  editProject: "Redagować",
  editProjectTitle: "Edytuj projekt",
  projectIcon: "Ikona",
  backgroundColor: "Kolor tła",
  closeFromList: "Zamknąć",
  searchInCode: "Szukaj w kodzie",
  searchInCodePlaceholder: "Szukaj",
  replacePlaceholder: "Zastępować",
  refreshSearch: "Odśwież wyszukiwanie",
  clearSearchResults: "Wyczyść wyniki wyszukiwania",
  viewAsTree: "Wyświetl jako drzewo",
  showReplace: "Pokaż Zamień",
  hideReplace: "Ukryj Zamień",
  matchCase: "Sprawa dopasowania",
  matchWholeWord: "Dopasuj całe słowo",
  useRegex: "Użyj wyrażenia regularnego",
  preserveCase: "Zachowaj skrzynkę",
  replaceAll: "Zamień wszystko",
  filesToIncludeExclude: "Pliki do włączenia/wyłączenia",
  filesToInclude: "pliki do dołączenia",
  filesToExclude: "pliki do wykluczenia",
  includePlaceholder: "np. *.ts, src/**",
  excludePlaceholder: "np. moduły_węzłów, *.test.ts",
  noResultsFound: "Nie znaleziono żadnych wyników.",
  searchInCodeResults_one: "{count} skutkuje plikiem {fileCount}",
  searchInCodeResults_few: "{count} daje w wyniku {fileCount} plików",
  searchInCodeResults: "{count} daje w wyniku {fileCount} plików",
  typeToSearch: "Wpisz zapytanie, aby znaleźć pliki według zawartości.",
  loadingMatches: "Załadunek...",
  moreMatches_one: "… i jeszcze {count} dopasowania",
  moreMatches_few: "… i jeszcze {count} dopasowań",
  moreMatches: "… i jeszcze {count} dopasowań",
  newProjectHotkey: "Nowy projekt",
  closeProjectHotkey: "Zamknij projekt",
  closeFileHotkey: "Zamknij plik",
  navigation: "Nawigacja",
  chat: "Pogawędzić",
  workspace: "Obszar roboczy",
  project: "Projekt",
  editor: "Redaktor",
  noHotkeys: "Nie załadowano żadnych skrótów klawiszowych",
  design: "Projekt",
  animations: "Animacje",
  animStyleFade: "Znikać",
  animStyleSlide: "Slajd",
  animStyleScale: "Skala",
  animStyleFadeSlide: "Zanikanie + przesuwanie",
  animStyleNone: "Brak animacji",
  animProjectHover: "Najedź kursorem na projekt",
  animProjectHoverDesc: "Animacja po najechaniu myszką na kafelek projektu",
  animProjectSwitch: "Przełącznik projektu",
  animProjectSwitchDesc: "Przejście podczas otwierania nowego projektu",
  animSidebarSlide: "Pasek boczny",
  animSidebarSlideDesc: "Otwieranie/zamykanie panelu bocznego",
  animContextMenu: "Menu kontekstowe",
  animContextMenuDesc: "Wygląd menu kontekstowego",
  animButtons: "Pikolak",
  animButtonsDesc: "Elementy interaktywne po najechaniu myszką",
  animPanelAppear: "Panele i modały",
  animPanelAppearDesc: "Ustawienia, wyskakujące okienka i wygląd modalny",
  animMultiplier: "Płynność animacji",
  animMultiplierDesc:
    "Mnożnik płynności animacji. 0 = zatrzymany, 0,5 = żwawy, 1 = normalny, 2 = gładki, 5 = bardzo gładki",
  windowEffects: "Efekty okienne",
  blurOverlay: "Rozmycie tła",
  blurOverlayDesc: "Rozmyj zawartość za oknami modalnymi (ustawienia, menu kontekstowe)",
  blurNone: "Nic",
  blurSubtle: "Subtelny",
  blurStrong: "Mocny",
  borderRadius: "Promień granicy",
  borderRadiusDesc: "Zaokrąglanie narożników elementów interfejsu użytkownika",
  uiZoom: "Powiększenie interfejsu",
  zoomStep: "Krok powiększenia",
  zoomStepDesc: "Jak bardzo każde naciśnięcie Ctrl+Plus/Ctrl+Minus zmienia poziom powiększenia",
  zoomDefault: "Domyślne powiększenie",
  zoomDefaultDesc: "Poziom powiększenia po naciśnięciu Ctrl+0",
  terminalShell: "Powłoka terminala",
  appName: "Pulpit OpenVibe",
  appVersion: "v1.3.9",
  shell: "Powłoka",
  langRussian: "rosyjski",
  langEnglish: "angielski",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "ukraiński",
  langBelarusian: "białoruski",
  langSpanish: "hiszpański",
  langItalian: "włoski",
  langPortuguese: "portugalski",
  langJapanese: "japoński",
  langSerbian: "serbski",
  langFrench: "francuski",
  langGerman: "niemiecki",
  langHindi: "hinduski",
  langArabic: "arabski",
  langIndonesian: "indonezyjski",
  langKorean: "koreański",
  langTurkish: "turecki",
  langVietnamese: "wietnamski",
  langPolish: "Polski",
  langDutch: "Holenderski",
  langRomanian: "rumuński",
  langGreek: "grecki",
  langSwedish: "szwedzki",
  langKazakh: "kazachski",
  langAzerbaijani: "azerbejdżański",
  langThai: "tajski",
  langBengali: "bengalski",
  langPunjabi: "Pendżabski",
  langBulgarian: "bułgarski",
  langCzech: "czeski",
  langFilipino: "Filipiński",
  langPersian: "perski",
  langMalay: "malajski",
  langBurmese: "Birmańczyk",
  langAmharic: "amharski",
  langMarathi: "marathi",
  codeTab: "Kod",
  editorFontSize: "Rozmiar czcionki",
  editorFontSizeDesc: "Rozmiar czcionki edytora i terminala",
  editorLineHeight: "Wysokość linii",
  editorLineHeightDesc: "Mnożnik wysokości linii edytora",
  editorLigatures: "Ligatury czcionek",
  editorLigaturesDesc: "Włącz ligatury kodujące (np. =>, ===)",
  editorCursorStyle: "Styl kursora",
  editorCursorStyleDesc: "Kształt kursora edytora",
  editorCursorBlink: "Kursor miga",
  editorCursorBlinkDesc: "Styl animacji kursora",
  cursorLine: "Linia",
  cursorBlock: "Blok",
  cursorUnderline: "Podkreślać",
  cursorLineThin: "Linia cienka",
  cursorBlockOutline: "Zarys bloku",
  cursorUnderlineThin: "Podkreśl Cienki",
  blinkBlink: "Migać",
  blinkSmooth: "Gładki",
  blinkPhase: "Faza",
  blinkExpand: "Zwiększać",
  blinkSolid: "Solidny",
  manageThemes: "Zarządzaj motywami",
  manageThemesDesc: "Importuj lub eksportuj motywy kolorów",
  importTheme: "Import",
  exportTheme: "Eksport",
  borderStyle: "Styl graniczny",
  borderStyleDesc: "Włącz lub wyłącz obramowanie panelu",
  borderStyleBordered: "Graniczy",
  borderStyleBorderless: "Bez granic",
  hideSourceControl: "Ukryj kontrolę źródła",
  showSourceControl: "Pokaż kontrolę źródła",

  // Newly added UI strings
  backBtn: "Z powrotem",
  onboardingStepSettingsTitle: "Ustawienia obszaru roboczego",
  continueBtn: "Kontynuować",
  welcomeThanks: "Skonfigurujmy OpenVibe pod kątem Twojego przepływu pracy.",
  startVibingBtn: "Zakończ konfigurację",
  rerunOnboarding: "Uruchom Kreatora instalacji",
  onboardingStepThemeTitle: "Wybierz motyw",
  letsVibeBtn: "Let's vibe",
  animationSpeed: "Szybkość animacji",
  onboardingStepSettingsDesc: "Ustaw swoje preferencje teraz lub zmień je później.",
  onboardingStepAnimationDesc: "Wybierz style przejść dla elementów interfejsu i dostosuj ich płynność.",
  useRegionalProxy: "Użyj regionalnego serwera proxy (Europa)",
  welcomeGreeting: "Witaj, {name}",
  rerunOnboardingDesc: "Uruchom ponownie początkowy ekran powitalny i kreatora szybkiego wdrożenia",
  useRegionalProxyDesc: "Kieruj żądania API przez szybki serwer proxy w Europie, aby ominąć ograniczenia regionalne",
  onboardingStepThemeDesc: "Przed kontynuowaniem wyświetl podgląd motywu.",
  onboardingStepAnimationTitle: "Konfiguracja animacji",
  animationSpeedDesc: "Przejścia interfejsu i płynne skalowanie efektów",
  // Added by tools/complete_i18n.py
  copyFormatted: "Skopiuj tekst",
  copyRaw: "Skopiuj jako surowy",
  todoTitle: "Zadania",
  todoCount: "{completed} z {count}",
  todoProgress: "Zadania ukończone: {completed} z {count}",
  todoPin: "Przypnij listę zadań",
  todoUnpin: "Odepnij listę zadań",
  todoCreated: "Utworzono plan zadań",
  todoCompleted: "Ukończone zadanie",
  todoBlocked: "Zablokowano w zadaniu",
  activityGroupTodo: "planowanie zadań",
  errorNoticeNetworkTitle: "Nie udało się skontaktować z serwisem",
  errorNoticeQuotaTitle: "Osiągnięto limit dostawcy",
  errorNoticeBlockedTitle: "Dostęp dostawcy jest ograniczony",
  errorNoticeProviderTitle: "Dostawca zwrócił błąd",
  agentRunWorkingFor: "Pracuje {time}",
  agentRunWorkedFor: "Pracował dla {time}",
  agentRunSeconds_one: "{count} sekunda",
  agentRunSeconds_few: "{count} sekund",
  agentRunSeconds: "{count} sekund",
  agentRunMinutesShort: "{count}m",
  agentRunSecondsShort: "{count}s",
  activityProjectStructure: "Badanie struktury projektu",
  activityInspectFolder: "Odkrywanie {name}",
  activityReadFile: "Recenzja {name}",
  activityReadCode: "Przeglądanie kodu",
  activitySearchQuery: "Wyszukiwanie „{query}”",
  activitySearchCode: "Wyszukiwanie odpowiedniej implementacji",
  activityUpdateFile: "Aktualizowanie {name}",
  activityUpdateCode: "Aktualizacja kodu",
  activityRunCommand: "Sprawdzanie projektu",
  activityInvestigateTask: "Badanie zadania",
  activityUseTool: "Uruchomienie {name}",
  gitStatus: "Sprawdzanie stanu",
  gitStatusDone: "Sprawdzony stan",
  gitBranches: "Sprawdzanie oddziałów",
  gitBranchesDone: "Sprawdzone gałęzie",
  gitLog: "Przeglądanie zatwierdzeń",
  gitLogDone: "Sprawdzone zatwierdzenia",
  gitDiff: "Przeglądanie zmian",
  gitDiffDone: "Sprawdzone zmiany",
  gitShow: "Sprawdzanie obiektu Git",
  gitShowDone: "Sprawdzony obiekt Git",
  gitBlame: "Analiza autorstwa linii",
  gitBlameDone: "Analizowane autorstwo linii",
  gitRefs: "Sprawdzanie referencji Git",
  gitRefsDone: "Sprawdzone referencje Git",
  gitInspect: "Sprawdzanie historii Gita",
  gitInspectDone: "Sprawdzona historia Git",
  activityGroupSearch: "szukaj",
  activityGroupRead: "czytanie plików",
  activityGroupEdit: "edytowane pliki",
  activityGroupCommand: "polecenia",
  activityGroupBrowse: "przeglądanie folderów",
  activityGroupAgent: "dochodzenie",
  activityGroupExternal: "narzędzia zewnętrzne",
  activityGroupTools: "działania",
  activityFetchUrl: "Pobieram stronę internetową {url}",
  activityFetchUrlGeneral: "Pobieram stronę internetową",
  activityGitBranches: "Przeglądanie gałęzi Git",
  activityGitCommand: "Operacja Git: {polecenie}",
  activityGitDiff: "Sprawdzanie różnic Git",
  activityGitLog: "Przeglądanie dziennika zatwierdzeń Git",
  activityGitStatus: "Sprawdzanie statusu Gita",
  activityGroupAgentN: "Dochodzenie — zadania: {count}",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "Dochodzenie — zadanie: {count}",
  activityGroupBrowseN: "Przeglądanie folderów: {count}",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "Przeglądanie folderu {count}",
  activityGroupCommandN: "Uruchamianie poleceń: {count}",
  activityGroupCommandN_few: "Выполнение {count} komand",
  activityGroupCommandN_one: "Uruchamiam polecenie {count}",
  activityGroupEditN: "Edytowanie plików: {count}",
  activityGroupEditN_few: "Редактирование {liczba} файлов",
  activityGroupEditN_one: "Edytowanie pliku {count}",
  activityGroupExternalN: "Narzędzia zewnętrzne — {count} połączeń",
  activityGroupExternalN_few: "Внешние instrumenty — {count} вызова",
  activityGroupExternalN_one: "Narzędzie zewnętrzne — połączenie {count}",
  activityGroupGit: "Operacje na Gicie",
  activityGroupGitN: "Git — {count} operacji",
  activityGroupGitN_few: "Git — {count} zastosowań",
  activityGroupGitN_one: "Git — operacja: {count}",
  activityGroupReadN: "Czytanie plików: {count}",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "Czytanie pliku {count}",
  activityGroupSearchN: "Szukaj — {count} zapytań",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "Wyszukaj — zapytanie: {count}",
  activityGroupTodoN: "Planowanie — {count} zadań",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "Planowanie — zadanie: {count}",

  // Agent flow (linear run redesign)
  flowThinking: "Myśli…",
  flowThought: "Proces myślenia",
  flowAnalysis: "Analiza",
  flowCountRead_one: "{count} odczyt",
  flowCountRead_few: "{count} odczyty",
  flowCountRead: "{count} odczytów",
  flowCountSearch_one: "{count} wyszukiwanie",
  flowCountSearch_few: "{count} wyszukiwania",
  flowCountSearch: "{count} wyszukiwań",
  flowCountBrowse_one: "{count} przegląd folderów",
  flowCountBrowse_few: "{count} przeglądy folderów",
  flowCountBrowse: "{count} przeglądów folderów",
  flowCountWeb_one: "{count} wyszukiwanie w sieci",
  flowCountWeb_few: "{count} wyszukiwania w sieci",
  flowCountWeb: "{count} wyszukiwań w sieci",
  flowCountGit_one: "{count} operacja git",
  flowCountGit_few: "{count} operacje git",
  flowCountGit: "{count} operacji git",
  activityGroupToolsN: "Liczba działań: {count}",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "Akcja: {count}",
  activityGroupWeb: "wyszukiwanie w Internecie",
  activityGroupWebN: "Wyszukiwarka internetowa — liczba zapytań: {count}",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "Wyszukiwarka internetowa — zapytanie: {count}",
  activityRepeatedCalls: "Liczba połączeń",
  activityWebSearch: "Wyszukiwanie w Internecie hasła „{query}”",
  activityWebSearchGeneral: "Wyszukiwanie informacji w Internecie",
  addModel: "Dodaj model",
  customModelsLabel: "Modele",
  experimentalExtremeRadius: "Eksperymentalny ekstremalny promień (do 100 pikseli)",
  experimentalExtremeRadiusDesc:
    "Umożliwia ustawienie promienia obramowania interfejsu użytkownika do 100 pikseli. Eksperymentalna flaga!",
  fetchedUrl: "Pobrany adres URL",
  fetchingUrl: "Pobieram adres URL",
  generateCommitMessage: "Wygeneruj wiadomość zatwierdzenia za pomocą AI",
  hideToolCalls: "Ukryj wywołania narzędzi",
  modelDisplayName: "Nazwa wyświetlana",
  modelIdPlaceholder: "identyfikator modelu",
  promptMarkdown: "Markdown w wierszu poleceń",
  promptMarkdownDesc: "Renderuj formatowanie Markdown na żywo podczas wpisywania podpowiedzi",
  promptMarkdownGhost: "Pokaż znaczniki składni (**)",
  promptMarkdownGhostDesc: "Wyświetlaj przyciemnione znaki składniowe (**, `, #) wewnątrz sformatowanego tekstu",
  reasoningEffortHigh: "Wysoki",
  reasoningEffortLow: "Niski",
  reasoningEffortMedium: "Średni",
  reasoningEffortNone: "Nic",
  searchedWeb: "Wyszukiwanie w Internecie",
  searchingWeb: "Wyszukiwanie w sieci",
  showToolCalls: "Pokaż wywołania narzędzi",
  tabStyle: "Styl zakładki",
  tabStyleDefault: "Domyślny",
  tabStyleDesc: "Kwadratowe lub zaokrąglone pigułki dla zakładek edytora",
  tabStylePills: "Pigułki",
};
