import type { Translations } from "./ru";

export const sr: Partial<Translations> = {
  app: "Aplikacija",
  general: "Opšte",
  hotkeys: "Prečice",
  server: "Server",
  providers: "Provajderi",
  models: "Modeli",
  language: "Jezik",
  languageDesc: "Promeni jezik prikaza OpenVibe aplikacije",
  autoAccept: "Automatski prihvati dozvole",
  autoAcceptDesc: "Zahtevi za dozvole biće automatski odobreni",
  terminalShellDesc: "Školjka za ugrađeni terminal",
  showThinking: "Prikaži sažetke razmišljanja",
  showThinkingDesc: "Prikaži proces razmišljanja modela",
  theme: "Tema",
  themeDesc: "Izaberite temu aplikacije",
  colorScheme: "Šema boja",
  colorSchemeDesc: "Svetla, tamna ili sistemska",
  dark: "Tamna",
  light: "Svetla",
  system: "Sistemska",
  font: "Font",
  fontDesc: "Glavni font interfejsa",
  systemFont: "Sistemski",
  codeFont: "Font za kod",
  codeFontDesc: "Monoširani font za editor i terminal",
  soundNotifications: "Zvučna obaveštenja",
  soundEnabled: "Uključi zvuke",
  soundEnabledDesc: "Reprodukuj zvučna obaveštenja",
  soundOnComplete: "Zadatak završen",
  soundOnCompleteDesc: "Zvuk pri uspešnom završetku",
  soundOnStop: "Zaustavljanje zadatka",
  soundOnStopDesc: "Zvuk pri prinudnom zaustavljanju",
  connectedProviders: "Povezani provajderi",
  disconnect: "Isključi",
  connect: "Poveži",
  customProvider: "Prilagođeni provajder",
  searchModels: "Pretraži modele...",
  loadingModels: "Učitavanje modela...",
  noModels: "Povežite bar jednog provajdera da vidite listu modela.",
  editProvider: "Uredi provajdera",
  customProviderTitle: "Prilagođeni provajder",
  name: "Naziv",
  hideKey: "Sakrij ključ",
  showKey: "Prikaži ključ",
  save: "Sačuvaj",
  newSession: "Nova sesija",
  prevSession: "Prethodna sesija",
  nextSession: "Sledeća sesija",
  openTerminal: "Otvori terminal",
  searchPlaceholder: "Pretraži komande, datoteke...",
  searchIn: "Pretraži u {folder}",
  menu: "Meni",
  hideSessions: "Sakrij sesije",
  showSessions: "Prikaži sesije",
  newSessionTitle: "Nova sesija",
  prevSessionTitle: "Prethodna sesija",
  nextSessionTitle: "Sledeća sesija",
  toggleTerminal: "Uključi/isključi terminal",
  toggleSessions: "Uključi/isključi sesije",
  hideFileTree: "Sakrij stablo datoteka",
  showFileTree: "Prikaži stablo datoteka",
  toggleFileTree: "Uključi/isključi stablo datoteka",
  close: "Zatvori",
  minimizeLabel: "Minimizuj",
  maximizeLabel: "Maksimizuj",
  closeLabel: "Zatvori",
  welcomeSubtitle: "Nema otvorenog projekta. Izaberite fasciklu da započnete sesiju.",
  openProject: "Otvori projekat",
  fatalErrorTitle: "Pokretanje vibea nije uspelo",
  fatalErrorHint: "Postavite VIBE_API_KEY u .env pored vibea, u ~/.vibe/config ili kao promenljivu okruženja.",
  loadingText: "Openvibe se učitava…",
  noSessions: "Još uvek nema sesija",
  untitled: "Bez naziva",
  deleteSession: "Obriši sesiju",
  selectModel: "Izaberite model:",
  revertToMessage: "Vrati se na ovu poruku",
  copy: "Kopiraj",
  completed: "Završeno",
  diff: "Razlike",
  regenerate: "Regeneriši",
  reading: "Čitanje",
  read: "Pročitano",
  failedWrite: "Greška pri pisanju",
  writing: "Pisanje",
  written: "Kreirano",
  failedEdit: "Greška pri uređivanju",
  editing: "Uređivanje",
  edited: "Uređeno",
  listing: "Pregledanje",
  listed: "Pregledano",
  searchingCodebase: "Pretraga koda",
  searchedCodebase: "Search in codebase",
  running: "Izvršavanje",
  ran: "Izvršeno",
  tool: "Alat",
  newFile: "Nova datoteka",
  newFolder: "Nova fascikla",
  rename: "Preimenuj",
  cut: "Iseci",
  paste: "Nalepi",
  delete: "Obriši",
  deleteConfirm: "Obriši {name}?",
  createFailed: "Greška pri kreiranju: {error}",
  renameFailed: "Greška pri preimenovanju: {error}",
  newFileTooltip: "Nova datoteka",
  newFolderTooltip: "Nova fascikla",
  refreshTooltip: "Osveži",
  collapseAllTooltip: "Skupi sve",
  loading: "učitavanje…",
  closeProject: "Zatvori projekat",
  openProjectMenuItem: "Otvori projekat",
  revealExplorer: "Prikaži u istraživaču",
  removeFromList: "Ukloni sa liste",
  openFolder: "Otvori fasciklu",
  settings: "Podešavanja",
  stop: "Zaustavi",
  runCommand: "Pokreni komandu",
  sendMessage: "Pošalji poruku",
  dropFilesAttach: "Prevucite datoteke za prilaganje",
  remove: "Ukloni",
  attachFiles: "Priloži datoteke",
  cancel: "Otkaži",
  processing: "Obrada...",
  vibeAnything: "Napišite nešto...",
  selectModelFallback: "Izaberite model",
  searchModelPlaceholder: "Pretraži modele...",
  addProvider: "Dodaj provajdera",
  configureModels: "Podesi modele",
  noModelsFound: "Modeli nisu pronađeni",
  noModelsEnabled: "Nema uključenih modela",
  searching: "pretraga…",
  noMatches: "ništa nije pronađeno",
  terminal: "Terminal",
  search: "Претрага",
  terminalTab: "Terminal {num}",
  closeTab: "Zatvori karticu",
  newTerminal: "Novi terminal",
  shellExited: "[školjka je završena sa kodom {code}]",
  cannotOpenFile: "Ne može se otvoriti datoteka",
  retry: "Pokušaj ponovo",
  openFileFromTree: "Otvorite datoteku iz stabla datoteka",
  unsavedChanges: "Nesačuvane izmene",
  closeFile: "Zatvori {filename}",
  filePath: "Putanja do datoteke",
  selectFileToEdit: "Izaberite datoteku za uređivanje",
  copyCode: "Kopiraj",
  openSettingsHotkey: "Otvori podešavanja",
  clearChatHotkey: "Očisti čet",
  manuallyStopped: "Заустављено од стране корисника",

  // MCP
  edit: "Уреди",
  mcpServers: "MCP сервери",
  mcpServersCount: "MCP сервери ({count})",
  mcpRefreshStatuses: "Освежи статусе",
  mcpNoServersConfigured: "Нема подешених MCP сервера",
  mcpOpenSettings: "Отвори MCP подешавања",
  mcpAddServer: "Додај сервер",
  mcpVisualEditor: "Уредник",
  mcpRawConfig: "RAW конфигурација",
  mcpExport: "Извези",
  mcpImport: "Увези",
  mcpSaveTomlConfig: "Сачувај TOML конфигурацију",
  mcpEnableServer: "Омогући сервер",
  mcpDisableServer: "Онемогући сервер",
  mcpStartServer: "Покрени сервер",
  mcpStopServer: "Заустави сервер",
  mcpAddServerTitle: "Додај MCP сервер",
  mcpEditServerTitle: "Уреди MCP сервер",
  mcpServerName: "Назив сервера",
  mcpCommandPath: "Команда (путања до извршног фајла)",
  mcpCommandPlaceholder: "npx, uvx или /путања/до/бинарног",
  mcpArguments: "Аргументи (раздвојени размаком)",
  mcpEnvVariables: "Променљиве окружења",
  mcpEnvKeyPlaceholder: "КЉУЧ",
  mcpEnvValuePlaceholder: "ВРЕДНОСТ",
  mcpAddEnvVar: "+ Додај променљиву окружења",
  mcpEnableOnStartup: "Омогући при покретању",
  mcpSaveServer: "Сачувај сервер",
  mcpDeleteConfirm: "Да ли сте сигурни да желите да избришете MCP сервер '{name}'?",
  mcpServerNameRequired: "Назив сервера је обавезан.",
  mcpServerCommandRequired: "Команда сервера је обавезна.",
  mcpServerExists: "Сервер са овим називом већ постоји.",
  mcpSaveFailed: "Неуспешно чување: {error}",
  mcpInvalidJsonFormat: "Неважећи JSON формат за MCP конфигурацију",
  mcpFailedParseJson: "Неуспешно рашчлањивање увезеног JSON-а",
  mcpInvalidConfigFormat: "Неважећи формат конфигурације: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 fajl izmenjen",
  commitFileChanged_few: "{count} fajla izmenjena",
  commitFileChanged: "{count} fajlova izmenjeno",
  commitInsertion_one: "1 umetanje(+)",
  commitInsertion_few: "{count} umetanja(+)",
  commitInsertion: "{count} umetanja(+)",
  commitDeletion_one: "1 brisanje(-)",
  commitDeletion_few: "{count} brisanja(-)",
  commitDeletion: "{count} brisanja(-)",
  openCommit: "Otvori commit",
  copyCommitHash: "Kopiraj hash commita",
  openOnGitHub: "Otvori na GitHub-u",
  noFilesChanged: "Nema izmenjenih fajlova",
  inlineGenerating: "Generisanje koda...",
  inlineEditCode: "Zamolite Inline Vibe da uredi kod...",
  inlineRefineCode: "Zamolite Inline Vibe da ponovo precizira...",
  inlineSend: "Pošalji (Ctrl+Enter)",
  inlineAccept: "Prihvati izmene",
  inlineReject: "Odbaci",
  inlinePrevDiff: "Prethodna razlika",
  inlineNextDiff: "Sledeća razlika",
  videoPlay: "Pusti (Space)",
  videoPause: "Pauziraj (Space)",
  videoMute: "Utišaj (M)",
  videoUnmute: "Uključi zvuk (M)",
  videoVolume: "Jačina zvuka",
  videoPlaybackSpeed: "Brzina reprodukcije",
  videoFullscreen: "Ceo ekran (F)",
  failedReadFile: "Čitanje fajla neuspešno",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "Kopiraj",
  regenerateMessage: "Regeneriši",

  // Source control
  sourceControl: "Контрола извора",
  viewAsFlatList: "Прикажи као равну листу",
  viewsAndMoreActions: "Прегледи и више радњи...",
  stageAllChanges: "Сцена Све промене",
  checkoutCreateBranch: "Плаћање / Креирање филијале...",
  refreshStatus: "Освежи статус",
  repositories: "Спремишта",
  commitMessagePlaceholder: "Порука (Цтрл+Ентер за урезивање на '{бранцх}')",
  commitBtn: "Цоммит",
  filterChangesPlaceholder: "Промене филтера (нпр. *.тс, срц/)",
  clearFilter: "Обриши филтер",
  noChangesDetected: "У спремишту нису откривене промене.",
  stagedChanges: "Постепене промене",
  unstageAll: "Унстаге Алл",
  unstageChanges: "Унстаге Цхангес",
  discardChanges: "Одбаци промене",
  stageChanges: "Стаге Цхангес",
  graph: "Граф",
  noCommitsInGraph: "Нема урезивања у историји графикона.",
  newBranchName: "Ново име филијале...",
  createBranchBtn: "Креирај",
  currentBranch: "(тренутни)",

  // Auto-added translated keys
  renderFileTree: "Прелепо стабло датотека",
  renderFileTreeDesc:
    "Рендерирајте структуре фасцикли као прелепу компоненту корисничког интерфејса уместо сировог текста",
  apiKeyPlaceholder: "АПИ кључ",
  customIcon: "Прилагођена икона (УРЛ или отпремање)",
  modelsUrl: "УРЛ листе модела (опционално)",
  headers: "Заглавља",
  parameters: "Параметерс",
  headerKey: "Име заглавља",
  headerValue: "Вредност заглавља",
  paramKey: "Назив параметра",
  paramValue: "Вредност параметра",
  uploadIcon: "Икона за отпремање",
  closeTerminal: "Затворите терминал",
  hideButton: "Сакриј се",
  showButton: "Схов",
  restoreButtons: "Дугмад за враћање",
  filesChanged: "Промењених датотека: {цоунт}",
  filesChanged_one: "{цоунт} датотека је промењена",
  filesChanged_few: "Промењених датотека: {цоунт}",
  changes: "Промене",
  exploring: "Истражујући",
  explored: "Истражите",
  editProject: "Уреди",
  editProjectTitle: "Уреди пројекат",
  projectIcon: "Икона",
  backgroundColor: "Боја позадине",
  closeFromList: "Затвори",
  searchInCode: "Тражи у коду",
  searchInCodePlaceholder: "Тражи",
  replacePlaceholder: "Замените",
  refreshSearch: "Освежите претрагу",
  clearSearchResults: "Обриши резултате претраге",
  viewAsTree: "Прикажи као дрво",
  showReplace: "Прикажи Замени",
  hideReplace: "Сакриј Замени",
  matchCase: "Матцх Цасе",
  matchWholeWord: "Ускладите целу реч",
  useRegex: "Користите регуларни израз",
  preserveCase: "Пресерве Цасе",
  replaceAll: "Замени све",
  filesToIncludeExclude: "Датотеке за укључивање/искључивање",
  filesToInclude: "датотеке које треба укључити",
  filesToExclude: "датотеке које треба искључити",
  includePlaceholder: "нпр. *.тс, срц/**",
  excludePlaceholder: "нпр. ноде_модулес, *.тест.тс",
  noResultsFound: "Нема пронађених резултата.",
  searchInCodeResults_one: "{цоунт} резултат у {филеЦоунт} датотеци",
  searchInCodeResults_few: "{цоунт} резултата у {филеЦоунт} датотекама",
  searchInCodeResults: "{цоунт} резултата у {филеЦоунт} датотекама",
  typeToSearch: "Унесите упит за претрагу да бисте пронашли датотеке по садржају.",
  loadingMatches: "Учитавање...",
  moreMatches_one: "… и још {цоунт} подударања",
  moreMatches_few: "… и још {цоунт} подударања",
  moreMatches: "… и још {цоунт} подударања",
  newProjectHotkey: "Нови пројекат",
  closeProjectHotkey: "Затвори пројекат",
  closeFileHotkey: "Затворите датотеку",
  navigation: "Навигација",
  chat: "Ћаскање",
  workspace: "Радни простор",
  project: "Пројекат",
  editor: "Уредник",
  noHotkeys: "Нема учитаних интервентних тастера",
  design: "Дизајн",
  animations: "Анимације",
  animStyleFade: "Фаде",
  animStyleSlide: "Слајд",
  animStyleScale: "Скала",
  animStyleFadeSlide: "Фаде + Слиде",
  animStyleNone: "Нема анимација",
  animProjectHover: "Пројецт ховер",
  animProjectHoverDesc: "Анимација када пређете мишем преко плочице пројекта",
  animProjectSwitch: "Пројецт свитцх",
  animProjectSwitchDesc: "Транзиција приликом отварања новог пројекта",
  animSidebarSlide: "Бочна трака",
  animSidebarSlideDesc: "Отварање/затварање бочне плоче",
  animContextMenu: "Контекстни мени",
  animContextMenuDesc: "Изглед контекстног менија",
  animButtons: "Дугмад",
  animButtonsDesc: "Интерактивни елементи при лебдењу",
  animPanelAppear: "Панели и модали",
  animPanelAppearDesc: "Подешавања, искачући прозори и модални изглед",
  animMultiplier: "Глаткост анимације",
  animMultiplierDesc:
    "Множилац глаткоће анимације. 0 = заустављено, 0,5 = брзо, 1 = нормално, 2 = глатко, 5 = ултра глатко",
  windowEffects: "Виндов Еффецтс",
  blurOverlay: "Замућење позадине",
  blurOverlayDesc: "Замаглите садржај иза модалних прозора (подешавања, контекстни менији)",
  blurNone: "Ниједан",
  blurSubtle: "Суптилно",
  blurStrong: "Јака",
  borderRadius: "Гранични радијус",
  borderRadiusDesc: "Заокруживање углова за елементе корисничког интерфејса",
  uiZoom: "УИ Зоом",
  zoomStep: "Корак зумирања",
  zoomStepDesc: "Колико сваки притисак Цтрл+Плус/Цтрл+Минус мења ниво зумирања",
  zoomDefault: "Подразумевани зум",
  zoomDefaultDesc: "Ниво зумирања када притиснете Цтрл+0",
  terminalShell: "Терминал Схелл",
  appName: "ОпенВибе Десктоп",
  appVersion: "в1.3.9",
  shell: "Схелл",
  langRussian: "руски",
  langEnglish: "енглески",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "украјински",
  langBelarusian: "белоруски",
  langSpanish: "шпански",
  langItalian: "италијански",
  langPortuguese: "португалски",
  langJapanese: "јапански",
  langSerbian: "српски",
  langFrench: "француски",
  langGerman: "немачки",
  langHindi: "Хинди",
  langArabic: "арапски",
  langIndonesian: "индонезијски",
  langKorean: "Кореан",
  langTurkish: "турски",
  langVietnamese: "вијетнамски",
  langPolish: "пољски",
  langDutch: "холандски",
  langRomanian: "румунски",
  langGreek: "грчки",
  langSwedish: "шведски",
  langKazakh: "казахстански",
  langAzerbaijani: "азербејџански",
  langThai: "тајландски",
  langBengali: "бенгалски",
  langPunjabi: "панџапски",
  langBulgarian: "бугарски",
  langCzech: "чешки",
  langFilipino: "филипински",
  langPersian: "персијски",
  langMalay: "малајски",
  langBurmese: "бурмански",
  langAmharic: "амхарски",
  langMarathi: "Маратхи",
  codeTab: "Код",
  editorFontSize: "Величина фонта",
  editorFontSizeDesc: "Едитор и величина фонта терминала",
  editorLineHeight: "Висина линије",
  editorLineHeightDesc: "Множилац висине реда уређивача",
  editorLigatures: "Фонт Лигатурес",
  editorLigaturesDesc: "Омогући лигатуре кодирања (нпр. =>, ===)",
  editorCursorStyle: "Цурсор Стиле",
  editorCursorStyleDesc: "Облик курсора уређивача",
  editorCursorBlink: "Курсор трепери",
  editorCursorBlinkDesc: "Стил анимације курсора",
  cursorLine: "Линија",
  cursorBlock: "Блокирај",
  cursorUnderline: "Подвуци",
  cursorLineThin: "Лине Тхин",
  cursorBlockOutline: "Блоцк Оутлине",
  cursorUnderlineThin: "Ундерлине Тхин",
  blinkBlink: "Блинк",
  blinkSmooth: "Смоотх",
  blinkPhase: "Фаза",
  blinkExpand: "Прошири",
  blinkSolid: "Чврсто",
  manageThemes: "Управљајте темама",
  manageThemesDesc: "Увезите или извезите своје теме боја",
  importTheme: "Увоз",
  exportTheme: "Извоз",
  borderStyle: "Бордер Стиле",
  borderStyleDesc: "Укључите или искључите ивице панела",
  borderStyleBordered: "Бордеред",
  borderStyleBorderless: "Бордерлесс",
  hideSourceControl: "Сакриј контролу извора",
  showSourceControl: "Прикажи контролу извора",

  // Newly added UI strings
  backBtn: "Назад",
  onboardingStepSettingsTitle: "Подешавања радног простора",
  continueBtn: "Настави",
  welcomeThanks: "Хајде да подесимо ОпенВибе за ваш радни ток.",
  startVibingBtn: "Завршите подешавање",
  rerunOnboarding: "Покрените чаробњак за подешавање",
  onboardingStepThemeTitle: "Изаберите тему",
  letsVibeBtn: "Let's vibe",
  animationSpeed: "Брзина анимације",
  onboardingStepSettingsDesc: "Подесите своја подешавања сада или их промените касније.",
  onboardingStepAnimationDesc: "Изаберите стилове прелаза за елементе интерфејса и прилагодите њихову глаткоћу.",
  useRegionalProxy: "Користи регионални прокси (Европа)",
  welcomeGreeting: "Здраво, {name}",
  rerunOnboardingDesc: "Поново покрените почетни екран добродошлице и чаробњак за брзо укључивање",
  useRegionalProxyDesc:
    "Усмерите АПИ захтеве преко брзог прокси сервера у Европи да бисте заобишли регионална ограничења",
  onboardingStepThemeDesc: "Прегледајте тему пре него што наставите.",
  onboardingStepAnimationTitle: "Подешавање анимације",
  animationSpeedDesc: "Прелази на интерфејсу и глатко скалирање ефеката",
  // Added by tools/complete_i18n.py
  copyFormatted: "Копирај текст",
  copyRaw: "Копирај као сирово",
  todoTitle: "Задаци",
  todoCount: "{completed} од {count}",
  todoProgress: "Завршени задаци: {completed} од {count}",
  todoPin: "Закачите листу задатака",
  todoUnpin: "Откачите листу задатака",
  todoCreated: "Направљен план задатака",
  todoCompleted: "Завршен задатак",
  todoBlocked: "Блокирано на задатку",
  activityGroupTodo: "планирање задатака",
  errorNoticeNetworkTitle: "Није могуће доћи до услуге",
  errorNoticeQuotaTitle: "Достигнуто је ограничење добављача",
  errorNoticeBlockedTitle: "Приступ провајдеру је ограничен",
  errorNoticeProviderTitle: "Провајдер је вратио грешку",
  agentRunWorkingFor: "Ради {time}",
  agentRunWorkedFor: "Радио за {time}",
  agentRunSeconds_one: "{count} секунда",
  agentRunSeconds_few: "{count} секунди",
  agentRunSeconds: "{count} секунди",
  agentRunMinutesShort: "{count}м",
  agentRunSecondsShort: "{count}с",
  activityProjectStructure: "Истраживање структуре пројекта",
  activityInspectFolder: "Истраживање {name}",
  activityReadFile: "Прегледам {name}",
  activityReadCode: "Прегледање кода",
  activitySearchQuery: "Тражи се „{query}“",
  activitySearchCode: "Трагање за релевантном имплементацијом",
  activityUpdateFile: "Ажурирање {name}",
  activityUpdateCode: "Ажурирање кода",
  activityRunCommand: "Провера пројекта",
  activityInvestigateTask: "Истражујући задатак",
  activityUseTool: "Трчање {name}",
  gitStatus: "Инспекција статуса",
  gitStatusDone: "Проверен статус",
  gitBranches: "Прегледање грана",
  gitBranchesDone: "Прегледане гране",
  gitLog: "Прегледање обавеза",
  gitLogDone: "Прегледане обавезе",
  gitDiff: "Преглед промена",
  gitDiffDone: "Прегледао измене",
  gitShow: "Преглед Гит објекта",
  gitShowDone: "Прегледани Гит објекат",
  gitBlame: "Анализирање ауторства линије",
  gitBlameDone: "Анализирано ауторство линије",
  gitRefs: "Провера Гит реф",
  gitRefsDone: "Прегледане Гит референце",
  gitInspect: "Преглед историје Гита",
  gitInspectDone: "Прегледана историја Гита",
  activityGroupSearch: "тражи",
  activityGroupRead: "читање датотека",
  activityGroupEdit: "уређиваних датотека",
  activityGroupCommand: "команде",
  activityGroupBrowse: "прегледавање фолдера",
  activityGroupAgent: "истраге",
  activityGroupExternal: "спољни алати",
  activityGroupTools: "радње",
  activityFetchUrl: "Преузимање веб странице {урл}",
  activityFetchUrlGeneral: "Преузимање веб странице",
  activityGitBranches: "Прегледање Гит грана",
  activityGitCommand: "Гит операција: {цомманд}",
  activityGitDiff: "Провера Гит дифф",
  activityGitLog: "Прегледање дневника Гит урезивања",
  activityGitStatus: "Провера Гит статуса",
  activityGroupAgentN: "Истрага — {цоунт} задатака",
  activityGroupAgentN_few: "Исследование — {цоунт} задачи",
  activityGroupAgentN_one: "Истрага — {цоунт} задатак",
  activityGroupBrowseN: "Прегледам {цоунт} директоријума",
  activityGroupBrowseN_few: "Просмотр {цоунт} папок",
  activityGroupBrowseN_one: "Прегледам фолдер {цоунт}",
  activityGroupCommandN: "Покретање {цоунт} команди",
  activityGroupCommandN_few: "Виполнение {цоунт} команд",
  activityGroupCommandN_one: "Покретање наредбе {цоунт}",
  activityGroupEditN: "Уређивање {цоунт} датотека",
  activityGroupEditN_few: "Редактирование {цоунт} фајлов",
  activityGroupEditN_one: "Уређивање {цоунт} датотеке",
  activityGroupExternalN: "Спољне алатке — {цоунт} позива",
  activityGroupExternalN_few: "Внешние инструменти — {цоунт} визова",
  activityGroupExternalN_one: "Екстерни алат — {цоунт} позив",
  activityGroupGit: "Гит операције",
  activityGroupGitN: "Гит — {цоунт} операције",
  activityGroupGitN_few: "Гит — {цоунт} операции",
  activityGroupGitN_one: "Гит — операција {цоунт}",
  activityGroupReadN: "Читање {цоунт} датотека",
  activityGroupReadN_few: "Чтение {цоунт} фајлов",
  activityGroupReadN_one: "Читање {цоунт} датотеке",
  activityGroupSearchN: "Претрага — {цоунт} упита",
  activityGroupSearchN_few: "Поиск — {цоунт} запрос",
  activityGroupSearchN_one: "Претрага — {цоунт} упит",
  activityGroupTodoN: "Планирање — {цоунт} задатака",
  activityGroupTodoN_few: "Планирование — {цоунт} задачи",
  activityGroupTodoN_one: "Планирање — {цоунт} задатак",

  // Agent flow (linear run redesign)
  flowThinking: "Razmišlja…",
  flowThought: "Tok razmišljanja",
  flowAnalysis: "Analiza",
  flowCountRead_one: "{count} čitanje",
  flowCountRead_few: "{count} čitanja",
  flowCountRead: "{count} čitanja",
  flowCountSearch_one: "{count} pretraga",
  flowCountSearch_few: "{count} pretrage",
  flowCountSearch: "{count} pretraga",
  flowCountBrowse_one: "{count} pregled fascikle",
  flowCountBrowse_few: "{count} pregleda fascikli",
  flowCountBrowse: "{count} pregleda fascikli",
  flowCountWeb_one: "{count} veb pretraga",
  flowCountWeb_few: "{count} veb pretrage",
  flowCountWeb: "{count} veb pretraga",
  flowCountGit_one: "{count} git operacija",
  flowCountGit_few: "{count} git operacije",
  flowCountGit: "{count} git operacija",
  activityGroupToolsN: "{цоунт} радњи",
  activityGroupToolsN_few: "{цоунт} дејстава",
  activityGroupToolsN_one: "{цоунт} радња",
  activityGroupWeb: "веб претрага",
  activityGroupWebN: "Веб претрага — {цоунт} упита",
  activityGroupWebN_few: "Веб-поиск — {цоунт} запрос",
  activityGroupWebN_one: "Веб претрага — {цоунт} упит",
  activityRepeatedCalls: "{цоунт} позива",
  activityWebSearch: "Претраживање веба за „{куери}“",
  activityWebSearchGeneral: "Тражење информација на вебу",
  addModel: "Додајте модел",
  customModelsLabel: "Модели",
  experimentalExtremeRadius: "Експериментални екстремни радијус (до 100 пиксела)",
  experimentalExtremeRadiusDesc:
    "Омогућава подешавање радијуса границе корисничког интерфејса до 100 пиксела. Експериментална застава!",
  fetchedUrl: "Преузета УРЛ адреса",
  fetchingUrl: "Преузимање УРЛ-а",
  generateCommitMessage: "Генеришите поруку за урезивање помоћу АИ",
  hideToolCalls: "Сакриј позиве алата",
  modelDisplayName: "Име за приказ",
  modelIdPlaceholder: "модел-ид",
  promptMarkdown: "Маркдовн у Промпт Инпут",
  promptMarkdownDesc: "Рендер Маркдовн форматирање уживо док куцате упите",
  promptMarkdownGhost: "Прикажи ознаке синтаксе (**)",
  promptMarkdownGhostDesc: "Приказ затамњених знакова синтаксе (**, `, #) унутар форматираног текста",
  reasoningEffortHigh: "Високо",
  reasoningEffortLow: "Ниско",
  reasoningEffortMedium: "Средње",
  reasoningEffortNone: "Ниједан",
  searchedWeb: "Веб претрага",
  searchingWeb: "Сеарцхинг веб",
  showToolCalls: "Прикажи позиве алата",
  tabStyle: "Стил картице",
  tabStyleDefault: "Подразумевано",
  tabStyleDesc: "Квадратне или заобљене таблете за картице уредника",
  tabStylePills: "пилуле",
};
