import type { Translations } from "./ru";

export const tr: Partial<Translations> = {
  app: "Uygulama",
  general: "Genel",
  hotkeys: "Kısayol Tuşları",
  server: "Sunucu",
  providers: "Sağlayıcılar",
  models: "Modeller",
  language: "Dil",
  languageDesc: "OpenVibe görüntüleme dilini değiştir",
  autoAccept: "İzinleri otomatik kabul et",
  autoAcceptDesc: "İzin talepleri otomatik olarak onaylanacak",
  terminalShellDesc: "Yerleşik terminal için kabuk",
  showThinking: "Düşünce özetlerini göster",
  showThinkingDesc: "Modelin düşünme sürecini göster",
  theme: "Tema",
  themeDesc: "Uygulama temasını seçin",
  colorScheme: "Renk şeması",
  colorSchemeDesc: "Açık, koyu veya sistem",
  dark: "Koyu",
  light: "Açık",
  system: "Sistem",
  font: "Yazı tipi",
  fontDesc: "Ana arayüz yazı tipi",
  systemFont: "Sistem",
  codeFont: "Kod yazı tipi",
  codeFontDesc: "Editör ve terminal için tek aralıklı yazı tipi",
  soundNotifications: "Ses bildirimleri",
  soundEnabled: "Sesleri etkinleştir",
  soundEnabledDesc: "Ses bildirimlerini oynat",
  soundOnComplete: "Görev tamamlandı",
  soundOnCompleteDesc: "Başarılı tamamlanmada ses",
  soundOnStop: "Görevi durdur",
  soundOnStopDesc: "Zorla durdurmada ses",
  connectedProviders: "Bağlı sağlayıcılar",
  disconnect: "Bağlantıyı kes",
  connect: "Bağlan",
  customProvider: "Özel sağlayıcı",
  searchModels: "Modelleri ara...",
  loadingModels: "Modeller yükleniyor...",
  noModels: "Model listesini görmek için en az bir sağlayıcı bağlayın.",
  editProvider: "Sağlayıcıyı düzenle",
  customProviderTitle: "Özel sağlayıcı",
  name: "Ad",
  hideKey: "Anahtarı gizle",
  showKey: "Anahtarı göster",
  save: "Kaydet",
  newSession: "Yeni oturum",
  prevSession: "Önceki oturum",
  nextSession: "Sonraki oturum",
  openTerminal: "Terminali aç",
  searchPlaceholder: "Komutları, dosyaları ara...",
  searchIn: "{folder} içinde ara",
  menu: "Menü",
  hideSessions: "Oturumları gizle",
  showSessions: "Oturumları göster",
  newSessionTitle: "Yeni oturum",
  prevSessionTitle: "Önceki oturum",
  nextSessionTitle: "Sonraki oturum",
  toggleTerminal: "Terminali değiştir",
  toggleSessions: "Oturumları değiştir",
  hideFileTree: "Dosya ağacını gizle",
  showFileTree: "Dosya ağacını göster",
  toggleFileTree: "Dosya ağacını değiştir",
  close: "Kapat",
  minimizeLabel: "Küçült",
  maximizeLabel: "Büyüt",
  closeLabel: "Kapat",
  welcomeSubtitle: "Açık proje yok. Bir oturum başlatmak için bir klasör seçin.",
  openProject: "Proje Aç",
  fatalErrorTitle: "vibe başlatılamadı",
  fatalErrorHint:
    "VIBE_API_KEY'i vibe yanındaki .env dosyasına, ~/.vibe/config'e veya ortam değişkeni olarak ayarlayın.",
  loadingText: "Openvibe yükleniyor…",
  noSessions: "Henüz oturum yok",
  untitled: "Başlıksız",
  deleteSession: "Oturumu sil",
  selectModel: "Bir model seçin:",
  revertToMessage: "Bu mesaja dön",
  copy: "Kopyala",
  completed: "Tamamlandı",
  diff: "Fark",
  regenerate: "Yeniden oluştur",
  reading: "Okunuyor",
  read: "Okundu",
  failedWrite: "Yazma başarısız",
  writing: "Yazılıyor",
  written: "Oluşturuldu",
  failedEdit: "Düzenleme başarısız",
  editing: "Düzenleniyor",
  edited: "Düzenlendi",
  listing: "Listeleniyor",
  listed: "Listelendi",
  searchingCodebase: "Kod tabanında aranıyor",
  searchedCodebase: "Search in codebase",
  running: "Çalıştırılıyor",
  ran: "Çalıştırıldı",
  tool: "Araç",
  newFile: "Yeni Dosya",
  newFolder: "Yeni Klasör",
  rename: "Yeniden adlandır",
  cut: "Kes",
  paste: "Yapıştır",
  delete: "Sil",
  deleteConfirm: "{name} silinsin mi?",
  createFailed: "Oluşturma başarısız: {error}",
  renameFailed: "Yeniden adlandırma başarısız: {error}",
  newFileTooltip: "Yeni dosya",
  newFolderTooltip: "Yeni klasör",
  refreshTooltip: "Yenile",
  collapseAllTooltip: "Tümünü daralt",
  loading: "yükleniyor…",
  closeProject: "Projeyi kapat",
  openProjectMenuItem: "Proje aç",
  revealExplorer: "Dosya gezgininde göster",
  removeFromList: "Listeden çıkar",
  openFolder: "Klasör aç",
  settings: "Ayarlar",
  stop: "Durdur",
  runCommand: "Komutu çalıştır",
  sendMessage: "Mesaj gönder",
  dropFilesAttach: "Eklemek için dosyaları sürükleyin",
  remove: "Kaldır",
  attachFiles: "Dosya ekle",
  cancel: "İptal",
  processing: "İşleniyor...",
  vibeAnything: "Bir şeyler yazın...",
  selectModelFallback: "Model Seç",
  searchModelPlaceholder: "Modelleri ara...",
  addProvider: "Sağlayıcı ekle",
  configureModels: "Modelleri yapılandır",
  noModelsFound: "Model bulunamadı",
  noModelsEnabled: "Etkin model yok",
  searching: "aranıyor…",
  noMatches: "eşleşme yok",
  terminal: "Terminal",
  search: "Ara",
  terminalTab: "Terminal {num}",
  closeTab: "Sekmeyi kapat",
  newTerminal: "Yeni terminal",
  shellExited: "[kabuk {code} koduyla çıktı]",
  cannotOpenFile: "Dosya açılamıyor",
  retry: "Tekrar dene",
  openFileFromTree: "Dosya ağacından bir dosya açın",
  unsavedChanges: "Kaydedilmemiş değişiklikler",
  closeFile: "{filename} kapat",
  filePath: "Dosya yolu",
  selectFileToEdit: "Düzenlenecek dosyayı seçin",
  copyCode: "Kopyala",
  openSettingsHotkey: "Ayarları Aç",
  clearChatHotkey: "Sohbeti Temizle",
  manuallyStopped: "Kullanıcı tarafından durduruldu",

  // MCP
  edit: "Düzenle",
  mcpServers: "MCP Sunucuları",
  mcpServersCount: "MCP Sunucuları ({count})",
  mcpRefreshStatuses: "Durumları yenile",
  mcpNoServersConfigured: "Yapılandırılmış MCP sunucusu yok",
  mcpOpenSettings: "MCP Ayarlarını Aç",
  mcpAddServer: "Sunucu Ekle",
  mcpVisualEditor: "Düzenleyici",
  mcpRawConfig: "Ham Yapılandırma",
  mcpExport: "Dışa Aktar",
  mcpImport: "İçe Aktar",
  mcpSaveTomlConfig: "TOML Yapılandırmasını Kaydet",
  mcpEnableServer: "Sunucuyu Etkinleştir",
  mcpDisableServer: "Sunucuyu Devre Dışı Bırak",
  mcpStartServer: "Sunucuyu Başlat",
  mcpStopServer: "Sunucuyu Durdur",
  mcpAddServerTitle: "MCP Sunucusu Ekle",
  mcpEditServerTitle: "MCP Sunucusunu Düzenle",
  mcpServerName: "Sunucu Adı",
  mcpCommandPath: "Komut (Çalıştırılabilir dosya yolu)",
  mcpCommandPlaceholder: "npx, uvx veya /dosya/yolu",
  mcpArguments: "Argümanlar (boşlukla ayrılmış)",
  mcpEnvVariables: "Ortam Değişkenleri",
  mcpEnvKeyPlaceholder: "ANAHTAR",
  mcpEnvValuePlaceholder: "DEĞER",
  mcpAddEnvVar: "+ Ortam Değişkeni Ekle",
  mcpEnableOnStartup: "Başlangıçta Etkinleştir",
  mcpSaveServer: "Sunucuyu Kaydet",
  mcpDeleteConfirm: "'{name}' MCP sunucusunu silmek istediğinizden emin misiniz?",
  mcpServerNameRequired: "Sunucu adı zorunludur.",
  mcpServerCommandRequired: "Sunucu komutu zorunludur.",
  mcpServerExists: "Bu isimde bir sunucu zaten var.",
  mcpSaveFailed: "Kaydetme başarısız: {error}",
  mcpInvalidJsonFormat: "MCP yapılandırması için geçersiz JSON formatı",
  mcpFailedParseJson: "İçe aktarılan JSON ayrıştırılamadı",
  mcpInvalidConfigFormat: "Geçersiz yapılandırma formatı: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 dosya değişti",
  commitFileChanged_few: "{count} dosya değişti",
  commitFileChanged: "{count} dosya değişti",
  commitInsertion_one: "1 ekleme(+)",
  commitInsertion_few: "{count} ekleme(+)",
  commitInsertion: "{count} ekleme(+)",
  commitDeletion_one: "1 silme(-)",
  commitDeletion_few: "{count} silme(-)",
  commitDeletion: "{count} silme(-)",
  openCommit: "Commit'i Aç",
  copyCommitHash: "Commit Hash'i Kopyala",
  openOnGitHub: "GitHub'da Aç",
  noFilesChanged: "Değişen dosya yok",
  inlineGenerating: "Kod oluşturuluyor...",
  inlineEditCode: "Inline Vibe'dan kodu düzenlemesini isteyin...",
  inlineRefineCode: "Inline Vibe'dan tekrar iyileştirmesini isteyin...",
  inlineSend: "Gönder (Ctrl+Enter)",
  inlineAccept: "Değişiklikleri Kabul Et",
  inlineReject: "Reddet",
  inlinePrevDiff: "Önceki Fark",
  inlineNextDiff: "Sonraki Fark",
  videoPlay: "Oynat (Space)",
  videoPause: "Duraklat (Space)",
  videoMute: "Sesi Kapat (M)",
  videoUnmute: "Sesi Aç (M)",
  videoVolume: "Ses",
  videoPlaybackSpeed: "Oynatma Hızı",
  videoFullscreen: "Tam Ekran (F)",
  failedReadFile: "Dosya okunamadı",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "Kopyala",
  regenerateMessage: "Yeniden Oluştur",

  // Source control
  sourceControl: "Kaynak Kontrolü",
  viewAsFlatList: "Düz Liste Olarak Görüntüle",
  viewsAndMoreActions: "Görüntülemeler ve Daha Fazla İşlem...",
  stageAllChanges: "Tüm Değişiklikleri Aşamalandır",
  checkoutCreateBranch: "Ödeme / Şube Oluştur...",
  refreshStatus: "Durumu Yenile",
  repositories: "Depolar",
  commitMessagePlaceholder: "Mesaj ('{branch}' üzerinde işlem yapmak için Ctrl+Enter)",
  commitBtn: "İşlemek",
  filterChangesPlaceholder: "Filtre değişiklikleri (ör. *.ts, src/)",
  clearFilter: "Filtreyi temizle",
  noChangesDetected: "Depoda herhangi bir değişiklik algılanmadı.",
  stagedChanges: "Aşamalı Değişiklikler",
  unstageAll: "Tümünü Kaldır",
  unstageChanges: "Değişiklikleri Geri Al",
  discardChanges: "Değişiklikleri İptal Et",
  stageChanges: "Aşama Değişiklikleri",
  graph: "Grafik",
  noCommitsInGraph: "Grafik geçmişinde taahhüt yok.",
  newBranchName: "Yeni şube adı...",
  createBranchBtn: "Yaratmak",
  currentBranch: "(akım)",

  // Auto-added translated keys
  renderFileTree: "Güzel dosya ağacı",
  renderFileTreeDesc: "Klasör yapılarını ham metin yerine güzel bir kullanıcı arayüzü bileşeni olarak işleyin",
  apiKeyPlaceholder: "API Anahtarı",
  customIcon: "Özel simge (URL veya yükleme)",
  modelsUrl: "Model listesi URL'si (isteğe bağlı)",
  headers: "Başlıklar",
  parameters: "Parametreler",
  headerKey: "Başlık adı",
  headerValue: "Başlık değeri",
  paramKey: "Parametre adı",
  paramValue: "Parametre değeri",
  uploadIcon: "Yükleme simgesi",
  closeTerminal: "Terminali kapat",
  hideButton: "Saklamak",
  showButton: "Göstermek",
  restoreButtons: "Düğmeleri geri yükle",
  filesChanged: "{count} dosya değiştirildi",
  filesChanged_one: "{count} dosya değiştirildi",
  filesChanged_few: "{count} dosya değiştirildi",
  changes: "Değişiklikler",
  exploring: "Keşfetmek",
  explored: "Keşfetmek",
  editProject: "Düzenlemek",
  editProjectTitle: "Projeyi düzenle",
  projectIcon: "Simge",
  backgroundColor: "Arka plan rengi",
  closeFromList: "Kapalı",
  searchInCode: "Kodda Ara",
  searchInCodePlaceholder: "Aramak",
  replacePlaceholder: "Yer değiştirmek",
  refreshSearch: "Aramayı yenile",
  clearSearchResults: "Arama sonuçlarını temizle",
  viewAsTree: "Ağaç Olarak Görüntüle",
  showReplace: "Değiştir'i Göster",
  hideReplace: "Gizle Değiştir",
  matchCase: "Maç Durumu",
  matchWholeWord: "Tüm Kelimeyi Eşleştir",
  useRegex: "Normal İfade Kullan",
  preserveCase: "Kasayı Koru",
  replaceAll: "Tümünü Değiştir",
  filesToIncludeExclude: "Dahil Edilecek/Hariç Tutulacak Dosyalar",
  filesToInclude: "dahil edilecek dosyalar",
  filesToExclude: "hariç tutulacak dosyalar",
  includePlaceholder: "örneğin *.ts, kaynak/**",
  excludePlaceholder: "örneğin node_modules, *.test.ts",
  noResultsFound: "Sonuç bulunamadı.",
  searchInCodeResults_one: "{fileCount} dosyasında {count} sonuç",
  searchInCodeResults_few: "{count}, {fileCount} dosyayla sonuçlanıyor",
  searchInCodeResults: "{count}, {fileCount} dosyayla sonuçlanıyor",
  typeToSearch: "Dosyaları içeriğe göre bulmak için bir arama sorgusu yazın.",
  loadingMatches: "Yükleniyor...",
  moreMatches_one: "… ve {count} eşleşme daha",
  moreMatches_few: "… ve {count} eşleşme daha",
  moreMatches: "… ve {count} eşleşme daha",
  newProjectHotkey: "Yeni Proje",
  closeProjectHotkey: "Projeyi Kapat",
  closeFileHotkey: "Dosyayı Kapat",
  navigation: "Navigasyon",
  chat: "Sohbet",
  workspace: "Çalışma alanı",
  project: "Proje",
  editor: "Editör",
  noHotkeys: "Kısayol tuşu yüklenmedi",
  design: "Tasarım",
  animations: "Animasyonlar",
  animStyleFade: "Solmak",
  animStyleSlide: "Slayt",
  animStyleScale: "Ölçek",
  animStyleFadeSlide: "Soldur + Kaydır",
  animStyleNone: "Animasyon yok",
  animProjectHover: "Proje vurgulu",
  animProjectHoverDesc: "Bir proje kutucuğunun üzerine gelindiğinde animasyon",
  animProjectSwitch: "Proje anahtarı",
  animProjectSwitchDesc: "Yeni bir proje açarken geçiş",
  animSidebarSlide: "Kenar çubuğu",
  animSidebarSlideDesc: "Yan panelin açılması/kapatılması",
  animContextMenu: "Bağlam menüsü",
  animContextMenuDesc: "Bağlam menüsü görünümü",
  animButtons: "Düğmeler",
  animButtonsDesc: "Fareyle üzerine gelindiğinde etkileşimli öğeler",
  animPanelAppear: "Paneller ve modeller",
  animPanelAppearDesc: "Ayarlar, açılır pencereler ve modal görünüm",
  animMultiplier: "Animasyon düzgünlüğü",
  animMultiplierDesc:
    "Animasyon düzgünlüğü çarpanı. 0 = durduruldu, 0,5 = hızlı, 1 = normal, 2 = pürüzsüz, 5 = son derece yumuşak",
  windowEffects: "Pencere Efektleri",
  blurOverlay: "Arka plan bulanıklığı",
  blurOverlayDesc: "Kalıcı pencerelerin (ayarlar, içerik menüleri) arkasındaki içeriği bulanıklaştırın",
  blurNone: "Hiçbiri",
  blurSubtle: "Hemen göze çarpmayan",
  blurStrong: "Güçlü",
  borderRadius: "Sınır yarıçapı",
  borderRadiusDesc: "UI öğeleri için köşe yuvarlama",
  uiZoom: "Kullanıcı Arayüzü Yakınlaştırma",
  zoomStep: "Yakınlaştırma adımı",
  zoomStepDesc: "Her Ctrl+Artı/Ctrl+Eksi basımı yakınlaştırma düzeyini ne kadar değiştirir?",
  zoomDefault: "Varsayılan yakınlaştırma",
  zoomDefaultDesc: "Ctrl+0 tuşlarına basıldığında yakınlaştırma düzeyi",
  terminalShell: "Terminal Kabuğu",
  appName: "OpenVibe Masaüstü",
  appVersion: "v1.3.9",
  shell: "Kabuk",
  langRussian: "Rusça",
  langEnglish: "İngilizce",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "Ukrayna",
  langBelarusian: "Belarusça",
  langSpanish: "İspanyol",
  langItalian: "İtalyan",
  langPortuguese: "Portekizce",
  langJapanese: "Japonca",
  langSerbian: "Sırpça",
  langFrench: "Fransızca",
  langGerman: "Almanca",
  langHindi: "Hintçe",
  langArabic: "Arapça",
  langIndonesian: "Endonezya dili",
  langKorean: "Korece",
  langTurkish: "Türkçe",
  langVietnamese: "Vietnam",
  langPolish: "Lehçe",
  langDutch: "Flemenkçe",
  langRomanian: "Romen",
  langGreek: "Yunan",
  langSwedish: "İsveççe",
  langKazakh: "Kazak",
  langAzerbaijani: "Azerice",
  langThai: "Tay dili",
  langBengali: "Bengalce",
  langPunjabi: "Pencap",
  langBulgarian: "Bulgarca",
  langCzech: "Çek",
  langFilipino: "Filipinli",
  langPersian: "Farsça",
  langMalay: "Malayca",
  langBurmese: "Birmanya",
  langAmharic: "Amharca",
  langMarathi: "Marathi",
  codeTab: "Kod",
  editorFontSize: "Yazı Tipi Boyutu",
  editorFontSizeDesc: "Düzenleyici ve terminal yazı tipi boyutu",
  editorLineHeight: "Satır Yüksekliği",
  editorLineHeightDesc: "Düzenleyici satır yüksekliği çarpanı",
  editorLigatures: "Yazı Tipi Bitişik Harfler",
  editorLigaturesDesc: "Kodlama bitişik harflerini etkinleştirin (ör. =>, ===)",
  editorCursorStyle: "İmleç Stili",
  editorCursorStyleDesc: "Düzenleyici imlecinin şekli",
  editorCursorBlink: "İmleç Yanıp Sönüyor",
  editorCursorBlinkDesc: "İmlecin animasyon stili",
  cursorLine: "Astar",
  cursorBlock: "Engellemek",
  cursorUnderline: "Altı çizili",
  cursorLineThin: "Çizgi İnce",
  cursorBlockOutline: "Blok Taslağı",
  cursorUnderlineThin: "İnce Altı Çizili",
  blinkBlink: "Göz kırpmak",
  blinkSmooth: "Düz",
  blinkPhase: "Faz",
  blinkExpand: "Genişletmek",
  blinkSolid: "Sağlam",
  manageThemes: "Temaları Yönet",
  manageThemesDesc: "Renk temalarınızı içe veya dışa aktarın",
  importTheme: "İçe aktarmak",
  exportTheme: "İhracat",
  borderStyle: "Kenarlık Stili",
  borderStyleDesc: "Panel kenarlıklarını açma veya kapatma",
  borderStyleBordered: "Kenarlıklı",
  borderStyleBorderless: "Kenarlıksız",
  hideSourceControl: "Kaynak Denetimini Gizle",
  showSourceControl: "Kaynak Denetimini Göster",

  // Newly added UI strings
  backBtn: "Geri",
  onboardingStepSettingsTitle: "Çalışma alanı ayarları",
  continueBtn: "Devam etmek",
  welcomeThanks: "İş akışınız için OpenVibe'yi kuralım.",
  startVibingBtn: "Kurulumu bitir",
  rerunOnboarding: "Kurulum Sihirbazını Çalıştır",
  onboardingStepThemeTitle: "Bir tema seçin",
  letsVibeBtn: "Haydi heyecanlanalım",
  animationSpeed: "Animasyon Hızı",
  onboardingStepSettingsDesc: "Tercihlerinizi şimdi ayarlayın veya daha sonra değiştirin.",
  onboardingStepAnimationDesc: "Arayüz öğeleri için geçiş stillerini seçin ve düzgünlüklerini ayarlayın.",
  useRegionalProxy: "Bölgesel proxy kullan (Avrupa)",
  welcomeGreeting: "Merhaba {name}",
  rerunOnboardingDesc: "İlk karşılama ekranını ve hızlı katılım sihirbazını yeniden tetikleyin",
  useRegionalProxyDesc:
    "Bölgesel kısıtlamaları aşmak için API isteklerini Avrupa'daki hızlı bir proxy sunucusu üzerinden yönlendirin",
  onboardingStepThemeDesc: "Devam etmeden önce bir temayı önizleyin.",
  onboardingStepAnimationTitle: "Animasyon kurulumu",
  animationSpeedDesc: "Arayüz geçişleri ve yumuşak efekt ölçeklendirme",
  activityFetchUrl: "{url} web sayfası getiriliyor",
  activityFetchUrlGeneral: "Web sayfası getiriliyor",
  activityGitBranches: "Git şubelerini görüntüleme",
  activityGitCommand: "Git işlemi: {command}",
  activityGitDiff: "Git farkını inceleme",
  activityGitLog: "Git yürütme günlüğünü görüntüleme",
  activityGitStatus: "Git durumunu kontrol etme",
  activityGroupAgent: "soruşturma",
  activityGroupAgentN: "Soruşturma — {count} görev",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "Soruşturma — {count} görev",
  activityGroupBrowse: "klasörlere göz atma",
  activityGroupBrowseN: "{count} klasöre göz atılıyor",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "{count} klasörüne göz atılıyor",
  activityGroupCommand: "komutları çalıştırma",
  activityGroupCommandN: "{count} komutlarını çalıştırma",
  activityGroupCommandN_few: "Выполнение {count} kodu",
  activityGroupCommandN_one: "{count} komutunu çalıştırma",
  activityGroupEdit: "düzenlenmiş dosyalar",
  activityGroupEditN: "{count} dosya düzenleniyor",
  activityGroupEditN_few: "Редактирование {count} файлов",
  activityGroupEditN_one: "{count} dosyası düzenleniyor",
  activityGroupExternal: "harici araçlar",
  activityGroupExternalN: "Harici araçlar — {count} çağrı",
  activityGroupExternalN_few: "Внешние инструменты — {count} вызова",
  activityGroupExternalN_one: "Harici araç — {count} çağrı",
  activityGroupGit: "Git işlemleri",
  activityGroupGitN: "Git — {count} işlemler",
  activityGroupGitN_few: "Git — {count} işlem",
  activityGroupGitN_one: "Git — {count} işlemi",
  activityGroupRead: "dosyaları okuma",
  activityGroupReadN: "{count} dosya okunuyor",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "{count} dosyası okunuyor",
  activityGroupSearch: "aramak",
  activityGroupSearchN: "Arama — {count} sorgu",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "Ara — {count} sorgu",
  activityGroupTodo: "görev planlama",
  activityGroupTodoN: "Planlama — {count} görev",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "Planlama — {count} görev",

  // Agent flow (linear run redesign)
  flowThinking: "Düşünüyor…",
  flowThought: "Düşünce süreci",
  flowAnalysis: "Analiz",
  flowCountRead: "{count} okuma",
  flowCountSearch: "{count} arama",
  flowCountBrowse: "{count} klasör görüntüleme",
  flowCountWeb: "{count} web araması",
  flowCountGit: "{count} git işlemi",
  activityGroupTools: "eylemler",
  activityGroupToolsN: "{count} işlem",
  activityGroupToolsN_few: "{count} teslimat",
  activityGroupToolsN_one: "{count} eylemi",
  activityGroupWeb: "web araması",
  activityGroupWebN: "Web araması — {count} sorgu",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "Web araması — {count} sorgu",
  activityInspectFolder: "{name} keşfediliyor",
  activityInvestigateTask: "Görevin araştırılması",
  activityProjectStructure: "Proje yapısını keşfetme",
  activityReadCode: "Kodun gözden geçirilmesi",
  activityReadFile: "{name} inceleniyor",
  activityRepeatedCalls: "{count} çağrı",
  activityRunCommand: "Projeyi kontrol etmek",
  activitySearchCode: "İlgili uygulamanın aranması",
  activitySearchQuery: "“{query}” aranıyor",
  activityUpdateCode: "Kodu güncelleme",
  activityUpdateFile: "{name} güncelleniyor",
  activityUseTool: "{name} çalıştırılıyor",
  activityWebSearch: 'Web\'de "{query}" aranıyor',
  activityWebSearchGeneral: "Bilgi için web'de arama yapmak",
  addModel: "Model ekle",
  agentRunMinutesShort: "{sayı} m",
  agentRunSeconds: "{count} saniye",
  agentRunSecondsShort: "{count}'lar",
  agentRunSeconds_few: "{count} saniye",
  agentRunSeconds_one: "{count} saniye",
  agentRunWorkedFor: "{time} süreyle çalıştı",
  agentRunWorkingFor: "{time} çalışıyor",
  copyFormatted: "Metni kopyala",
  copyRaw: "Ham olarak kopyala",
  customModelsLabel: "Modeller",
  errorNoticeBlockedTitle: "Sağlayıcı erişimi kısıtlandı",
  errorNoticeNetworkTitle: "Servise ulaşamadım",
  errorNoticeProviderTitle: "Sağlayıcı bir hata döndürdü",
  errorNoticeQuotaTitle: "Sağlayıcı sınırına ulaşıldı",
  experimentalExtremeRadius: "Deneysel aşırı yarıçap (100 piksele kadar)",
  experimentalExtremeRadiusDesc:
    "Kullanıcı arayüzü kenarlık yarıçapının 100 piksele kadar ayarlanmasına izin verir. Deneysel bayrak!",
  fetchedUrl: "Getirilen URL",
  fetchingUrl: "URL getiriliyor",
  generateCommitMessage: "AI ile taahhüt mesajı oluşturun",
  gitBlame: "Satır yazarlığının analizi",
  gitBlameDone: "Analiz edilen satır yazarlığı",
  gitBranches: "Şubeleri denetlemek",
  gitBranchesDone: "Denetlenen şubeler",
  gitDiff: "Değişiklikleri gözden geçirme",
  gitDiffDone: "İncelenen değişiklikler",
  gitInspect: "Git geçmişini inceleme",
  gitInspectDone: "Git geçmişi incelendi",
  gitLog: "Taahhütleri gözden geçirme",
  gitLogDone: "İncelenen taahhütler",
  gitRefs: "Git referanslarını inceleme",
  gitRefsDone: "İncelenen Git referansları",
  gitShow: "Git nesnesini inceleme",
  gitShowDone: "İncelenen Git nesnesi",
  gitStatus: "Durum inceleniyor",
  gitStatusDone: "Denetlenme durumu",
  hideToolCalls: "Araç çağrılarını gizle",
  modelDisplayName: "Ekran adı",
  modelIdPlaceholder: "model kimliği",
  promptMarkdown: "İstem Girişinde İşaretleme",
  promptMarkdownDesc: "İstemleri yazarken Markdown formatını canlı olarak işleme",
  promptMarkdownGhost: "Sözdizimi İşaretçilerini Göster (**)",
  promptMarkdownGhostDesc: "Biçimlendirilmiş metin içinde soluk sözdizimi karakterlerini (**, `, #) görüntüle",
  reasoningEffortHigh: "Yüksek",
  reasoningEffortLow: "Düşük",
  reasoningEffortMedium: "Orta",
  reasoningEffortNone: "Hiçbiri",
  searchedWeb: "Web araması",
  searchingWeb: "Web'de arama",
  showToolCalls: "Araç çağrılarını göster",
  tabStyle: "Sekme Stili",
  tabStyleDefault: "Varsayılan",
  tabStyleDesc: "Düzenleyici sekmeleri için kare veya yuvarlak haplar",
  tabStylePills: "Haplar",
  todoBlocked: "Görevde engellendi",
  todoCompleted: "Tamamlanan görev",
  todoCount: "{tamamlandı} / {count}",
  todoCreated: "Görev planı oluşturuldu",
  todoPin: "Görev listesini sabitle",
  todoProgress: "Tamamlanan görevler: {completed} / {count}",
  todoTitle: "Görevler",
  todoUnpin: "Görev listesinin sabitlemesini kaldır",
};
