import type { Translations } from "./ru";

export const vi: Partial<Translations> = {
  app: "Ứng dụng",
  general: "Tổng quan",
  hotkeys: "Phím tắt",
  server: "Máy chủ",
  providers: "Nhà cung cấp",
  models: "Mô hình",
  language: "Ngôn ngữ",
  languageDesc: "Thay đổi ngôn ngữ hiển thị của OpenVibe",
  autoAccept: "Tự động chấp nhận quyền",
  autoAcceptDesc: "Yêu cầu cấp quyền sẽ được tự động phê duyệt",
  terminalShellDesc: "Shell cho terminal tích hợp",
  showThinking: "Hiển thị tóm tắt suy luận",
  showThinkingDesc: "Hiển thị quá trình suy nghĩ của mô hình",
  theme: "Chủ đề",
  themeDesc: "Chọn chủ đề ứng dụng",
  colorScheme: "Bảng màu",
  colorSchemeDesc: "Sáng, tối hoặc hệ thống",
  dark: "Tối",
  light: "Sáng",
  system: "Hệ thống",
  font: "Phông chữ",
  fontDesc: "Phông chữ giao diện chính",
  systemFont: "Hệ thống",
  codeFont: "Phông chữ mã",
  codeFontDesc: "Phông chữ đơn cách cho trình soạn thảo và terminal",
  soundNotifications: "Thông báo âm thanh",
  soundEnabled: "Bật âm thanh",
  soundEnabledDesc: "Phát thông báo âm thanh",
  soundOnComplete: "Hoàn thành tác vụ",
  soundOnCompleteDesc: "Âm thanh khi hoàn thành thành công",
  soundOnStop: "Dừng tác vụ",
  soundOnStopDesc: "Âm thanh khi dừng bắt buộc",
  connectedProviders: "Nhà cung cấp đã kết nối",
  disconnect: "Ngắt kết nối",
  connect: "Kết nối",
  customProvider: "Nhà cung cấp tùy chỉnh",
  searchModels: "Tìm kiếm mô hình...",
  loadingModels: "Đang tải mô hình...",
  noModels: "Kết nối ít nhất một nhà cung cấp để xem danh sách mô hình.",
  editProvider: "Chỉnh sửa nhà cung cấp",
  customProviderTitle: "Nhà cung cấp tùy chỉnh",
  name: "Tên",
  hideKey: "Ẩn khóa",
  showKey: "Hiện khóa",
  save: "Lưu",
  newSession: "Phiên mới",
  prevSession: "Phiên trước",
  nextSession: "Phiên tiếp theo",
  openTerminal: "Mở terminal",
  searchPlaceholder: "Tìm kiếm lệnh, tệp...",
  searchIn: "Tìm trong {folder}",
  menu: "Menu",
  hideSessions: "Ẩn phiên",
  showSessions: "Hiện phiên",
  newSessionTitle: "Phiên mới",
  prevSessionTitle: "Phiên trước",
  nextSessionTitle: "Phiên tiếp theo",
  toggleTerminal: "Chuyển đổi Terminal",
  toggleSessions: "Chuyển đổi phiên",
  hideFileTree: "Ẩn cây tệp",
  showFileTree: "Hiện cây tệp",
  toggleFileTree: "Chuyển đổi cây tệp",
  close: "Đóng",
  minimizeLabel: "Thu nhỏ",
  maximizeLabel: "Phóng to",
  closeLabel: "Đóng",
  welcomeSubtitle: "Không có dự án nào đang mở. Chọn một thư mục để bắt đầu phiên làm việc.",
  openProject: "Mở Dự án",
  fatalErrorTitle: "Không thể khởi động vibe",
  fatalErrorHint: "Đặt VIBE_API_KEY trong .env bên cạnh vibe, trong ~/.vibe/config hoặc dưới dạng biến môi trường.",
  loadingText: "Openvibe đang tải…",
  noSessions: "Chưa có phiên nào",
  untitled: "Chưa có tiêu đề",
  deleteSession: "Xóa phiên",
  selectModel: "Chọn mô hình:",
  revertToMessage: "Quay lại tin nhắn này",
  copy: "Sao chép",
  completed: "Đã hoàn thành",
  diff: "Khác biệt",
  regenerate: "Tạo lại",
  reading: "Đang đọc",
  read: "Đã đọc",
  failedWrite: "Ghi thất bại",
  writing: "Đang ghi",
  written: "Đã tạo",
  failedEdit: "Chỉnh sửa thất bại",
  editing: "Đang chỉnh sửa",
  edited: "Đã chỉnh sửa",
  listing: "Đang liệt kê",
  listed: "Đã liệt kê",
  searchingCodebase: "Đang tìm trong mã nguồn",
  searchedCodebase: "Search in codebase",
  running: "Đang chạy",
  ran: "Đã chạy",
  tool: "Công cụ",
  newFile: "Tệp Mới",
  newFolder: "Thư mục Mới",
  rename: "Đổi tên",
  cut: "Cắt",
  paste: "Dán",
  delete: "Xóa",
  deleteConfirm: "Xóa {name}?",
  createFailed: "Tạo thất bại: {error}",
  renameFailed: "Đổi tên thất bại: {error}",
  newFileTooltip: "Tệp mới",
  newFolderTooltip: "Thư mục mới",
  refreshTooltip: "Làm mới",
  collapseAllTooltip: "Thu gọn tất cả",
  loading: "đang tải…",
  closeProject: "Đóng dự án",
  openProjectMenuItem: "Mở dự án",
  revealExplorer: "Hiện trong trình khám phá tệp",
  removeFromList: "Xóa khỏi danh sách",
  openFolder: "Mở thư mục",
  settings: "Cài đặt",
  stop: "Dừng",
  runCommand: "Chạy lệnh",
  sendMessage: "Gửi tin nhắn",
  dropFilesAttach: "Thả tệp để đính kèm",
  remove: "Xóa",
  attachFiles: "Đính kèm tệp",
  cancel: "Hủy",
  processing: "Đang xử lý...",
  vibeAnything: "Viết gì đó...",
  selectModelFallback: "Chọn Mô hình",
  searchModelPlaceholder: "Tìm kiếm mô hình...",
  addProvider: "Thêm nhà cung cấp",
  configureModels: "Cấu hình mô hình",
  noModelsFound: "Không tìm thấy mô hình",
  noModelsEnabled: "Không có mô hình nào được bật",
  searching: "đang tìm…",
  noMatches: "không có kết quả",
  terminal: "Terminal",
  search: "Tìm kiếm",
  terminalTab: "Terminal {num}",
  closeTab: "Đóng tab",
  newTerminal: "Terminal mới",
  shellExited: "[shell đã thoát với mã {code}]",
  cannotOpenFile: "Không thể mở tệp",
  retry: "Thử lại",
  openFileFromTree: "Mở tệp từ cây tệp",
  unsavedChanges: "Thay đổi chưa lưu",
  closeFile: "Đóng {filename}",
  filePath: "Đường dẫn tệp",
  selectFileToEdit: "Chọn tệp để chỉnh sửa",
  copyCode: "Sao chép",
  openSettingsHotkey: "Mở Cài đặt",
  clearChatHotkey: "Xóa Trò chuyện",
  manuallyStopped: "Đã dừng bởi người dùng",

  // MCP
  edit: "Chỉnh sửa",
  mcpServers: "Máy chủ MCP",
  mcpServersCount: "Máy chủ MCP ({count})",
  mcpRefreshStatuses: "Làm mới trạng thái",
  mcpNoServersConfigured: "Chưa cấu hình máy chủ MCP",
  mcpOpenSettings: "Mở Cài đặt MCP",
  mcpAddServer: "Thêm máy chủ",
  mcpVisualEditor: "Trình chỉnh sửa",
  mcpRawConfig: "Cấu hình thô",
  mcpExport: "Xuất",
  mcpImport: "Nhập",
  mcpSaveTomlConfig: "Lưu cấu hình TOML",
  mcpEnableServer: "Bật máy chủ",
  mcpDisableServer: "Tắt máy chủ",
  mcpStartServer: "Bắt đầu máy chủ",
  mcpStopServer: "Dừng máy chủ",
  mcpAddServerTitle: "Thêm máy chủ MCP",
  mcpEditServerTitle: "Chỉnh sửa máy chủ MCP",
  mcpServerName: "Tên máy chủ",
  mcpCommandPath: "Lệnh (Đường dẫn tệp thực thi)",
  mcpCommandPlaceholder: "npx, uvx hoặc /duong/dan/taptin",
  mcpArguments: "Đối số (phân cách bằng dấu cách)",
  mcpEnvVariables: "Biến môi trường",
  mcpEnvKeyPlaceholder: "KHÓA",
  mcpEnvValuePlaceholder: "GIÁ TRỊ",
  mcpAddEnvVar: "+ Thêm biến môi trường",
  mcpEnableOnStartup: "Bật khi khởi động",
  mcpSaveServer: "Lưu máy chủ",
  mcpDeleteConfirm: "Bạn có chắc chắn muốn xóa máy chủ MCP '{name}' không?",
  mcpServerNameRequired: "Tên máy chủ là bắt buộc.",
  mcpServerCommandRequired: "Lệnh máy chủ là bắt buộc.",
  mcpServerExists: "Máy chủ với tên này đã tồn tại.",
  mcpSaveFailed: "Lưu thất bại: {error}",
  mcpInvalidJsonFormat: "Định dạng JSON không hợp lệ cho cấu hình MCP",
  mcpFailedParseJson: "Không thể phân tích cú pháp JSON đã nhập",
  mcpInvalidConfigFormat: "Định dạng cấu hình không hợp lệ: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 tệp thay đổi",
  commitFileChanged_few: "{count} tệp thay đổi",
  commitFileChanged: "{count} tệp thay đổi",
  commitInsertion_one: "1 lần chèn(+)",
  commitInsertion_few: "{count} lần chèn(+)",
  commitInsertion: "{count} lần chèn(+)",
  commitDeletion_one: "1 lần xóa(-)",
  commitDeletion_few: "{count} lần xóa(-)",
  commitDeletion: "{count} lần xóa(-)",
  openCommit: "Mở Commit",
  copyCommitHash: "Sao chép Hash Commit",
  openOnGitHub: "Mở trên GitHub",
  noFilesChanged: "Không có tệp thay đổi",
  inlineGenerating: "Đang tạo mã...",
  inlineEditCode: "Yêu cầu Inline Vibe chỉnh sửa mã...",
  inlineRefineCode: "Yêu cầu Inline Vibe tinh chỉnh lại...",
  inlineSend: "Gửi (Ctrl+Enter)",
  inlineAccept: "Chấp nhận thay đổi",
  inlineReject: "Từ chối",
  inlinePrevDiff: "Diff trước",
  inlineNextDiff: "Diff tiếp theo",
  videoPlay: "Phát (Space)",
  videoPause: "Tạm dừng (Space)",
  videoMute: "Tắt tiếng (M)",
  videoUnmute: "Bật tiếng (M)",
  videoVolume: "Âm lượng",
  videoPlaybackSpeed: "Tốc độ phát lại",
  videoFullscreen: "Toàn màn hình (F)",
  failedReadFile: "Không thể đọc tệp",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "Sao chép",
  regenerateMessage: "Tạo lại",

  // Source control
  sourceControl: "Kiểm soát nguồn",
  viewAsFlatList: "Xem dưới dạng danh sách phẳng",
  viewsAndMoreActions: "Lượt xem và hành động khác...",
  stageAllChanges: "Giai đoạn tất cả các thay đổi",
  checkoutCreateBranch: "Thanh toán/Tạo chi nhánh...",
  refreshStatus: "Trạng thái làm mới",
  repositories: "Kho lưu trữ",
  commitMessagePlaceholder: "Thông báo (Ctrl+Enter để xác nhận trên '{branch}')",
  commitBtn: "Làm",
  filterChangesPlaceholder: "Thay đổi bộ lọc (ví dụ: *.ts, src/)",
  clearFilter: "Xóa bộ lọc",
  noChangesDetected: "Không có thay đổi nào được phát hiện trong kho lưu trữ.",
  stagedChanges: "Thay đổi theo giai đoạn",
  unstageAll: "Bỏ qua tất cả",
  unstageChanges: "Thay đổi không giai đoạn",
  discardChanges: "Hủy thay đổi",
  stageChanges: "Thay đổi giai đoạn",
  graph: "đồ thị",
  noCommitsInGraph: "Không có cam kết trong lịch sử biểu đồ.",
  newBranchName: "Tên chi nhánh mới...",
  createBranchBtn: "Tạo nên",
  currentBranch: "(hiện hành)",

  // Auto-added translated keys
  renderFileTree: "Cây hồ sơ đẹp",
  renderFileTreeDesc: "Kết xuất cấu trúc thư mục dưới dạng thành phần giao diện người dùng đẹp thay vì văn bản thô",
  apiKeyPlaceholder: "Khóa API",
  customIcon: "Biểu tượng tùy chỉnh (URL hoặc tải lên)",
  modelsUrl: "URL danh sách mô hình (tùy chọn)",
  headers: "Tiêu đề",
  parameters: "Thông số",
  headerKey: "Tên tiêu đề",
  headerValue: "Giá trị tiêu đề",
  paramKey: "Tên tham số",
  paramValue: "Giá trị tham số",
  uploadIcon: "Biểu tượng tải lên",
  closeTerminal: "Đóng thiết bị đầu cuối",
  hideButton: "Trốn",
  showButton: "Trình diễn",
  restoreButtons: "Nút khôi phục",
  filesChanged: "{count} tệp đã thay đổi",
  filesChanged_one: "tập tin {count} đã thay đổi",
  filesChanged_few: "{count} tệp đã thay đổi",
  changes: "Thay đổi",
  exploring: "Khám phá",
  explored: "Khám phá",
  editProject: "Biên tập",
  editProjectTitle: "Chỉnh sửa dự án",
  projectIcon: "Biểu tượng",
  backgroundColor: "Màu nền",
  closeFromList: "Đóng",
  searchInCode: "Tìm kiếm trong Mã",
  searchInCodePlaceholder: "Tìm kiếm",
  replacePlaceholder: "Thay thế",
  refreshSearch: "Làm mới tìm kiếm",
  clearSearchResults: "Xóa kết quả tìm kiếm",
  viewAsTree: "Xem dưới dạng cây",
  showReplace: "Hiển thị Thay thế",
  hideReplace: "Ẩn Thay thế",
  matchCase: "Hộp đựng trận đấu",
  matchWholeWord: "Ghép toàn bộ từ",
  useRegex: "Sử dụng biểu thức chính quy",
  preserveCase: "Hộp bảo quản",
  replaceAll: "Thay thế tất cả",
  filesToIncludeExclude: "Các tập tin cần bao gồm/loại trừ",
  filesToInclude: "tập tin để bao gồm",
  filesToExclude: "tập tin cần loại trừ",
  includePlaceholder: "ví dụ. *.ts, src/**",
  excludePlaceholder: "ví dụ. node_modules, *.test.ts",
  noResultsFound: "Không tìm thấy kết quả nào.",
  searchInCodeResults_one: "{count} dẫn đến tệp {fileCount}",
  searchInCodeResults_few: "{count} dẫn đến tệp {fileCount}",
  searchInCodeResults: "{count} dẫn đến tệp {fileCount}",
  typeToSearch: "Nhập truy vấn tìm kiếm để tìm tệp theo nội dung.",
  loadingMatches: "Đang tải...",
  moreMatches_one: "… và {count} trận đấu khác",
  moreMatches_few: "… và {count} kết quả phù hợp khác",
  moreMatches: "… và {count} kết quả phù hợp khác",
  newProjectHotkey: "Dự án mới",
  closeProjectHotkey: "Đóng dự án",
  closeFileHotkey: "Đóng tệp",
  navigation: "Điều hướng",
  chat: "Trò chuyện",
  workspace: "Không gian làm việc",
  project: "Dự án",
  editor: "Biên tập viên",
  noHotkeys: "Không có phím nóng nào được tải",
  design: "Thiết kế",
  animations: "Hoạt hình",
  animStyleFade: "Phai",
  animStyleSlide: "Cầu trượt",
  animStyleScale: "Tỉ lệ",
  animStyleFadeSlide: "Làm mờ dần + Trượt",
  animStyleNone: "Không có hình ảnh động",
  animProjectHover: "Dự án di chuột",
  animProjectHoverDesc: "Hoạt ảnh khi di chuột qua ô dự án",
  animProjectSwitch: "Chuyển đổi dự án",
  animProjectSwitchDesc: "Chuyển tiếp khi mở dự án mới",
  animSidebarSlide: "Thanh bên",
  animSidebarSlideDesc: "Mở/đóng bảng điều khiển bên",
  animContextMenu: "Trình đơn ngữ cảnh",
  animContextMenuDesc: "Giao diện menu ngữ cảnh",
  animButtons: "Nút",
  animButtonsDesc: "Các yếu tố tương tác khi di chuột",
  animPanelAppear: "Bảng điều khiển & phương thức",
  animPanelAppearDesc: "Cài đặt, cửa sổ bật lên và giao diện phương thức",
  animMultiplier: "Độ mượt của hoạt ảnh",
  animMultiplierDesc:
    "Animation smoothness multiplier. 0 = stopped, 0.5 = snappy, 1 = normal, 2 = smooth, 5 = ultra smooth",
  windowEffects: "Hiệu ứng cửa sổ",
  blurOverlay: "Làm mờ nền",
  blurOverlayDesc: "Làm mờ nội dung đằng sau các cửa sổ phương thức (cài đặt, menu ngữ cảnh)",
  blurNone: "Không có",
  blurSubtle: "tinh tế",
  blurStrong: "Mạnh",
  borderRadius: "Bán kính viền",
  borderRadiusDesc: "Làm tròn góc cho các thành phần UI",
  uiZoom: "Thu phóng giao diện người dùng",
  zoomStep: "Bước thu phóng",
  zoomStepDesc: "Mỗi lần nhấn Ctrl+Plus/Ctrl+Trừ sẽ thay đổi mức thu phóng bao nhiêu",
  zoomDefault: "Thu phóng mặc định",
  zoomDefaultDesc: "Mức thu phóng khi nhấn Ctrl+0",
  terminalShell: "Vỏ thiết bị đầu cuối",
  appName: "Máy tính để bàn OpenVibe",
  appVersion: "v1.3.9",
  shell: "Vỏ bọc",
  langRussian: "tiếng Nga",
  langEnglish: "Tiếng Anh",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "简体中文",
  langUkrainian: "tiếng Ukraina",
  langBelarusian: "Tiếng Belarus",
  langSpanish: "tiếng Tây Ban Nha",
  langItalian: "người Ý",
  langPortuguese: "tiếng Bồ Đào Nha",
  langJapanese: "tiếng Nhật",
  langSerbian: "tiếng Serbia",
  langFrench: "người Pháp",
  langGerman: "tiếng Đức",
  langHindi: "Tiếng Hindi",
  langArabic: "tiếng Ả Rập",
  langIndonesian: "tiếng Indonesia",
  langKorean: "Tiếng Hàn",
  langTurkish: "tiếng Thổ Nhĩ Kỳ",
  langVietnamese: "Tiếng Việt",
  langPolish: "Đánh bóng",
  langDutch: "tiếng Hà Lan",
  langRomanian: "người Rumani",
  langGreek: "tiếng Hy Lạp",
  langSwedish: "tiếng Thụy Điển",
  langKazakh: "Kazakhstan",
  langAzerbaijani: "Tiếng Azerbaijan",
  langThai: "tiếng Thái",
  langBengali: "tiếng Bengali",
  langPunjabi: "Tiếng Punjab",
  langBulgarian: "tiếng Bungari",
  langCzech: "tiếng Séc",
  langFilipino: "Tiếng Philippin",
  langPersian: "tiếng Ba Tư",
  langMalay: "Mã Lai",
  langBurmese: "Miến Điện",
  langAmharic: "tiếng Amharic",
  langMarathi: "Tiếng Marathi",
  codeTab: "Mã số",
  editorFontSize: "Cỡ chữ",
  editorFontSizeDesc: "Kích thước phông chữ của trình soạn thảo và thiết bị đầu cuối",
  editorLineHeight: "Chiều cao dòng",
  editorLineHeightDesc: "Hệ số chiều cao dòng soạn thảo",
  editorLigatures: "Chữ ghép chữ",
  editorLigaturesDesc: "Bật chữ ghép mã hóa (ví dụ: =>, ===)",
  editorCursorStyle: "Kiểu con trỏ",
  editorCursorStyleDesc: "Hình dạng con trỏ soạn thảo",
  editorCursorBlink: "Con trỏ nhấp nháy",
  editorCursorBlinkDesc: "Phong cách hoạt hình của con trỏ",
  cursorLine: "Đường kẻ",
  cursorBlock: "Khối",
  cursorUnderline: "gạch chân",
  cursorLineThin: "Đường mỏng",
  cursorBlockOutline: "Khối phác thảo",
  cursorUnderlineThin: "Gạch chân mỏng",
  blinkBlink: "chớp mắt",
  blinkSmooth: "Trơn tru",
  blinkPhase: "Giai đoạn",
  blinkExpand: "Mở rộng",
  blinkSolid: "Chất rắn",
  manageThemes: "Quản lý chủ đề",
  manageThemesDesc: "Nhập hoặc xuất chủ đề màu của bạn",
  importTheme: "Nhập khẩu",
  exportTheme: "Xuất khẩu",
  borderStyle: "Kiểu viền",
  borderStyleDesc: "Bật hoặc tắt viền bảng điều khiển",
  borderStyleBordered: "có viền",
  borderStyleBorderless: "Không biên giới",
  hideSourceControl: "Ẩn kiểm soát nguồn",
  showSourceControl: "Hiển thị kiểm soát nguồn",

  // Newly added UI strings
  backBtn: "Mặt sau",
  onboardingStepSettingsTitle: "Cài đặt không gian làm việc",
  continueBtn: "Tiếp tục",
  welcomeThanks: "Hãy thiết lập OpenVibe cho quy trình làm việc của bạn.",
  startVibingBtn: "Hoàn tất thiết lập",
  rerunOnboarding: "Chạy trình hướng dẫn cài đặt",
  onboardingStepThemeTitle: "Chọn một chủ đề",
  letsVibeBtn: "Hãy rung cảm",
  animationSpeed: "Tốc độ hoạt ảnh",
  onboardingStepSettingsDesc: "Đặt tùy chọn của bạn ngay bây giờ hoặc thay đổi chúng sau.",
  onboardingStepAnimationDesc: "Chọn kiểu chuyển tiếp cho các thành phần giao diện và điều chỉnh độ mượt của chúng.",
  useRegionalProxy: "Sử dụng proxy khu vực (Châu Âu)",
  welcomeGreeting: "Xin chào, {name}",
  rerunOnboardingDesc: "Kích hoạt lại màn hình chào mừng ban đầu và trình hướng dẫn giới thiệu nhanh",
  useRegionalProxyDesc:
    "Định tuyến các yêu cầu API thông qua máy chủ proxy nhanh ở Châu Âu để vượt qua các hạn chế trong khu vực",
  onboardingStepThemeDesc: "Xem trước chủ đề trước khi bạn tiếp tục.",
  onboardingStepAnimationTitle: "Thiết lập hoạt ảnh",
  animationSpeedDesc: "Chuyển đổi giao diện và chia tỷ lệ hiệu ứng mượt mà",
  activityFetchUrl: "Đang tìm nạp trang web {url}",
  activityFetchUrlGeneral: "Đang tìm nạp trang web",
  activityGitBranches: "Xem các nhánh Git",
  activityGitCommand: "Thao tác Git: {lệnh}",
  activityGitDiff: "Kiểm tra khác biệt Git",
  activityGitLog: "Xem nhật ký cam kết Git",
  activityGitStatus: "Kiểm tra trạng thái Git",
  activityGroupAgent: "cuộc điều tra",
  activityGroupAgentN: "Điều tra — {count} nhiệm vụ",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "Điều tra — nhiệm vụ {count}",
  activityGroupBrowse: "duyệt thư mục",
  activityGroupBrowseN: "Đang duyệt {count} thư mục",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "Đang duyệt thư mục {count}",
  activityGroupCommand: "lệnh chạy",
  activityGroupCommandN: "Chạy lệnh {count}",
  activityGroupCommandN_few: "Выполнение {count} команд",
  activityGroupCommandN_one: "Đang chạy lệnh {count}",
  activityGroupEdit: "tập tin đã chỉnh sửa",
  activityGroupEditN: "Đang chỉnh sửa tệp {count}",
  activityGroupEditN_few: "Редактирование {count} файлов",
  activityGroupEditN_one: "Đang chỉnh sửa tệp {count}",
  activityGroupExternal: "công cụ bên ngoài",
  activityGroupExternalN: "Công cụ bên ngoài — {count} cuộc gọi",
  activityGroupExternalN_few: "Внешние инструменты — {count} вызова",
  activityGroupExternalN_one: "Công cụ bên ngoài — lệnh gọi {count}",
  activityGroupGit: "Hoạt động Git",
  activityGroupGitN: "Git — thao tác {count}",
  activityGroupGitN_few: "Git — {count} операции",
  activityGroupGitN_one: "Git — thao tác {count}",
  activityGroupRead: "đọc tập tin",
  activityGroupReadN: "Đọc tệp {count}",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "Đang đọc tệp {count}",
  activityGroupSearch: "tìm kiếm",
  activityGroupSearchN: "Tìm kiếm — truy vấn {count}",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "Tìm kiếm — truy vấn {count}",
  activityGroupTodo: "lập kế hoạch nhiệm vụ",
  activityGroupTodoN: "Lập kế hoạch — {count} nhiệm vụ",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "Lập kế hoạch — nhiệm vụ {count}",

  // Agent flow (linear run redesign)
  flowThinking: "Đang suy nghĩ…",
  flowThought: "Quá trình suy nghĩ",
  flowAnalysis: "Phân tích",
  flowCountRead: "{count} lượt đọc",
  flowCountSearch: "{count} lượt tìm kiếm",
  flowCountBrowse: "{count} lượt xem thư mục",
  flowCountWeb: "{count} lượt tìm kiếm web",
  flowCountGit: "{count} thao tác git",
  activityGroupTools: "hành động",
  activityGroupToolsN: "{đếm} hành động",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "hành động {đếm}",
  activityGroupWeb: "tìm kiếm trên mạng",
  activityGroupWebN: "Tìm kiếm trên web — truy vấn {count}",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "Tìm kiếm trên web — truy vấn {count}",
  activityInspectFolder: "Đang khám phá {tên}",
  activityInvestigateTask: "Nhiệm vụ điều tra",
  activityProjectStructure: "Khám phá cấu trúc dự án",
  activityReadCode: "Xem lại mã",
  activityReadFile: "Đang xem xét {name}",
  activityRepeatedCalls: "{count} cuộc gọi",
  activityRunCommand: "Kiểm tra dự án",
  activitySearchCode: "Tìm kiếm triển khai có liên quan",
  activitySearchQuery: "Đang tìm kiếm “{truy vấn}”",
  activityUpdateCode: "Đang cập nhật mã",
  activityUpdateFile: "Đang cập nhật {name}",
  activityUseTool: "Đang chạy {tên}",
  activityWebSearch: 'Đang tìm kiếm trên web cho "{query}"',
  activityWebSearchGeneral: "Tìm kiếm thông tin trên web",
  addModel: "Thêm mô hình",
  agentRunMinutesShort: "{đếm} phút",
  agentRunSeconds: "{đếm} giây",
  agentRunSecondsShort: "{đếm} giây",
  agentRunSeconds_few: "{đếm} giây",
  agentRunSeconds_one: "{đếm} giây",
  agentRunWorkedFor: "Đã làm việc được {time}",
  agentRunWorkingFor: "Làm việc {thời gian}",
  copyFormatted: "Sao chép văn bản",
  copyRaw: "Sao chép dưới dạng thô",
  customModelsLabel: "Người mẫu",
  errorNoticeBlockedTitle: "Quyền truy cập của nhà cung cấp bị hạn chế",
  errorNoticeNetworkTitle: "Không thể kết nối với dịch vụ",
  errorNoticeProviderTitle: "Nhà cung cấp trả lại lỗi",
  errorNoticeQuotaTitle: "Đã đạt đến giới hạn của nhà cung cấp",
  experimentalExtremeRadius: "Bán kính cực đại thử nghiệm (lên tới 100px)",
  experimentalExtremeRadiusDesc: "Cho phép thiết lập bán kính đường viền UI lên tới 100px. Cờ thử nghiệm!",
  fetchedUrl: "URL đã tìm nạp",
  fetchingUrl: "Đang tìm nạp URL",
  generateCommitMessage: "Tạo thông điệp cam kết với AI",
  gitBlame: "Phân tích quyền tác giả dòng",
  gitBlameDone: "Quyền tác giả của dòng được phân tích",
  gitBranches: "Kiểm tra chi nhánh",
  gitBranchesDone: "Chi nhánh được kiểm tra",
  gitDiff: "Xem xét các thay đổi",
  gitDiffDone: "Các thay đổi đã được xem xét",
  gitInspect: "Kiểm tra lịch sử Git",
  gitInspectDone: "Lịch sử Git đã kiểm tra",
  gitLog: "Xem xét các cam kết",
  gitLogDone: "Đã xem xét cam kết",
  gitRefs: "Kiểm tra giới thiệu Git",
  gitRefsDone: "Giới thiệu Git đã được kiểm tra",
  gitShow: "Kiểm tra đối tượng Git",
  gitShowDone: "Đối tượng Git được kiểm tra",
  gitStatus: "Tình trạng kiểm tra",
  gitStatusDone: "Trạng thái đã kiểm tra",
  hideToolCalls: "Ẩn cuộc gọi công cụ",
  modelDisplayName: "Tên hiển thị",
  modelIdPlaceholder: "id mẫu",
  promptMarkdown: "Đánh dấu trong đầu vào nhắc nhở",
  promptMarkdownDesc: "Hiển thị định dạng Markdown trực tiếp trong khi nhập lời nhắc",
  promptMarkdownGhost: "Hiển thị dấu cú pháp (**)",
  promptMarkdownGhostDesc: "Hiển thị các ký tự cú pháp bị làm mờ (**, `, #) bên trong văn bản được định dạng",
  reasoningEffortHigh: "Cao",
  reasoningEffortLow: "Thấp",
  reasoningEffortMedium: "Trung bình",
  reasoningEffortNone: "Không có",
  searchedWeb: "Tìm kiếm trên web",
  searchingWeb: "Tìm kiếm trên web",
  showToolCalls: "Hiển thị các cuộc gọi công cụ",
  tabStyle: "Kiểu tab",
  tabStyleDefault: "Mặc định",
  tabStyleDesc: "Viên thuốc vuông hoặc tròn cho tab soạn thảo",
  tabStylePills: "thuốc",
  todoBlocked: "Đã chặn nhiệm vụ",
  todoCompleted: "Nhiệm vụ đã hoàn thành",
  todoCount: "{đã hoàn thành} trong số {count}",
  todoCreated: "Đã tạo kế hoạch nhiệm vụ",
  todoPin: "Ghim danh sách nhiệm vụ",
  todoProgress: "Nhiệm vụ đã hoàn thành: {completed} trong tổng số {count}",
  todoTitle: "Nhiệm vụ",
  todoUnpin: "Bỏ ghim danh sách nhiệm vụ",
};
