import type { Translations } from "./ru";

export const zhTW: Partial<Translations> = {
  app: "應用程式",
  general: "一般",
  hotkeys: "快捷鍵",
  server: "伺服器",
  providers: "提供者",
  models: "模型",
  language: "語言",
  languageDesc: "更改 OpenVibe 的顯示語言",
  autoAccept: "自動接受權限",
  autoAcceptDesc: "權限請求將自動獲得批准",
  terminalShell: "終端 Shell",
  terminalShellDesc: "內建終端的命令列環境",
  showThinking: "顯示推理摘要",
  showThinkingDesc: "顯示模型的推理過程",
  theme: "主題",
  themeDesc: "選擇應用程式主題",
  colorScheme: "配色方案",
  colorSchemeDesc: "淺色、深色或系統",
  dark: "深色",
  light: "淺色",
  system: "系統",
  font: "字型",
  fontDesc: "主介面字型",
  systemFont: "系統",
  codeFont: "程式碼字型",
  codeFontDesc: "編輯器和終端的等寬字型",
  soundNotifications: "聲音通知",
  soundEnabled: "啟用聲音",
  soundEnabledDesc: "播放聲音通知",
  soundOnComplete: "任務完成",
  soundOnCompleteDesc: "成功完成時播放聲音",
  soundOnStop: "任務停止",
  soundOnStopDesc: "強制停止時播放聲音",
  connectedProviders: "已連線的提供者",
  disconnect: "中斷連線",
  connect: "連線",
  customProvider: "自訂提供者",
  searchModels: "搜尋模型...",
  loadingModels: "載入模型中...",
  noModels: "請至少連線一個提供者以檢視模型清單。",
  editProvider: "編輯提供者",
  customProviderTitle: "自訂提供者",
  name: "名稱",
  hideKey: "隱藏金鑰",
  showKey: "顯示金鑰",
  save: "儲存",
  newSession: "新對話",
  prevSession: "上一個對話",
  nextSession: "下一個對話",
  openTerminal: "開啟終端",
  searchPlaceholder: "搜尋指令、檔案...",
  searchIn: "在 {folder} 中搜尋",
  menu: "選單",
  hideSessions: "隱藏對話",
  showSessions: "顯示對話",
  newSessionTitle: "新對話",
  prevSessionTitle: "上一個對話",
  nextSessionTitle: "下一個對話",
  toggleTerminal: "切換終端",
  toggleSessions: "切換對話",
  hideFileTree: "隱藏檔案樹",
  showFileTree: "顯示檔案樹",
  toggleFileTree: "切換檔案樹",
  close: "關閉",
  minimizeLabel: "最小化",
  maximizeLabel: "最大化",
  closeLabel: "關閉",
  welcomeSubtitle: "沒有打開的專案。選擇一個資料夾以在其中開始對話。",
  openProject: "開啟專案",
  fatalErrorTitle: "無法啟動 vibe",
  fatalErrorHint: "在 vibe 旁邊的 .env 檔案、~/.vibe/config 或環境變數中設定 VIBE_API_KEY。",
  loadingText: "OpenVibe 正在載入…",
  noSessions: "暫無對話",
  untitled: "無標題",
  deleteSession: "刪除對話",
  selectModel: "選擇模型：",
  revertToMessage: "回復到該訊息",
  copy: "複製",
  completed: "已完成",
  diff: "差異",
  regenerate: "重新產生",
  reading: "讀取中",
  read: "已讀取",
  failedWrite: "寫入失敗",
  writing: "寫入中",
  written: "已建立",
  failedEdit: "編輯失敗",
  editing: "編輯中",
  edited: "已編輯",
  listing: "列出中",
  listed: "已列出",
  searchingCodebase: "程式碼庫搜尋中",
  searchedCodebase: "Search in codebase",
  running: "執行中",
  ran: "已執行",
  tool: "工具",
  newFile: "新增檔案",
  newFolder: "新增資料夾",
  rename: "重新命名",
  cut: "剪下",
  paste: "貼上",
  delete: "刪除",
  deleteConfirm: "刪除 {name}？",
  createFailed: "建立失敗：{error}",
  renameFailed: "重新命名失敗：{error}",
  newFileTooltip: "新增檔案",
  newFolderTooltip: "新增資料夾",
  refreshTooltip: "重新整理",
  collapseAllTooltip: "全部折疊",
  loading: "載入中…",
  closeProject: "關閉專案",
  openProjectMenuItem: "開啟專案",
  revealExplorer: "在檔案總管中顯示",
  removeFromList: "從清單中移除",
  openFolder: "開啟資料夾",
  settings: "設定",
  stop: "停止",
  runCommand: "執行命令",
  sendMessage: "傳送訊息",
  dropFilesAttach: "拖放檔案以附加",
  remove: "移除",
  attachFiles: "附加檔案",
  cancel: "取消",
  processing: "處理中...",
  vibeAnything: "輸入一些內容...",
  selectModelFallback: "選擇模型",
  searchModelPlaceholder: "搜尋模型...",
  addProvider: "新增提供者",
  configureModels: "設定模型",
  noModelsFound: "找不到模型",
  noModelsEnabled: "沒有啟用的模型",
  searching: "搜尋中…",
  noMatches: "無相符項",
  terminal: "終端機",
  search: "搜尋",
  terminalTab: "終端機 {num}",
  closeTab: "關閉分頁",
  newTerminal: "新增終端機",
  shellExited: "[shell 以代碼 {code} 退出]",
  cannotOpenFile: "無法開啟檔案",
  retry: "重試",
  openFileFromTree: "從檔案樹開啟檔案",
  unsavedChanges: "未儲存的變更",
  closeFile: "關閉 {filename}",
  filePath: "檔案路徑",
  selectFileToEdit: "選擇要編輯的檔案",
  copyCode: "複製",
  openSettingsHotkey: "開啟設定",
  clearChatHotkey: "清除聊天",
  manuallyStopped: "已由用戶停止",

  // MCP
  edit: "編輯",
  mcpServers: "MCP 伺服器",
  mcpServersCount: "MCP 伺服器 ({count})",
  mcpRefreshStatuses: "重新整理狀態",
  mcpNoServersConfigured: "未設定 MCP 伺服器",
  mcpOpenSettings: "開啟 MCP 設定",
  mcpAddServer: "新增伺服器",
  mcpVisualEditor: "編輯器",
  mcpRawConfig: "Raw 設定",
  mcpExport: "匯出",
  mcpImport: "匯入",
  mcpSaveTomlConfig: "儲存 TOML 設定",
  mcpEnableServer: "啟用伺服器",
  mcpDisableServer: "停用伺服器",
  mcpStartServer: "啟動伺服器",
  mcpStopServer: "停止伺服器",
  mcpAddServerTitle: "新增 MCP 伺服器",
  mcpEditServerTitle: "編輯 MCP 伺服器",
  mcpServerName: "伺服器名稱",
  mcpCommandPath: "指令（執行檔路徑）",
  mcpCommandPlaceholder: "npx、uvx 或 /path/to/binary",
  mcpArguments: "參數（以空格分開）",
  mcpEnvVariables: "環境變數",
  mcpEnvKeyPlaceholder: "鍵",
  mcpEnvValuePlaceholder: "值",
  mcpAddEnvVar: "+ 新增環境變數",
  mcpEnableOnStartup: "啟動時啟用",
  mcpSaveServer: "儲存伺服器",
  mcpDeleteConfirm: "確定要刪除 MCP 伺服器「{name}」嗎？",
  mcpServerNameRequired: "伺服器名稱為必填項目。",
  mcpServerCommandRequired: "伺服器指令為必填項目。",
  mcpServerExists: "已存在同名的伺服器。",
  mcpSaveFailed: "儲存失敗: {error}",
  mcpInvalidJsonFormat: "MCP 設定 JSON 格式無效",
  mcpFailedParseJson: "無法解析匯入的 JSON",
  mcpInvalidConfigFormat: "設定格式無效: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 個檔案已變更",
  commitFileChanged_few: "{count} 個檔案已變更",
  commitFileChanged: "{count} 個檔案已變更",
  commitInsertion_one: "1 行插入(+)",
  commitInsertion_few: "{count} 行插入(+)",
  commitInsertion: "{count} 行插入(+)",
  commitDeletion_one: "1 行刪除(-)",
  commitDeletion_few: "{count} 行刪除(-)",
  commitDeletion: "{count} 行刪除(-)",
  openCommit: "開啟提交",
  copyCommitHash: "複製提交雜湊",
  openOnGitHub: "在 GitHub 上開啟",
  noFilesChanged: "沒有變更的檔案",
  inlineGenerating: "正在生成程式碼...",
  inlineEditCode: "請求 Inline Vibe 編輯程式碼...",
  inlineRefineCode: "請求 Inline Vibe 再次優化/編輯...",
  inlineSend: "傳送 (Ctrl+Enter)",
  inlineAccept: "接受變更",
  inlineReject: "拒絕",
  inlinePrevDiff: "上一個差異",
  inlineNextDiff: "下一個差異",
  videoPlay: "播放 (Space)",
  videoPause: "暫停 (Space)",
  videoMute: "靜音 (M)",
  videoUnmute: "取消靜音 (M)",
  videoVolume: "音量",
  videoPlaybackSpeed: "播放速度",
  videoFullscreen: "全螢幕 (F)",
  failedReadFile: "讀取檔案失敗",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "複製",
  regenerateMessage: "重新生成",

  // Source control
  sourceControl: "原始碼控制",
  viewAsFlatList: "查看平面列表",
  viewsAndMoreActions: "視圖和更多操作...",
  stageAllChanges: "暫存所有變更",
  checkoutCreateBranch: "結帳/建立分支...",
  refreshStatus: "刷新狀態",
  repositories: "儲存庫",
  commitMessagePlaceholder: "訊息（Ctrl+Enter 以在“{branch}”上提交）",
  commitBtn: "犯罪",
  filterChangesPlaceholder: "過濾器更改（例如 *.ts、src/）",
  clearFilter: "清除過濾器",
  noChangesDetected: "在儲存庫中未偵測到任何變更。",
  stagedChanges: "階段性改變",
  unstageAll: "全部取消暫存",
  unstageChanges: "取消暫存更改",
  discardChanges: "放棄更改",
  stageChanges: "階段變化",
  graph: "圖形",
  noCommitsInGraph: "圖表歷史記錄中沒有提交。",
  newBranchName: "新的分店名稱...",
  createBranchBtn: "創造",
  currentBranch: "（當前的）",

  // Auto-added translated keys
  renderFileTree: "美麗的文件樹",
  renderFileTreeDesc: "將資料夾結構渲染為漂亮的 UI 元件而不是原始文本",
  apiKeyPlaceholder: "API金鑰",
  customIcon: "自訂圖示（URL 或上傳）",
  modelsUrl: "型號清單 URL（可選）",
  headers: "標頭",
  parameters: "參數",
  headerKey: "標頭名稱",
  headerValue: "標頭值",
  paramKey: "參數名稱",
  paramValue: "參數值",
  uploadIcon: "上傳圖示",
  closeTerminal: "關閉終端",
  hideButton: "隱藏",
  showButton: "展示",
  restoreButtons: "恢復按鈕",
  filesChanged: "{count} 個檔案已更改",
  filesChanged_one: "{count} 個檔案已更改",
  filesChanged_few: "{count} 個檔案已更改",
  changes: "變化",
  exploring: "探索",
  explored: "探索",
  editProject: "編輯",
  editProjectTitle: "編輯項目",
  projectIcon: "圖示",
  backgroundColor: "背景顏色",
  closeFromList: "關閉",
  searchInCode: "在代碼中搜尋",
  searchInCodePlaceholder: "搜尋",
  replacePlaceholder: "代替",
  refreshSearch: "重新整理搜尋",
  clearSearchResults: "清除搜尋結果",
  viewAsTree: "以樹形式查看",
  showReplace: "顯示替換",
  hideReplace: "隱藏替換",
  matchCase: "火柴盒",
  matchWholeWord: "匹配整個單字",
  useRegex: "使用正規表示式",
  preserveCase: "保存箱",
  replaceAll: "全部替換",
  filesToIncludeExclude: "要包含/排除的文件",
  filesToInclude: "要包含的文件",
  filesToExclude: "要排除的文件",
  includePlaceholder: "例如*.ts，src/**",
  excludePlaceholder: "例如節點模組，*.test.ts",
  noResultsFound: "沒有找到結果。",
  searchInCodeResults_one: "{count} 個結果位於 {fileCount} 個檔案中",
  searchInCodeResults_few: "{count} 個結果產生 {fileCount} 個文件",
  searchInCodeResults: "{count} 個結果產生 {fileCount} 個文件",
  typeToSearch: "輸入搜尋查詢以按內容尋找文件。",
  loadingMatches: "載入中...",
  moreMatches_one: "… 還有 {count} 條匹配項",
  moreMatches_few: "…還有 {count} 場比賽",
  moreMatches: "…還有 {count} 場比賽",
  newProjectHotkey: "新專案",
  closeProjectHotkey: "關閉專案",
  closeFileHotkey: "關閉文件",
  navigation: "導航",
  chat: "聊天",
  workspace: "工作空間",
  project: "專案",
  editor: "編輯",
  noHotkeys: "沒有載入熱鍵",
  design: "設計",
  animations: "動畫",
  animStyleFade: "褪色",
  animStyleSlide: "滑動",
  animStyleScale: "規模",
  animStyleFadeSlide: "淡入淡出 + 滑動",
  animStyleNone: "無動畫",
  animProjectHover: "項目懸停",
  animProjectHoverDesc: "將滑鼠懸停在項目圖塊上時的動畫",
  animProjectSwitch: "項目切換",
  animProjectSwitchDesc: "打開新專案時的過渡",
  animSidebarSlide: "側邊欄",
  animSidebarSlideDesc: "打開/關閉側面板",
  animContextMenu: "內容選單",
  animContextMenuDesc: "上下文選單外觀",
  animButtons: "按鈕",
  animButtonsDesc: "懸停時的互動元素",
  animPanelAppear: "面板和模態框",
  animPanelAppearDesc: "設定、彈出視窗和模式外觀",
  animMultiplier: "動畫流暢度",
  animMultiplierDesc:
    "Animation smoothness multiplier. 0 = stopped, 0.5 = snappy, 1 = normal, 2 = smooth, 5 = ultra smooth",
  windowEffects: "視窗效果",
  blurOverlay: "背景模糊",
  blurOverlayDesc: "模糊模式視窗後面的內容（設定、上下文選單）",
  blurNone: "沒有任何",
  blurSubtle: "微妙的",
  blurStrong: "強的",
  borderRadius: "邊界半徑",
  borderRadiusDesc: "UI 元素的圓角",
  uiZoom: "使用者介面縮放",
  zoomStep: "變焦步長",
  zoomStepDesc: "每次按 Ctrl+加號/Ctrl+減號可改變縮放等級多少",
  zoomDefault: "預設縮放",
  zoomDefaultDesc: "按 Ctrl+0 時的縮放級別",
  appName: "OpenVibe 桌面",
  appVersion: "v1.3.9",
  shell: "殼",
  langRussian: "俄文",
  langEnglish: "英語",
  langChinese: "中文 (繁體)",
  langChineseSimplified: "簡體中文",
  langUkrainian: "烏克蘭",
  langBelarusian: "白俄羅斯語",
  langSpanish: "西班牙語",
  langItalian: "義大利語",
  langPortuguese: "葡萄牙語",
  langJapanese: "日本人",
  langSerbian: "塞爾維亞",
  langFrench: "法語",
  langGerman: "德文",
  langHindi: "印地語",
  langArabic: "阿拉伯",
  langIndonesian: "印尼",
  langKorean: "韓國人",
  langTurkish: "土耳其",
  langVietnamese: "越南語",
  langPolish: "拋光",
  langDutch: "荷蘭語",
  langRomanian: "羅馬尼亞語",
  langGreek: "希臘文",
  langSwedish: "瑞典",
  langKazakh: "哈薩克語",
  langAzerbaijani: "亞塞拜然語",
  langThai: "泰國",
  langBengali: "孟加拉",
  langPunjabi: "旁遮普語",
  langBulgarian: "保加利亞語",
  langCzech: "捷克語",
  langFilipino: "菲律賓人",
  langPersian: "波斯語",
  langMalay: "馬來語",
  langBurmese: "緬甸語",
  langAmharic: "阿姆哈拉語",
  langMarathi: "馬拉地語",
  codeTab: "程式碼",
  editorFontSize: "字體大小",
  editorFontSizeDesc: "編輯器和終端字體大小",
  editorLineHeight: "行高",
  editorLineHeightDesc: "編輯器行高乘數",
  editorLigatures: "字體連字",
  editorLigaturesDesc: "啟用編碼連字（例如 =>、===）",
  editorCursorStyle: "遊標樣式",
  editorCursorStyleDesc: "編輯器遊標的形狀",
  editorCursorBlink: "遊標閃爍",
  editorCursorBlinkDesc: "遊標動畫樣式",
  cursorLine: "線",
  cursorBlock: "堵塞",
  cursorUnderline: "強調",
  cursorLineThin: "細線",
  cursorBlockOutline: "塊輪廓",
  cursorUnderlineThin: "底線細",
  blinkBlink: "眨",
  blinkSmooth: "光滑的",
  blinkPhase: "階段",
  blinkExpand: "擴張",
  blinkSolid: "堅硬的",
  manageThemes: "管理主題",
  manageThemesDesc: "匯入或匯出您的顏色主題",
  importTheme: "進口",
  exportTheme: "出口",
  borderStyle: "邊框樣式",
  borderStyleDesc: "開啟或關閉面板邊框",
  borderStyleBordered: "有邊框",
  borderStyleBorderless: "無邊框",
  hideSourceControl: "隱藏原始碼管理",
  showSourceControl: "顯示原始碼控制",

  // Newly added UI strings
  backBtn: "後退",
  onboardingStepSettingsTitle: "工作區設定",
  continueBtn: "繼續",
  welcomeThanks: "讓我們為您的工作流程設定 OpenVibe。",
  startVibingBtn: "完成設定",
  rerunOnboarding: "運行安裝精靈",
  onboardingStepThemeTitle: "選擇一個主題",
  letsVibeBtn: "讓我們來感受一下",
  animationSpeed: "動畫速度",
  onboardingStepSettingsDesc: "立即設定您的首選項或稍後更改它們。",
  onboardingStepAnimationDesc: "選擇介面元素的過渡樣式並調整其平滑度。",
  useRegionalProxy: "使用區域代理（歐洲）",
  welcomeGreeting: "你好，{name}",
  rerunOnboardingDesc: "重新觸發初始歡迎畫面和快速入門嚮導",
  useRegionalProxyDesc: "透過歐洲的快速代理伺服器路由 API 請求以繞過區域限制",
  onboardingStepThemeDesc: "在繼續之前預覽主題。",
  onboardingStepAnimationTitle: "動畫設定",
  animationSpeedDesc: "界面過渡和平滑效果縮放",
  activityFetchUrl: "正在取得網頁 {url}",
  activityFetchUrlGeneral: "正在取得網頁",
  activityGitBranches: "查看 Git 分支",
  activityGitCommand: "Git操作：{指令}",
  activityGitDiff: "檢查 Git 差異",
  activityGitLog: "查看Git提交日誌",
  activityGitStatus: "檢查 Git 狀態",
  activityGroupAgent: "調查",
  activityGroupAgentN: "調查 — {count} 項任務",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "調查 — {count} 項任務",
  activityGroupBrowse: "瀏覽資料夾",
  activityGroupBrowseN: "正在瀏覽 {count} 個資料夾",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "正在瀏覽 {count} 個資料夾",
  activityGroupCommand: "運行命令",
  activityGroupCommandN: "執行 {count} 個命令",
  activityGroupCommandN_few: "Выполнение {count} команд",
  activityGroupCommandN_one: "執行 {count} 命令",
  activityGroupEdit: "編輯過的文件",
  activityGroupEditN: "編輯 {count} 個文件",
  activityGroupEditN_few: "Редактирование {count} файлов",
  activityGroupEditN_one: "正在編輯 {count} 個文件",
  activityGroupExternal: "外部工具",
  activityGroupExternalN: "外部工具 — {count} 次調用",
  activityGroupExternalN_few: "Внешние инструменты — {count} вызова",
  activityGroupExternalN_one: "外部工具 — {count} 調用",
  activityGroupGit: "Git操作",
  activityGroupGitN: "Git — {count} 次操作",
  activityGroupGitN_few: "Git — {count} операции",
  activityGroupGitN_one: "Git — {count} 操作",
  activityGroupRead: "讀取文件",
  activityGroupReadN: "正在讀取 {count} 個文件",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "正在讀取 {count} 個文件",
  activityGroupSearch: "搜尋",
  activityGroupSearchN: "搜尋 — {count} 筆查詢",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "搜尋 — {count} 筆查詢",
  activityGroupTodo: "任務規劃",
  activityGroupTodoN: "計劃 — {count} 項任務",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "計劃 — {count} 項任務",

  // Agent flow (linear run redesign)
  flowThinking: "思考中…",
  flowThought: "思考過程",
  flowAnalysis: "分析",
  flowCountRead: "{count} 次讀取",
  flowCountSearch: "{count} 次搜尋",
  flowCountBrowse: "{count} 次瀏覽目錄",
  flowCountWeb: "{count} 次網路搜尋",
  flowCountGit: "{count} 次 git 操作",
  activityGroupTools: "行動",
  activityGroupToolsN: "{count} 次操作",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "{count} 個操作",
  activityGroupWeb: "網路搜尋",
  activityGroupWebN: "網路搜尋 — {count} 條查詢",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "網路搜尋 — {count} 條查詢",
  activityInspectFolder: "探索{名稱}",
  activityInvestigateTask: "調查任務",
  activityProjectStructure: "探索項目結構",
  activityReadCode: "檢查程式碼",
  activityReadFile: "正在審核{name}",
  activityRepeatedCalls: "{count} 次通話",
  activityRunCommand: "檢查項目",
  activitySearchCode: "尋找相關實現",
  activitySearchQuery: "搜尋“{query}”",
  activityUpdateCode: "更新程式碼",
  activityUpdateFile: "正在更新{名稱}",
  activityUseTool: "正在運行{名稱}",
  activityWebSearch: "在網路上搜尋“{query}”",
  activityWebSearchGeneral: "在網路上搜尋資訊",
  addModel: "新增型號",
  agentRunMinutesShort: "{計數}米",
  agentRunSeconds: "{count} 秒",
  agentRunSecondsShort: "{count} 個",
  agentRunSeconds_few: "{count} 秒",
  agentRunSeconds_one: "{count} 秒",
  agentRunWorkedFor: "工作了{時間}",
  agentRunWorkingFor: "工作{時間}",
  copyFormatted: "複製文字",
  copyRaw: "複製為原始文件",
  customModelsLabel: "型號",
  errorNoticeBlockedTitle: "提供者存取受到限制",
  errorNoticeNetworkTitle: "無法聯繫服務",
  errorNoticeProviderTitle: "提供者回傳錯誤",
  errorNoticeQuotaTitle: "已達到提供者限制",
  experimentalExtremeRadius: "實驗極限半徑（最大 100px）",
  experimentalExtremeRadiusDesc: "允許將 UI 邊框半徑設定為最大 100 像素。實驗旗幟！",
  fetchedUrl: "取得的網址",
  fetchingUrl: "正在取得網址",
  generateCommitMessage: "使用 AI 產生提交訊息",
  gitBlame: "分析線路作者身份",
  gitBlameDone: "分析線路作者",
  gitBranches: "檢查分支機構",
  gitBranchesDone: "檢查分行",
  gitDiff: "審查變更",
  gitDiffDone: "已審核變更",
  gitInspect: "檢查 Git 歷史記錄",
  gitInspectDone: "檢查 Git 歷史記錄",
  gitLog: "審查提交",
  gitLogDone: "已審查的提交",
  gitRefs: "檢查 Git 引用",
  gitRefsDone: "檢查了 Git 參考",
  gitShow: "檢查 Git 對象",
  gitShowDone: "檢查的 Git 對象",
  gitStatus: "檢查狀態",
  gitStatusDone: "檢查狀態",
  hideToolCalls: "隱藏工具調用",
  modelDisplayName: "顯示名稱",
  modelIdPlaceholder: "型號 ID",
  promptMarkdown: "提示輸入中的 Markdown",
  promptMarkdownDesc: "在輸入提示時即時渲染 Markdown 格式",
  promptMarkdownGhost: "顯示語法標記 (**)",
  promptMarkdownGhostDesc: "在格式化文字內顯示灰色語法字元（**、`、#）",
  reasoningEffortHigh: "高的",
  reasoningEffortLow: "低的",
  reasoningEffortMedium: "中等的",
  reasoningEffortNone: "沒有任何",
  searchedWeb: "網頁搜尋",
  searchingWeb: "搜尋網頁",
  showToolCalls: "顯示工具調用",
  tabStyle: "選項卡樣式",
  tabStyleDefault: "預設",
  tabStyleDesc: "用於編輯器選項卡的方形或圓形藥丸",
  tabStylePills: "藥丸",
  todoBlocked: "任務被阻止",
  todoCompleted: "已完成任務",
  todoCount: "{已完成}，共 {count} 個",
  todoCreated: "已建立任務計劃",
  todoPin: "固定任務列表",
  todoProgress: "已完成的任務：{completed}（共 {count}）",
  todoTitle: "任務",
  todoUnpin: "取消固定任務列表",
};
