import type * as monaco from "monaco-editor";

export const monokai: monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2", background: "272822" },
    { token: "invalid", foreground: "f8f8f0", background: "f92672" },
    { token: "keyword", foreground: "f92672" },
    { token: "storage.type", foreground: "66d9ef", fontStyle: "italic" },
    { token: "storage.modifier", foreground: "66d9ef", fontStyle: "italic" },
    { token: "constant.numeric", foreground: "ae81ff" },
    { token: "constant.language", foreground: "ae81ff" },
    { token: "constant.character", foreground: "ae81ff" },
    { token: "constant.other", foreground: "ae81ff" },
    { token: "variable.language", foreground: "f8f8f2" },
    { token: "variable.other", foreground: "f8f8f2" },
    { token: "string", foreground: "e6db74" },
    { token: "comment", foreground: "75715e" },
    { token: "entity.name.type", foreground: "a6e22e", fontStyle: "underline" },
    { token: "entity.name.function", foreground: "a6e22e" },
    { token: "entity.other.inherited-class", foreground: "a6e22e", fontStyle: "italic underline" },
    { token: "variable.parameter", foreground: "fd971f", fontStyle: "italic" },
    { token: "entity.name.tag", foreground: "f92672" },
    { token: "entity.other.attribute-name", foreground: "a6e22e" },
    { token: "support.function", foreground: "66d9ef" },
    { token: "support.constant", foreground: "66d9ef" },
    { token: "support.type", foreground: "66d9ef", fontStyle: "italic" },
    { token: "support.class", foreground: "66d9ef", fontStyle: "italic" },
  ],
  colors: {
    "editor.foreground": "#F8F8F2",
    "editor.background": "#272822",
    "editor.selectionBackground": "#49483E",
    "editor.lineHighlightBackground": "#3E3D32",
    "editorCursor.foreground": "#F8F8F0",
    "editorWhitespace.foreground": "#3B3A32",
    "editorIndentGuide.activeBackground": "#9D550F",
    "editor.selectionHighlightBackground": "#333333",
  },
};
